### ISSUE TITLE
set streaming.useNativeHlsOnSafari: false， then the video cannot be played on ios safari.

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#6922] opened 2024-06-27 03:32 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.9.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
I don't know

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
ios 17.5
the default version safari of ios 17.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

I create  very simple page to show the bug:
when I set 
```
player.configure({
    streaming: {
      useNativeHlsOnSafari: false,
    },
  });
```
Then open the page on `ios's safari browser` The video cannot be played.
The `shaka-ios-safari-error.html` does't work normal and the `shaka-ios-safari-ok.html ` can work on ios's safari.

the code page: https://github.com/issuebox/player/blob/main/shaka-ios-safari-error.html
the visite page: https://issuebox.github.io/player/shaka-ios-safari-error.html

It is the same media source with  https://github.com/issuebox/player/blob/main/shaka-ios-safari-ok.html , which visite with  https://issuebox.github.io/player/shaka-ios-safari-ok.html ,if I use `streaming.useNativeHlsOnSafari: true`, it works ok on ios safari!

**What did you expect to happen?**
I hope it can play on the iphone's safari browser when I set `streaming.useNativeHlsOnSafari: false`

**What actually happened?**

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment] 2024-06-27 06:13
Duplicate of https://github.com/shaka-project/shaka-player/issues/6315. Recommendation: Use fMP4 instead of TS

**Closed by avelad** 2024-06-27 06:13 UTC
Labels: type: bug
