### ISSUE TITLE
"position" setting is ignored for webvtt cues

### ISSUE THREAD

**Issue by Peterdoo** [shaka-project/shaka-player#4957] opened 2023-02-02 18:15 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.3.4-uncompiled

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Demo app shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome Version 109.0.5414.120 (Official Build) (64-bit) on Win11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo app shaka-player-demo.appspot.com

**What did you do?**

Played a HLS video with the following cues in the webvtt file:
10:00:00.000 --&gt; 10:00:00.662 line:90%,end position:10%,line-left align:start
Left
both lines

10:00:01.184 --&gt; 10:00:03.903 line:90%,end position:90%,line-right align:end
Right
both lines

**What did you expect to happen?**
According to the webvtt spec, the setting "position" for cue is supposed to control the horizontal position of the box containing text.
position:10% is 10% from the left and position:90% is 10% from the right. The "line-left" or "line-right" only refers to the physical side of the box to which the "position" setting applies. It does not affect or relate to the direction or position of the text itself within the box.

The first cue should be displayed as:
Text left aligned inside of the box (align:start).
The left edge (line-left) of the box containing text should be positioned at 10% from the left (position 10%).

The second cue should be displayed as:
Text right aligned inside of the box (align:end).
The right edge (line-right) of the box containing text should be positioned at 10% from the right (position:90%).

**What actually happened?**

Text is correctly aligned within the box. "align" setting is respected correctly.
The box is always displayed centered, ignoring the setting "position" and "line-left", "line-right".
The setting "line" that is used for vertical positioning and works in a similar way than "position" works correctly.

This is how it looks like:

![image](https://user-images.githubusercontent.com/33329671/216409936-221930d6-049f-4703-a141-16ec795dda9e.png)

![image](https://user-images.githubusercontent.com/33329671/216410188-ed21a6bc-839e-4136-952a-8c16aa7b99e2.png)

**Comment by avelad** [comment] 2023-02-02 18:25
Duplicate of https://github.com/shaka-project/shaka-player/issues/4486

**Closed by avelad** 2023-02-02 18:25 UTC
Labels: type: bug
