### ISSUE TITLE
DASH <EssentialProperty> parsing problem

### ISSUE THREAD

**Issue by alexhmit** [shaka-project/shaka-player#4374] opened 2022-07-26 03:42 UTC
Current DASH parser only recognizes TransferCharacteristics. The other 2 legit properties MatrixCoefficients and ColourPrimariesColourPrimaries are not recognized.  Unrecognized essential property has its parent element dropped implemented according to the spec. This usually results in the adaptation being dropping which could be the whole media.

Basically any DASH manifest containing valid MatrixCoefficients  and ColourPrimariesColourPrimaries essential properties are not playable by Shaka.

Is there a legitimate reason for such severe restriction or is this just an oversight?

Thanks

**Comment by joeyparrish** [comment] 2022-07-28 21:28
I'm looking into it now.  (Next time, please use one of our issue templates.)

**Comment by joeyparrish** [comment] 2022-07-28 21:31
It appears to be well-documented in the source code and quotes the DASH spec:

https://github.com/shaka-project/shaka-player/blob/5102dac96cb1a749fefeb1f6b7a24c13f6b1077b/lib/dash/dash_parser.js#L1023-L1032

So I'm going to call this "working as intended" from the spec point of view.

If you'd like to add support for `MatrixCoefficients` and `ColourPrimariesColourPrimaries`, please send a PR.  I'll convert this into an enhancement and assign it back to you on the assumption that you want these.  Thanks!

**Comment by alexhmit** [comment] 2022-07-28 21:38
Thanks for the reply.

Dropping the parent is according to the spec when there are unrecognized values. But why are MatrixCoefficients and ColourPrimariesColourPrimaries not recognized when they are clearly documented in the spec?

Thanks

**Comment by joeyparrish** [comment] 2022-07-28 22:33
Because Shaka Player doesn't recognize them.  "Unrecognized" doesn't mean "invalid".  It just means our parser does not know what they are.  Feel free to change that!

<EssentialProperty> is supposed to be "essential" or "required".  So anything "essential" we don't know about, we assume (per the spec) that we can't handle.  If you know that those two properties don't affect the web platform's ability to play back content, you can add clauses for them in the parser and ignore them.  If they _can_ affect the platform's ability to play back content, then they need to be fed into MediaCapabilities to query for support.

**Comment by alexhmit** [comment] 2022-07-29 02:45
Thanks for the repeated explanation. I was hoping more proactive approach to support the 'norm'. As is, some MAJOR streaming service cannot use Shaka as is and thus consider moving away from it reluctantly.

Thanks again for the explanation. We can close this discussion.

**Comment by joeyparrish** [comment] 2022-07-29 04:01
I suggested a way you can contribute a fix.  Since you did not use our issue template or provide links to the affected content, we are not able to verify any potential fix.  But if you want to contribute a fix and verify that is solves your issue, I would welcome that PR.

If you'd rather move away from Shaka than contribute, that's your choice.  We'll be sorry to see you go.

**Comment by alexhmit** [comment] 2022-07-29 17:27
It is not us moving away from Shaka; we are helping the major streaming service to get their stream playing with Shaka.

We can patch Shaka but the service do not feel that one has to patch something that is part of the spec especially a relatively easy one. They do not feel this is a trustworthy long term relationship.

We are somewhat neutral to this. We can understand the streaming service's concerns and we also understand that you have your priority.

Believe it or not that we are actually an advocate for Shaka.

Good luck and keep up the good work!

**Comment by joeyparrish** [comment] 2022-07-29 18:53
We're not suggesting you "patch" it in the sense that you keep and deploy private patches that differ from what's in the repo.  Are you interested to contribute your suggested change as a PR?

We can't verify fixes for content we don't have access to, so there is no way we could make the change and verify it on our end unless you choose to share the content URL.  But since Shaka is open source, you should feel empowered to make a change and send a PR once you have verified that it works for your streaming service's content.

Does that clear things up?

**Comment by alexhmit** [comment] 2022-07-29 23:52
The issue here does not require actual content. It is a parsing problem. Just need to have the <EssentialProperty> nodes in a manifest and make sure the containing adaptation does not get dropped. Effecting the property values is not even required here.

It is also not about the effort required to do this or who does it. This is a very small effort. (We might even do the PR in the future although that is not really our charter.)

But this does not salvage the stream services who were considering using Shaka. Again, this is not our decision. They have some reservation about Shaka project's treatment of such problem rightly or wrongly.

Your message is loud and clear.

Thanks

**Closed** 2022-07-30 00:23 UTC
Labels: type: enhancement, priority: P3, component: DASH
