### ISSUE TITLE
Double-tap to seek on mobile

### ISSUE THREAD

**Issue by aditmehta9** [shaka-project/shaka-player#3303] opened 2021-04-01 13:13 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Describe the solution you'd like**

There is a replay icon in the video element when viewed in the browser but not in mobile view so the replay icon can be added.
Addition of the feature like youtube in mobile which allows fast forward on double click on right side of the screen and rewinds on the left side of the screen.

**Additional context**
![image](https://user-images.githubusercontent.com/35133994/113298895-ef1c3200-9319-11eb-9f2c-037aba9f1319.png)
![image](https://user-images.githubusercontent.com/35133994/113299056-17a42c00-931a-11eb-8c59-9854f5568a1d.png)

**Comment by aditmehta9** [comment] 2021-04-02 04:49
If someone wants to work on this issue for part one, one has to do a similar thing like this [PR](https://github.com/google/shaka-player/pull/3253) for big play button file.

**Comment by prsndp** [comment] 2021-04-04 09:16
Hi, @aditmehta9 I want to work on this issue. Please assign me if it is open.

**Comment by aditmehta9** [comment] 2021-04-04 09:18
> Hi, @aditmehta9 I want to work on this issue. Please assign me if it is open.

I can't assign only members can assign.

**Comment by prsndp** [comment] 2021-04-04 09:25
then,  @aditmehta9  how can I join as a member?

**Comment by aditmehta9** [comment] 2021-04-04 09:26
> then, @aditmehta9 how can I join as a member?

Sorry, I meant only members can assign you we can't be a member.

**Comment by prsndp** [comment] 2021-04-04 09:29
Ooh!! sorry for the misunderstanding from my end.

**Comment by prsndp** [comment] 2021-04-04 09:29
> > then, @aditmehta9 how can I join as a member?
> 
> Sorry, I meant only members can assign you we can't be a member.

Ooh!! sorry for the misunderstanding from my side.

**Comment by nbcl** [comment] 2021-04-12 05:37
Hello @prsndp!

Are you still working on a fix for this issue?

Please let me know if you need any help approaching the solution and I will be happy to help!

**Comment by prsndp** [comment] 2021-04-12 12:13
HI @nbcl! Yeah, sure. I'm working on this issue. 
There is any deadline for this?

**Comment by nbcl** [comment] 2021-04-12 14:56
> There is any deadline for this?

As far as I understand, there should not be any because it is not currently assigned to any milestone or label!

> HI @nbcl! Yeah, sure. I'm working on this issue.

Let me know if I can be of help!

**Comment by prsndp** [comment] 2021-04-13 10:54
> > There is any deadline for this?
> 
> As far as I understand, there should not be any because it is not currently assigned to any milestone or label!
> 
> > HI @nbcl! Yeah, sure. I'm working on this issue.
> 
> Let me know if I can be of help!

Yeah Sure!

**Comment by ismena** [comment] 2021-04-13 17:16
You are correct, if the issue is not assigned to a milestone, there is no deadline.
@prsndp  @nbcl I'm assigning you both per your interest.

**Comment by nbcl** [comment] 2021-04-13 18:08
Great!

@prsndp, feel free to create a pull request or draft with your updates whenever you feel ready, and I will make sure to check in and provide any feedback that could be useful if it was needed.

I can also provide feedback on your personal fork if you point me to a specific branch if that is what you prefer!

Let me know!

**Comment by prsndp** [comment] 2021-04-13 18:38
> Great!
> 
> @prsndp, feel free to create a pull request or draft with your updates whenever you feel ready, and I will make sure to check in and provide any feedback that could be useful if it was needed.
> 
> I can also provide feedback on your personal fork if you point me to a specific branch if that is what you prefer!
> 
> Let me know!

@nbcl Yeah Sure!

**Comment by surajkumar-sk** [comment] 2021-04-30 16:46
I didn't know this was the original issue and people are already assigned for it. Issue #3357 describes adding on fast-forward and rewind buttons on double click and no one was working on it , so I started the work and added a PR #3373 . I am extremely sorry assignees if you were working on it, well the PR has not been reviewed yet so it can be rejected by reviewers.

**Comment by nbcl** [comment] 2021-04-30 18:17
@surajkumar-sk you are right, #3357 contains a duplicate of the second enhancement request that is present in this issue.

Personally, as I agreed in a couple of messages before, I was supposed not to directly code the solution, but to check in and provide any feedback that could be useful if it was needed - This being the case, and as you already brought together a pull request, then I can take my efforts to provide feedback on #3373 as soon as I am able to.

Now, apart from that, and with the objective of keeping the issues in a correct manner, this issue could be re purposed to only consider the first enhancement:

> "There is a replay icon in the video element when viewed in the browser but not in mobile view so the replay icon can be added."

This way we leave the second request, "fast-forward buttons on double tap" to be specifically considered in #3357.

@prsndp @surajkumar-sk, do you agree with this new arrangement? 

Please let me know!

**Comment by surajkumar-sk** [comment] 2021-04-30 18:29
@nbcl An appreciation for you english . You are really good at writing formal messages .

As per the first issue . The changes will be pretty small, a few lines. After review, if the changes are good, I can fix the first issue too.

**Comment by nbcl** [comment] 2021-04-30 19:09
> An appreciation for you english . You are really good at writing formal messages .

I always try to take an extra minute to check if I am being clear in my responses, so I really appreciate your message! 

I have always though that when building software, specially open source, communication plays one of the most important parts in the success of a project. Of course, there is no software without code, but can a team really build something great without communicating accordingly? 

> As per the first issue . The changes will be pretty small, a few lines. After review, if the changes are good, I can fix the first issue too in the same pr. 🙂

Sounds great - Let's maybe wait a bit for @prsndp to comment before continuing with the first enhancement!

**Comment by surajkumar-sk** [comment] 2021-04-30 19:21
@nbcl this is probably a low priority issue right now for members, with the gsoc and 3.1.0 release members are pretty busy. I don't expect a review for atleast a week from now . We got a lot of time to continue this discussion .

**Comment by nbcl** [comment] 2021-04-30 19:28
Definitely, sounds good! - That being the case we can await a response and, in the meanwhile, I will try to reach out with a review on #3373 in the upcoming weekend! 😄

**Closed** 2023-11-29 09:22 UTC
Labels: type: enhancement, flag: seeking PR, component: UI, priority: P3
