### ISSUE TITLE
Severity 2 error when VTT file fails to load.

### ISSUE THREAD

**Issue by stuartflanagan** [shaka-project/shaka-player#4040] opened 2022-03-21 10:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
I have not built this just using latest NPM package

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Due to the nature of this issue I ahve not found a way to do this just yet.

**What browser and OS are you using?**
Version 99.0.4844.74 (Official Build) (x86_64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

I added a text track to a video on load via `player.addTextTrack`
There is an issue with the text file which we need to fix but I did not expect a severity 2 error to be thrown and playback to affected.

**What did you expect to happen?**
Loading of text track to fail silently and video to continue to play

**What actually happened?**

I added a text track to a video on load via `player.addTextTrack`
There is an issue with the text file which we need to fix but I did not expect a severity 2 error to be thrown and playback to affected.

**Comment by stuartflanagan** [comment] 2022-03-21 11:04
I just tested with `addTextTrackAsync` but got same result.

Error code returned is `1002`

**Comment by stuartflanagan** [comment] 2022-04-20 08:30
this is still happening. Is it something worth discussing? I feel an error should still be thrown but potentially not a severity 2 error?

**Comment by joeyparrish** [comment] 2022-04-20 21:17
The errors thrown directly by that method are all `Severity.RECOVERABLE`, except `Code.MISSING_TEXT_PLUGIN`, which is `Severity.CRITICAL`.

If an error is thrown from elsewhere, and bubbles up through this method, you could always choose to catch it and change its severity.

> There is an issue with the text file which we need to fix but I did not expect a severity 2 error to be thrown and playback to affected.

Those severity settings in Errors are just advisory.  The severity field doesn't directly stop playback.  (The only exception is in NetworkingEngine, where a CRITICAL error from a scheme plugin will stop the retry logic.)

Can you elaborate on the issue?  What's the source of the error?  How did this stop playback?  Why is it incorrect or problematic for the error to be marked CRITICAL?

**Comment by stuartflanagan** [comment] 2022-04-22 01:34
OK I will look into this more. We receive a `1002` error `Severity.CRITICAL` each time a text track is missing or cannot be loaded.

**Comment by joeyparrish** [comment] 2022-04-22 15:45
I just tried this in the demo to see what would happen:

```js
player = video.ui.getControls().getLocalPlayer()
player.addTextTrackAsync('foo.vtt', 'en', 'captions', 'text/vtt', '', '', false)
```

`foo.vtt` doesn't exist.  The call succeeds (Promise resolved).  Then I selected this side-loaded track from the UI, and then started seeing failing requests for `foo.vtt`.  The requests occur about once per second, without the player ever giving up, which seems wrong.

But I never see error 1002, and playback continues to the end of the presentation.  (In this case, BBB: the Dark Truths, about 6 minutes long.)

**Comment by stuartflanagan** [comment] 2022-04-26 10:27
Thanks for trying this @joeyparrish. We are not using the shaka UI in this instance but just listening for an error event and checking the severity. 
I will investigate a bit more locally and get back to you.

**Comment by stuartflanagan** [comment] 2022-05-02 13:51
Hi @joeyparrish. I have set up a small example of how I am seeing this 1002 error.
I am seeing an error with severity 2 thrown when the track is selected. First I am seeing the 404 from the VTT file.

We are not using the UI to select the track though, just selecting it programatically after it is added.

```
player.addEventListener('error', (e: Error) => {
  console.log({ e });
});
try {
  await player.load(manifest);

  const textTrack = await player.addTextTrackAsync(
    'http://example.com/test.vtt',
    'en',
    'captions',
    'text/vtt'
  );

  player.selectTextTrack(textTrack);
  player.setTextTrackVisibility(true);

} catch (err: any) {
  console.error({ err });
}
```

The error returned is:

<img width="621" alt="Screen Shot 2022-05-02 at 11 50 39 pm" src="https://user-images.githubusercontent.com/811015/166245167-6d4ddea8-675e-48a1-8463-afb1228441fc.png">

**Comment by alarochelle** [comment] 2024-01-15 13:06
Also reproducing this. This is a bit problematic since it's pretty challenging to **reliably** determine that this error can be safely dismissed and that playback can continue. Any news or workaround for this issue?

**Comment by avelad** [comment] 2024-01-15 14:37
You can set `streaming.ignoreTextStreamFailures = true` to avoid this issue. Can you tell me if it works? If it works I will close this issue because it is a configuration issue.

**Comment by alarochelle** [comment] 2024-01-15 14:43
Hi @avelad, thanks, was unaware this setting existed, this works.

**Closed** 2024-01-15 14:44 UTC
Labels: type: bug, status: waiting on response, priority: P2, component: WebVTT

**Comment by alarochelle** [comment] 2024-01-17 18:26
Sorry, just thought it would be right to come back to this. Setting `streaming.ignoreTextStreamFailures = true` does resolve the issue but I think an issue still exists in Shaka concerning this: when adding a track through `addTextTrackAsync`, if the track fails to load or is missing, the player just retries fetching it according to the `manifest.retryParameters` configuration. 

The player also just keeps exposing the track through `getTextTracks` (if using a captions file).

Shouldn't the player remove the track from it's internal list and not expose it?
