### ISSUE TITLE
Allow building when the path is long on Windows

### ISSUE THREAD

**Issue by Ashaaradhya** [shaka-project/shaka-player#3551] opened 2021-07-27 13:01 UTC
Hi.. I have been trying to build the shaka player on my windows machine ( Tried on 3 windows machine with different node versions) but always end up with error [Error] *** A required dependency is missing : node

Please find the screenshot attached. As we can see here node version 14 is already installed.

![image](https://user-images.githubusercontent.com/66466711/127157847-dd064d3a-9765-4e1a-a192-394f10459517.png)

**Comment by TheModMaker** [comment] 2021-07-27 16:17
Try running `python` by itself and entering the following:

```python
import subprocess
subprocess.call(['node', '-v'])
```

**Comment by Ashaaradhya** [comment] 2021-07-28 09:24
Hi.. This is the output
![Capture](https://user-images.githubusercontent.com/66466711/127298235-a804ae63-6765-477a-8ec6-01a6586e2bd0.PNG)

**Comment by Ashaaradhya** [comment] 2021-07-28 15:22
I also tried to build/all.py there directly in the python terminal but it didn't work..

**Comment by TheModMaker** [comment] 2021-07-28 17:03
Try running `set PRINT_ARGUMENTS=1` before running `build/all.py`.  I think [this check](https://github.com/google/shaka-player/blob/38cfc230483133862cc41153931f4dc170eb4a75/build/shakaBuildHelpers.py#L164) is giving false positives when node is running a sub-command.

**Comment by Ashaaradhya** [comment] 2021-07-29 16:24
I tried it with above suggestion but still no luck.

![Capture1](https://user-images.githubusercontent.com/66466711/127529094-c57211ce-6d01-4a9d-ac8f-d26943134aaf.PNG)

This is the output 

![Capture2](https://user-images.githubusercontent.com/66466711/127529177-f73fb67d-5ce8-4b6d-beba-67bc45023af1.PNG)

**Comment by TheModMaker** [comment] 2021-07-29 16:49
It wasn't to fix it, I wanted to see the first part of the last command to see what failed.  Could you post the whole last command?  Also, it would be easier if you posted the text instead of a screenshot.

**Comment by TheModMaker** [comment] 2021-07-29 22:45
Actually, I think this is a duplicate of #3369.  Try moving the folder to another location so the full paths are shorter.  It's possible we are hitting path limits.

**Comment by TheModMaker** [comment] 2021-07-29 23:36
It looks like this may be a limit on the command line size.  Since we pass a bunch of absolute paths in, the command line is huge.  We may be able to reduce the size of this a few ways:

- For eslint, we can split up multiple calls or just lint recursively all files instead of explicitly listing each.
- For the compiler, there is a `--json_streams` option to accept input files from standard in instead.
- We may be able to use relative paths for some programs.

I'll mark this a bug, but put it on the backlog since there is an easy workaround.  For the moment, you can just move it to another folder with a shorter path (e.g. `C:\shaka-player`).

**Comment by Ashaaradhya** [comment] 2021-07-30 09:02
Sorry, posting the full error here below. I added it to shorter path like you suggested and good news is no more node error but now getting a different error:

```
**npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v14.17.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.
npm WARN npm You can find the latest version at https://nodejs.org/
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
Error: Cannot find module 'eslint-plugin-shaka-rules'
Require stack:
- C:\shaka-player\node_modules\eslint\lib\config\config-file.js
- C:\shaka-player\node_modules\eslint\lib\config.js
- C:\shaka-player\node_modules\eslint\lib\cli-engine.js
- C:\shaka-player\node_modules\eslint\lib\cli.js
- C:\shaka-player\node_modules\eslint\bin\eslint.js
Referenced from: C:\shaka-player\.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at resolve (C:\shaka-player\node_modules\eslint\lib\config\config-file.js:498:31)
    at load (C:\shaka-player\node_modules\eslint\lib\config\config-file.js:579:26)
    at C:\shaka-player\node_modules\eslint\lib\config\config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\shaka-player\node_modules\eslint\lib\config\config-file.js:431:26)
    at loadFromDisk (C:\shaka-player\node_modules\eslint\lib\config\config-file.js:551:22)
    at Object.load (C:\shaka-player\node_modules\eslint\lib\config\config-file.js:587:20)
    at Config.loadSpecificConfig (C:\shaka-player\node_modules\eslint\lib\config.js:148:46)

C:\shaka-player>**
```

**Comment by TheModMaker** [comment] 2021-07-30 16:30
Since you moved the folder, it broke a symlink.  Delete `node_modules/eslint-plugin-shaka-rules` and run `npm install`.

**Comment by Ashaaradhya** [comment] 2021-08-02 13:40
I tried to build fresh copy of Shaka Player . Please find the error below:

npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...

C:\shaka-player\demo\main.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)

[INFO] Linting CSS...
Error: No files matching the pattern "C:\shaka-player\demo\cast_receiver\receiver_app.css, C:\shaka-player\demo\demo.less, C:\shaka-player\ui\controls.less, C:\shaka-player\ui\less\ad_controls.less, C:\shaka-player\ui\less\buttons.less, C:\shaka-player\ui\less\containers.less, C:\shaka-player\ui\less\general.less, C:\shaka-player\ui\less\other_elements.less, C:\shaka-player\ui\less\overflow_menu.less, C:\shaka-player\ui\less\range_elements.less, C:\shaka-player\ui\less\spinner.less" were found.
    at C:\shaka-player\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

C:\shaka-player>

**Comment by Ashaaradhya** [comment] 2021-08-09 14:30
To keep the ticket updated , I above issue was fixed with the help of https://github.com/google/shaka-player/issues/2985 .. I was able to build and run the shaka-player

**Comment by Ashaaradhya** [comment] 2021-08-09 14:34
To keep the ticket updated , I above issue was fixed with the help of https://github.com/google/shaka-player/issues/2985 .. I was able to build and run the shaka-player

**Closed** 2023-01-26 22:25 UTC
Labels: type: bug, priority: P2
