### ISSUE TITLE
Playback is broken after seeking to video end

### ISSUE THREAD

**Issue by NemiS94** [shaka-project/shaka-player#4393] opened 2022-08-08 10:09 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The issue is similar to #1967 and #1014.

**What version of Shaka Player are you using?**
4.1.2 & 3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 102.0.5005.63 and Firefox 100.0.2. Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Manifest: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
I have been able to reproduce the issue with all manifests tested.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default config, but I am able to also reproduce it programmatically if `streaming.durationBackoff` is set to `0`.

**What did you do?**
Seek to the duration of the video. Note: You need to drag the slider past the end.
Seek to somewhere else.
Start playback.

**What did you expect to happen?**
Playback is working.

**What actually happened?**
Playback is not working. In Chrome when clicking play the play head will jump to the end. In Firefox you cannot seek. The play head jumps to the start.

**Comment by joeyparrish** [comment] 2022-08-10 17:43
Confirmed.  Thank you for the report!

**Comment by joeyparrish** [comment] 2022-08-10 17:46
This is reproducible with both our UI and the native browser controls, so it's not a Shaka UI bug.

It does not appear to happen when you seek via the video element API.  I tried both video.currentTime = 60 or video.currentTime = 90 on a 60-second clip.

**Comment by joeyparrish** [comment] 2022-08-12 17:55
I still have not determined if this is a browser bug or a Shaka bug.  I will need more time to dig into this.

Since we don't have a fix, this issue will not be fixed by this week's releases.

**Comment by joeyparrish** [comment] 2022-08-18 21:10
This doesn't happen on plain HTML5 video, and it doesn't happen with single mp4 videos in Shaka Player.  So the key must be something to do with how we talk to MediaSource.

**Comment by joeyparrish** [comment] 2022-08-18 21:19
Commenting out the inner-most arrow function in `MediaSourceEngine.endOfStream()` makes the problem go away.

**Comment by joeyparrish** [comment] 2022-08-18 21:22
Scratch that, that was wrong.  Something hadn't reloaded properly in my browser.

**Comment by joeyparrish** [comment] 2022-08-18 21:46
Increasing the settling time in the UI (`ui/seek_bar.js`, inside `onChange()`) seems to avoid the problem, but it can still be triggered in the native browser seek UI.

I can also reliably trigger the issue in Chrome with code like this, which seeks X number of times, 125 ms apart:

```js
rapidSeek = (seeks) => {
  video.currentTime += 10;
  if (seeks >= 1) {
    console.log(`${seeks} left`);
    setTimeout(() => rapidSeek(seeks - 1), 125);
  } else {
    console.log('done');
  }
};

// seek 5 times past the end:
rapidSeek(5 + (video.duration - video.currentTime) / 10);
```

This only seems to occur for MSE playbacks, but not for plain MP4s.

I can't reproduce the same behavior on either dash.js nor hls.js, so it seems much more likely to be a Shaka bug than a browser bug.

**Comment by joeyparrish** [comment] 2022-08-18 23:11
It seems to be important to trigger this state that the seeking happen rapidly enough that the buffer is completely cleared by the time the "ended" state is reached.

This seems to have a consequence at the HTML video element level that we may not be able to do anything about: `video.ended` remains `true` even after seeking backward.  If the buffer isn't empty, seeking backward resets `video.ended` to `false`.

Part of the problem seems to be that StreamingEngine's state is broken by this, and this part we can fix.  Normally, seeking kick-starts StreamingEngine through the forceClearBuffer_ method.  But if there is nothing buffered, this doesn't happen, and therefore StreamingEngine remains idle after seeking backward.

**Comment by avelad** [comment] 2023-11-29 14:36
The issue is still reproduced in the main branch and in 4.6.2

**Comment by avelad** [comment] 2024-04-08 14:34
The issue is still reproduced in the main branch and in 4.7.11

**Closed** 2024-07-09 12:32 UTC
Labels: type: bug, priority: P1
