### ISSUE TITLE
Error when switching audio language on safari

### ISSUE THREAD

**Issue by zubcoco** [shaka-project/shaka-player#7243] opened 2024-09-02 08:22 UTC
**What version of Shaka Player are you using?**
The latest shaka player version : v4.10.13

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari on MacOS (not reproduced on Chrome)

**What are the manifest and license server URIs?**
I'll send you the manifest URI by mail.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
I reproduce the error with the demo app.

**What did you do?**
1. Start the stream (ok)
2. Change the audio language

**What did you expect to happen?**
Video continue with the other audio language.

**What actually happened?**
The video stopped and there is no way to continue.

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment] 2024-09-02 08:39
Duplicate of https://github.com/shaka-project/shaka-player/issues/3243

**Closed by avelad** 2024-09-02 08:39 UTC
Labels: type: bug

**Comment by zubcoco** [comment] 2024-09-02 08:44
It's not exactly a duplicate of #3243 
I can reproduce with a HLS stream too. I'll send you an other manifest URI.

**Comment by avelad** [comment] 2024-09-02 08:48
See: https://github.com/WebKit/WebKit/pull/32938

**Comment by avelad** [comment] 2024-09-02 08:48
It can actually happen with DASH, HLS, MS, anyone using MSE
