### ISSUE TITLE
HLS AES-128 streams fail to play in MS Edge and when casting

### ISSUE THREAD

**Issue by multiplexer2** [shaka-project/shaka-player#4441] opened 2022-08-25 12:55 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2 nightly

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Have not tried

**Are you using the demo app or your own custom app?**
The Shaka demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Microsoft Edge
Chromecast from Google Chrome on Windows and Ubuntu

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
I've been testing with "Art of Motion (HLS, TS, AES-128)" on the Shaka demo page

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
The config is as configured on the demo page

**What did you do?**
Test 1: Navigate to the stream in MS Edge and start playback
Test 2: Navigate to the stream in Chrome and start casting

**What did you expect to happen?**
The video to play without issues

**What actually happened?**
In both cases, the video starts playing but after a couple of seconds playback stops with the following error:

```
Failed to set the 'timestampOffset' property on 'SourceBuffer': The timestamp offset may not be set while the SourceBuffer's append state is 'PARSING_MEDIA_SEGMENT'.
    at shaka.media.MediaSourceEngine.appendBuffer (https://nightly-dot-shaka-player-demo.appspot.com/lib/media/media_source_engine.js:630:38)
    at async shaka.media.StreamingEngine.append_ (https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1646:5)
    at async shaka.media.StreamingEngine.fetchAndAppend_ (https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1301:9)

```

**Comment by avelad** [comment] 2022-08-25 18:05
![image](https://user-images.githubusercontent.com/8983024/186737408-adc38a90-23b2-468b-bb31-c4c3f5e6c922.png)
https://shaka-player-demo.appspot.com/demo/#audiolang=es;textlang=es;uilang=es;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8;panel=ALL_CONTENT;build=uncompiled

I was able to reproduce it in Edge. There must be some bug in the AES-128 implementation. @theodab you have implemented it, can you take a look at it?

**Comment by gaminglnk** [comment] 2022-08-29 00:25
MS Edge has native transmuxing of mpeg-2-ts chunks of hls streams.
So to counter it.
First of all, make sure you have this included
```html

<script src="https://cdn.jsdelivr.net/npm/mux.js@6.2.0/dist/mux.js"></script>

```
in the head of your app or project.

...
---
And also make sure you have 
```javascript

player.configure("streaming.forceTransmuxTS", true);

``` 
inside your init function.
I.e. 
```javascript

async function init() { player.configure("streaming.forceTransmuxTS", true); }

```
Make sure to report this error to MS so you don't have to include this all in future.

**Comment by gaminglnk** [comment] 2022-08-29 00:29
This was how I fixed it as I also use MS edge.
https://www.speedynet.eu.org/shaka?link=<YOUR_MANIFEST_URL>

This is a quick way of testing HLS streams on Edge with Shaka player.

**Comment by joeyparrish** [comment] 2022-08-29 18:43
I would guess that errors relating to `timestampOffset` may not have anything to do with encryption.

I'm confused by some of the posts.  The OP says the issue starts when casting, but others are suggesting fixes that relate to Edge playback rather than Chromecast playback.

Does the issue occur only when casting?  Or does the issue occur when playing directly in Edge?

Does the issue occur when casting from other browsers, such as Chrome?

**Comment by multiplexer2** [comment] 2022-08-30 07:35
> Does the issue occur only when casting? Or does the issue occur when playing directly in Edge?

Both. The problem occurs with direct playback from Edge - and also when initiating a cast session from any browser, including Edge. When I add the forceTransmuxTS workaround to the player setup in Edge, direct playback works fine. But when attempting to cast the player throws that same error message:

---
CastSender: onSessionInitiated
CastSender: connection status true
Starting unload...
CastSender: connection status true
Error code 11 object Error: Failed to set the 'timestampOffset' property on 'SourceBuffer': The timestamp offset may not be set while the SourceBuffer's append state is 'PARSING_MEDIA_SEGMENT'.
---

> Does the issue occur when casting from other browsers, such as Chrome?

Yes.

**Comment by theodab** [comment] 2022-10-11 11:55
I tried this out in MS Edge and didn't see the error. I un-applied #4543 (which looks like it is describing the same issue) and tried again and did see the error, so I think this is fixed now.
If you see that error again, you can re-open this.

**Closed by theodab** 2022-10-11 11:55 UTC
Labels: type: bug, component: HLS, priority: P1
