### ISSUE TITLE
HLS playback not working in iOS 17

### ISSUE THREAD

**Issue by athulms1988** [shaka-project/shaka-player#5338] opened 2023-06-21 02:24 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari, iOS 17

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-IN;textlang=en-IN;uilang=en-IN;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=ALL_CONTENT;panelData=source:SHAKA,drm:CLEAR,HLS,MP4,VOD;build=uncompiled

**Comment by avelad** [comment] 2023-06-21 20:41
Duplicate of https://github.com/shaka-project/shaka-player/issues/5272

**Closed by avelad** 2023-06-21 20:41 UTC
Labels: type: bug
