### ISSUE TITLE
Shaka Error MEDIA.VIDEO_ERROR (3,,PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#2830] opened 2020-08-31 08:43 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4. Hosted Demo

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
Using Demo App

**What browser and OS are you using?**
Chrome/MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://streaming-cdn.learnyst.com/v3/schools/11075/courses/77372/ndrm/paid/710475/audio_video/10__EXPLANATION_PART_FOR_AREA_OF_FILLING__part-1__lyst6996_lyst3637_uenc/stream.mpd

**What did you do?**
Play the above manifest in hosted demo

**What did you expect to happen?**
Play should be success

**What actually happened?**
At 40th second during the play, the play fails with the below error:
Shaka Error MEDIA.VIDEO_ERROR (3,,PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: {timestamp=40658140 duration=23219 size=861 is_key_frame=1 encrypted=0})

**Comment by TheModMaker** [comment] 2020-08-31 17:40
PIPELINE_ERROR_DECODE is a decoder error from the browser.  This is usually caused by bad content that the browser can't play.  There is usually nothing we can do about it since there is some problem with the content.  I'll look a bit at the content to see if there is anything I can see wrong with it.

**Comment by TheModMaker** [comment] 2020-08-31 20:22
Oddly, the content plays fine in [Shaka Player Embedded](https://github.com/google/shaka-player-embedded).  So the iOS hardware decoders can play the content.  But Shaka Player Embedded also uses Shaka Player to play, so this seems like a platform bug.  Unfortunately I don't have any insights on what would be causing it or how to workaround it.  You should file a [Chrome bug](https://bugs.chromium.org/p/chromium/issues/entry)

**Comment by sridhard** [comment] 2020-09-01 04:38
@TheModMaker Do you find any issue with the content. We can modify the parameters like bitrate/fps etc if required

**Comment by shivaksk1** [comment] 2022-03-16 07:06
@sridhard the url is not accessible:
- https://streaming-cdn.learnyst.com/v3/schools/11075/courses/77372/ndrm/paid/710475/audio_video/10__EXPLANATION_PART_FOR_AREA_OF_FILLING__part-1__lyst6996_lyst3637_uenc/stream.mpd
Is it possible to make this available, or do you know any public streams where this issue is reproducible?

**Comment by joeyparrish** [comment] 2022-05-24 17:44
This appears to be a content issue.  Closing.

**Closed by joeyparrish** 2022-05-24 17:44 UTC
Labels: status: bad content
