### ISSUE TITLE
DRM 6008 - Failed to execute 'update' on 'MediaKeySession': Rejected with system code (22)

### ISSUE THREAD

**Issue by samueleastdev** [shaka-project/shaka-player#5410] opened 2023-07-12 14:58 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

**Please ask your question**

I'm currently seeking information regarding an error that has been occurring on Chrome version 114.0.0.0 for Windows 10, and I was wondering if you could provide some insight.

Specifically, we have been encountering a DRM 6008 error. From my understanding, this error message indicates that the license response from the Content Decryption Module (CDM) was rejected. It suggests that the server's response may be invalid or malformed for this particular CDM. 

code: https://github.com/shaka-project/shaka-player/blob/6d75d89fbb13a32de135a6c1ab6a7a3e55fcb3f4/lib/util/error.js#L841

Now, the aspect I'm particularly interested in is this error that come along with it. 
```
"Failed to execute 'update' on 'MediaKeySession': Rejected with system code (22)" error. 
```

I'm trying to gain more insights into this specific error and understand what the system code (22) signifies. Additionally, if there are any relevant documentation or resources available that could assist in debugging why we are experiencing this error, it would be greatly appreciated. I have already explored the possibility of this issue being related to Chrome settings, such as hardware acceleration, but I haven't had any success in resolving it.

It's worth noting that this error occurs sporadically, only happening occasionally. Could it be related to the Content Decryption Module (CDM) on certain users' machines?

Any help would be great,

Thanks

**Comment by avelad** [comment] 2023-08-22 07:31
Duplicate of https://github.com/shaka-project/shaka-player/issues/2702

**Closed by avelad** 2023-08-22 07:31 UTC
Labels: type: question

**Comment by samueleastdev** [comment] 2023-08-23 09:04
Just wanted to add some context to this to help anyone else.

This seemed to be an issue on Googles end from our analytics the issue is no longer present on Windows 10 / Chrome 115.0.0.0 something has changed from Windows 10 / Chrome 114.0.0.0 which we are investigating to try and get some more information on what might have changed.
