### ISSUE TITLE
Cast: Fix `TypeError` within MediaCapabilities#decodingInfo() polyfill implementation

### ISSUE THREAD

**Issue by JulianDomingo** [shaka-project/shaka-player#4790] opened 2022-12-05 19:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Latest (`v4.3.0`).

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Yes.

**Are you using the demo app or your own custom app?**
Custom app (Apple Music).

**If custom app, can you reproduce the issue using our demo app?**
No, since it's specific to Cast devices.

**What browser and OS are you using?**
Chrome, Cast OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Google Nest Hub / FW Version: `1.56.271947`

**What are the manifest and license server URIs?**
N/A (Accessible by selecting content in the Cast app).

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Confidential, since these are determined by the partner's receiver application. They are basic DRM configurations for Widevine.

**What did you do?**
Cast any content from Apple Music onto a Cast device and observe the loading process.

**What did you expect to happen?**
Content to play successfully.

**What actually happened?**
Content failed to load due to unsupported DRM configurations. In reality, the DRM configuration only failed due to a `TypeError` when trying to access `MediaDecodingConfig['audio']`, specifically: https://github.com/shaka-project/shaka-player/blob/795342dd04ace6fbfaae389d128b341b0ed75118/lib/polyfill/media_capabilities.js#L190-L192

The weird thing is, when the error is propagated to Chrome's console logs, it's clear the needed fields are defined. I don't know if this is some weird race condition behavior. The offending PR is this one: https://github.com/shaka-project/shaka-player/pull/4708/files#diff-c4c9f9f8b2aeadde8d04789ebe84f215109bf5285f903614bb69e02e9d25fb5f.

Below shows the stack trace of the issue:
![image](https://user-images.githubusercontent.com/14350728/205581679-d77c27e1-327a-42ec-9856-0faa6007531b.png)

This issue disappears when I simply add existence checks for the preceding fields of `contentType` and fallback to an empty string if not defined, so the fix will just be that.

**Comment by theodab** [comment] 2022-12-07 22:55
Is this complete now?

**Comment by joeyparrish** [comment] 2022-12-07 23:07
I have concerns about the fix potentially masking a deeper issue without getting to the root cause.  Let's leave this open for now.  I'll work with Julian on how to repro so I can investigate.

**Comment by avelad** [comment] 2023-12-04 10:12
A year has passed, and it seems that the problem has not recurred. So I'm going to close the issue.

**Closed by avelad** 2023-12-04 10:12 UTC
Labels: type: bug, priority: P1, platform: Cast
