### ISSUE TITLE
Shaka player :  HTTP_ERROR or error code 1002 in Edge Browsers 

### ISSUE THREAD

**Issue by praveenRI007** [shaka-project/shaka-player#5232] opened 2023-05-15 18:08 UTC
In Edge browser getting HTTP_ERROR or error code 1002 error when running media files (audio or video). But when Edge browser is updated to latest it works.but we had earlier tested with lower versions of Edge browser where it worked fine , but now those previous versions require latest upgrade in order to run. Can I get the reason as to why this inconsistency happens ?

**Comment by avelad** [comment] 2023-05-16 07:18
Duplicate of https://github.com/shaka-project/shaka-player/issues/5234

**Closed by avelad** 2023-05-16 07:18 UTC

**Comment by praveenRI007** [comment] 2023-05-16 12:25
Hi @avelad could you please brief on this error , currently we are facing issue with users suddenly due to this , we want to confirm whether error is due to code implementation or the browser.
