### ISSUE TITLE
3018 Error for ima ads as well as vod content

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5363] opened 2023-06-27 13:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Tes

**Are you using the demo app or your own custom app?**
Custom App. 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOs and Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Shared in mail

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Shared in mail

**What did you do?**

Just play the content with corresponding manifest url or dai asset key in case of ads

**What did you expect to happen?**
Video Playing smoothly

**What actually happened?**
Getting 3018 error showing transmuxing failed

**Comment by WINOFFRG** [comment] 2023-06-27 21:34
Duplicate of https://github.com/shaka-project/shaka-player/issues/4392

**Comment by neerajgulati-airtel** [comment] 2023-06-30 14:53
Hi can you suggest a solution for this. It's a kind of blocker for me to play live tv with ads

**Comment by neerajgulati-airtel** [comment] 2023-07-18 14:04
A gentle reminder

**Comment by avelad** [comment] 2023-10-04 15:03
@neerajgulati-airtel can you test it with the main branch? Thanks!

**Comment by neerajgulati-airtel** [comment] 2023-10-04 16:10
Getting same error on current shaka demo as well as on nightly

<img width="1464" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/9e66ab46-4714-443c-b36e-812fde3809a6">

**Comment by avelad** [comment] 2023-11-02 16:57
I've fixed some transmuxer issues on the main branch, can you check if it's still happening? thank you!

**Closed** 2023-11-09 17:08 UTC
Labels: type: bug, status: waiting on response, component: HLS, component: ads
