### ISSUE TITLE
[ViacomCBS] [XBox] - Shaka Player DRM Key Per Track Playback Errors

### ISSUE THREAD

**Issue by jhemby-cbsi** [shaka-project/shaka-player#3627] opened 2021-09-10 20:54 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, there are no duplicate open issues

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes, latest version in Prod

**Can you reproduce the issue with the latest code from `master`?**
Not tested

**Are you using the demo app or your own custom app?**
Vanilla Shaka Player on Device and Custom App

**If custom app, can you reproduce the issue using our demo app?**
Vanilla Shaka Player on Device

**What browser and OS are you using?**
XBox One

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Xbox One

**What are the manifest and license server URIs?**
SENT via EMAIL

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
SENT via EMAIL

**What did you do?**
The content is packaged with Key Per Track labels and certain bitrates have different keys:
SD - 1 key
HD - 1 key
UHD - 1 key
audio(s) - 1 key

when playing this type of packaged content on a XBox One device, no playback and an error appears
DASH_INVALID_XML / 4001:
The DASH Manifest contained invalid XML markup.
error.data[0] is the URI associated with the XML.

**What did you expect to happen?**
The device to play the content. It should be able to support all renditions available in the manifest and be able to decrypt all the keys for each one for playback.

**What actually happened?**
No Video Playback, An Error is Returned

**Comment by dsparacio** [comment] 2021-09-10 21:04
@ jhemby-cbsi. Thanks for filing this on behalf of our teams. 
@joeyparrish and team,  We also engaged with Chromecast on this issue. They did some research and found possible Shaka related issues for that device. You may hear something internally around that.   

Our content is work really well on all other HTML in Shaka 3.2 including on Samsung and other STV platforms. 

At first I thought it was related to the same issue we saw on Xbox, with unencrypted pre-rolls into encrypted periods.. But I think this may be different.   

We are seeing the above Dash error in logs but that seems like like a schema issue, I doubt it is related to key per track.  
We are not seeing much else in logs but we can collect them for you if you have no access to Xbox?

**Comment by agajassi** [comment] 2021-09-15 19:36
@dsparacio @joeyparrish 

This particular error is related to this issue I filed.
https://github.com/google/shaka-player/issues/3636

However regardless of the above ticket, key per track DRM on Xbobx still doesn't appear to work. It was also tested on earlier version of Shaka player that doesn't exhibit the 4001 error. 

@dsparacio just like you predicted, yes 4001 error is not related to key per track. I just wanted to make a clear distinction.

**Comment by joeyparrish** [comment] 2021-09-15 20:08
I'm going to close this as a duplicate of #3636 and continue the investigation there using the public DASH content in that issue.  Thanks!

**Comment by joeyparrish** [comment] 2021-09-15 20:50
I found the root cause of #3636 (bad content), and it doesn't explain this issue at all.  So I'm reopening this one and removing the "duplicate" label.

**Comment by joeyparrish** [comment] 2021-09-15 22:50
I am unable to reproduce this error on my Xbox One.  I tried the following:

1. Fetching the manifest and parsing it using DOMParser
2. Fetching the manifest and parsing it using our XmlUtils abstraction
3. Feeding the manifest to the uncompiled DASH parser
4. Feeding the manifest to the compiled DASH parser

All of these produced valid results, and no errors.

My device reports its User-Agent string as: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041`

Here's my test code:

```js
describe('Error 4001', () => {
  it('ad-hoc test for issues 3636 and 3627', async () => {
    // This is the URI from #3636; the URI from #3627 is private.
    const uri =
        'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd';
    const data = await shaka.test.Util.fetch(uri);
    const mimeType = 'text/xml';

    // Parse with DOMParser directly
    const dataString = shaka.util.StringUtils.fromUTF8(data);
    const parser = new DOMParser();
    const doc1 = parser.parseFromString(dataString, mimeType);
    console.log(doc1);
    if (doc1 == null) {
      fail('doc1 is null');
    }

    // Parse with our XmlUtils abstraction
    const doc2 = shaka.util.XmlUtils.parseXml(data, 'MPD');
    console.log(doc2);
    if (doc2 == null) {
      fail('doc2 is null');
    }

    const manifestConfig =
        shaka.util.PlayerConfiguration.createDefault().manifest;

    // Parse with uncompiled DASH parser
    const playerInterface1 = {
      networkingEngine: new shaka.net.NetworkingEngine(),
      filter: (manifest) => {},
      makeTextStreamsForClosedCaptions: (manifest) => {},
      onTimelineRegionAdded: (region) => {},
      onEvent: (event) => {},
      onError: (error) => fail(error),
      isLowLatencyMode: () => false,
      isAutoLowLatencyMode: () => false,
      enableLowLatencyMode: () => {},
    };
    const dashParser1 = new shaka.dash.DashParser();
    dashParser1.configure(manifestConfig);
    // Throws on error, failing the test automatically
    const manifest1 = await dashParser1.start(uri, playerInterface1);
    console.log(manifest1);

    const compiledShaka =
        await shaka.test.Loader.loadShaka(/* uncompiled= */ false);

    // Parse with compiled DASH parser
    const playerInterface2 = {
      networkingEngine: new compiledShaka.net.NetworkingEngine(),
      filter: (manifest) => {},
      makeTextStreamsForClosedCaptions: (manifest) => {},
      onTimelineRegionAdded: (region) => {},
      onEvent: (event) => {},
      onError: (error) => fail(error),
      isLowLatencyMode: () => false,
      isAutoLowLatencyMode: () => false,
      enableLowLatencyMode: () => {},
    };
    const dashParser2 = new compiledShaka.dash.DashParser();
    dashParser2.configure(manifestConfig);
    // Throws on error, failing the test automatically
    const manifest2 = await dashParser2.start(uri, playerInterface2);
    console.log(manifest2);
  });
});
```

**Comment by jhemby-cbsi** [comment] 2021-09-23 23:20
Hello @joeyparrish  

looks like for this ticket, you did not test the correct stream URL with Key Per Track enabled. 

I emailed the URL and LA URL and config info to the shaka-player-issues email address. I will re-send today. 

This is the URL here below. You can get the LA URL and player info from the email. Let me know if you have issues receiving the info: 

Playback URL:  
https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2021/03/09/1871242307665/611707_cenc_precon_dash/stream.mpd

thanks,
Jermaine

**Comment by agajassi** [comment] 2021-11-09 00:57
### LATEST UPDATE

Revisited this use case and retested with Shaka Player 3.2.1. It still doesn't play. Seeing following errors:

**Error Code: 6005 - FAILED_TO_CREATE_SESSION
Not Supported Error. The CDM refused to create a session for some unknown reason.**


**Error Code: 3016 VIDEO ERROR
The video element reported an error**

**Comment by avelad** [comment] 2023-11-06 15:34
@littlespex Can you check if it's still happening? Thanks!

**Comment by dsparacio** [comment] 2024-01-02 17:38
Retested and is still an issue. Tested from Master.

**Comment by avelad** [comment] 2024-04-26 11:10
@dsparacio Do you plan to submit a PR to fix this? Thanks!

**Closed** 2024-05-07 11:08 UTC
Labels: type: bug, priority: P1, platform: Xbox
