### ISSUE TITLE
Rejected with system code (30)

### ISSUE THREAD

**Issue by pemasat** [shaka-project/shaka-player#2702] opened 2020-06-30 11:41 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.1

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom app

**If custom app, can you reproduce the issue using our demo app?** No

**What browser and OS are you using?** Kubuntu 20.04, Google Chrome 84.0.4147.68

**What are the manifest and license server URIs?** If you need, I can send it.

**What did you do?**
Played live stream, and after a few minute it gave me sometimes error from video element
`"Failed to execute 'update' on 'MediaKeySession': Rejected with system code (30)"`
![Screenshot_20200629_155357](https://user-images.githubusercontent.com/438504/86121688-b921f700-bad6-11ea-9579-c85c9610aabe.png)
But widewine proxy gave me all times good response. Can you share what error code "30" means?

**What did you expect to happen?** No error

**What actually happened?** It gave me error

**Comment by TheModMaker** [comment] 2020-06-30 16:29
This is an internal error from the browser and Widevine.  This appears to be a problem with the new license renewal.  This is probably a problem with your license proxy or server.  You should discuss this with your license provider or with Widevine.

**Comment by jakubvojacek** [comment] 2020-06-30 17:22
Hello

I am responsible for the widevine proxy - we're using license wrapping according to your manual https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html with url base64encoding since 2 years ago without an issue on tens of thousands end devices without ever seeing such error. The proxy implementation is rather straightforward, there is zero manipulation pretty much, we receive licence request, we forward it to WV, we get licence response, we forward it to the client (along with other business logic - but that does not manipulate the license content in any way). According to logs, there were no issues with the license retrieving and also the network tab in the browsers shows only successfull heartbeats prior to the error.

We only started to see this issues randomly on web players with shaka player since about two weeks ago. It happens at random times during live playback only, we've never seen it on the VOD. We're using one-minute heartbeats powered by widevine (renew delay seconds 60, license duration 130 and 10 seconds retries). 

We were hoping that you could enlighten us what the error code `Rejected with system code (30)` might mean, we could not find the list of codes anywhere and based on the previous issues reported in this repo, you were able to reach out to widevine team for error code description. 

Thank you
Jakub

**Comment by joeyparrish** [comment] 2020-08-18 00:57
Hi Jakub,

As far as I can tell from the internal docs that are available to me at Widevine, that error code indicates that something is wrong at the policy level.  It's very non-specific, unfortunately.

I will ask someone from the Chrome CDM team to reply here if they can and suggest some things you can do to debug this issue.  Unfortunately, as far as we know, we have no control over this situation at the level of Shaka Player.

**Comment by hmchen-github** [comment] 2020-08-18 01:20
Hi Petr and Jakub,

Can you send the manifest and license server URL so that I can reproduce and debug on the http://shaka-player-demo.appspot.com ?

**Comment by joeyparrish** [comment] 2020-08-18 01:43
If they can't be posted publicly, you can email them to shaka-player-issues@google.com and they will only be shared with the Shaka Player and Widevine CDM teams for debugging purposes.

**Comment by joeyparrish** [comment] 2022-05-24 17:43
Nothing more to do here as far as I can tell, as this was a license policy issue.  Closing.

**Closed by joeyparrish** 2022-05-24 17:43 UTC
Labels: type: external
