### ISSUE TITLE
Support dual subtitles

### ISSUE THREAD

**Issue by vwkd** [shaka-project/shaka-player#5462] opened 2023-08-04 23:12 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**Is your feature request related to a problem? Please describe.**

Support dual subtitles.

This is useful for language learning to show subtitles for both the source and target language at the same time.

**Describe the solution you'd like**

Show one subtitle at the bottom and a second one at the top.

**Describe alternatives you've considered**

**Additional context**

https://github.com/TeamPiped/Piped/issues/2768

**Comment by avelad** [comment] 2023-08-16 14:23
@joeyparrish can you review it? Thanks!

**Comment by avelad** [comment] 2023-08-18 13:35
Duplicate of https://github.com/shaka-project/shaka-player/issues/3436

**Closed by avelad** 2023-08-18 13:35 UTC
Labels: type: enhancement
