### ISSUE TITLE
Error code for extra newlines in VTT

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#3158] opened 2021-02-12 21:55 UTC
In https://github.com/google/shaka-player/issues/3122, the content had extra newlines in VTT that were maybe confusing our parser and causing subs not to display.  We should consider an explicit check or error code for that.

**Comment by MayankVir** [comment] 2021-03-16 06:47
Hi @joeyparrish , Can I start working on this issue?

**Comment by michellezhuogg** [comment] 2021-03-16 20:57
Hi @MayankVir, sure!

**Comment by MayankVir** [comment] 2021-03-17 11:30
Thanks @michellezhuogg, Can you guide me to reproduce the bug. I tried in demo app but could not reproduce!!

**Comment by MayankVir** [comment] 2021-03-17 11:46
Also just now I tried playing live stream in demo app and it threw an error of BAD_HTTPS_STATUS and the video play and pause again and again. Should I open a separate issue for this? Below is the attached screenshot
![Capture](https://user-images.githubusercontent.com/41983025/111462430-71b2c800-8744-11eb-9739-968d23848f5f.PNG)

**Comment by michellezhuogg** [comment] 2021-03-17 16:15
1. No worries if you cannot reproduce, since it's not reproducible with our demo contents. We'll take care of this bug.
2. The error message of the live stream in the demo app is not relevant. Don't worry about it. Thank you!

**Comment by MayankVir** [comment] 2021-03-17 16:30
Okay, Can you guide me through the repository where the parser code for vtt file is written?

**Comment by michellezhuogg** [comment] 2021-03-18 20:23
The cue is parsed [here](https://github.com/google/shaka-player/blob/master/lib/text/vtt_text_parser.js#L301), and here are the [unit tests](https://github.com/google/shaka-player/blob/master/test/text/vtt_text_parser_unit.js#L62).

Similar to "handles a blank line at the end of the file", you'll need a test case with a blank line between the time and the caption:
```
'WEBVTT\n\n' +
'00:00:20.000 --> 00:00:40.000\n\n' +
'Test\n',
```
And expect it to throw a "shaka.util.Error.Code.INVALID_TEXT_CUE" exception, similar to [this case](https://github.com/google/shaka-player/blob/master/test/text/vtt_text_parser_unit.js#L174).

**Comment by avelad** [comment] 2024-04-16 06:28
Is anyone interested in seeing this implemented? Otherwise the issue will be closed in 7 days.

**Closed** 2024-04-23 06:38 UTC
Labels: type: enhancement, status: waiting on response, component: captions/subtitles, priority: P3, component: WebVTT
