### ISSUE TITLE
Embedded / Close Captions are not coming for HLS livestream

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#5906] opened 2023-11-20 06:30 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. No duplicate issues

**If the problem is related to FairPlay, have you read the tutorial?**

No, It's not related to FairPlay.

**What version of Shaka Player are you using?**

v4.5.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
OS:
Edition Windows 11 Enterprise
Version 22H2
Browser: Chrome
Version 118.0.5993.70 (Official Build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**CBS NEWS URL**
https://www.cbsnews.com/streaming/

**CBS NEWS Manifest :**
https://dai.google.com/linear/hls/pb/event/Sid4xiTQTkCT1SLu6rjUSQ/stream/689546a1-c104-43a5-840c-2a431c211dc9:SIN/master.m3u8

**Shaka Demo Player URL:**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;useSafariBehaviorForLive=false;uilang=en-US;asset=https://dai.google.com/linear/hls/pb/event/Sid4xiTQTkCT1SLu6rjUSQ/stream/689546a1-c104-43a5-840c-2a431c211dc9:SIN/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "persistentSessionOnlinePlayback": false,
        "persistentSessionsMetadata": [],
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false,
        "minHdcpVersion": "",
        "ignoreDuplicateInitData": true
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "raiseFatalErrorOnManifestUpdateRequestFailure": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            },
            "sequenceMode": false,
            "enableAudioGroups": false
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            "useSafariBehaviorForLive": false,
            "liveSegmentsDelay": 3,
            "sequenceMode": true,
            "ignoreManifestTimestampsInSegmentsMode": false,
            "disableCodecGuessing": false,
            "allowLowLatencyByteRangeOptimization": true
        },
        "mss": {
            "sequenceMode": false,
            "keySystemsBySystemId": {
                "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            }
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "gapJumpTimerTime": 0.25,
        "durationBackoff": 1,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false,
        "segmentPrefetchLimit": 0,
        "liveSync": false,
        "liveSyncMaxLatency": 1,
        "liveSyncPlaybackRate": 1.1,
        "liveSyncMinLatency": 0,
        "liveSyncMinPlaybackRate": 1
    },
    "mediaSource": {
        "codecSwitchingStrategy": "smooth",
        "sourceBufferExtraFeatures": "",
        "forceTransmux": false,
        "insertFakeEncryptionInInit": true
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false,
        "clearBufferSwitch": false,
        "safeMarginSwitch": 0
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "en-US",
    "preferredAudioLabel": "",
    "preferredTextLanguage": "en-US",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoHdrLevel": "AUTO",
    "preferredVideoLayout": "",
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    },
    "ads": {
        "customPlayheadTracker": false
    }
}

**What did you do?**

Step 1: Created a Demo player with HLS Live stream,(taken from CBS NEWS live manifest).
Step2: Observe that the closed caption option is not available.
**Note:** The closed caption options are available in iOS devices.(Due to the Native HLS)
**What did you expect to happen?**
All browsers should be able to have the closed caption option for the embedded caption stream from HLS.

**What actually happened?**

I believe the MSE doesn't creating the text track for the HLS livestream with Embedded caption.
There is no tracks added to the manifest data.
Please refer the below mentioned screenshots.

**iOS Devices- Shaka Demo:**
![image](https://github.com/shaka-project/shaka-player/assets/131441182/3fff442d-ea63-4c14-a914-051bf3b4de37)
![image](https://github.com/shaka-project/shaka-player/assets/131441182/018e99bc-8c8f-4461-a3b0-c531b90ee93d)
![image](https://github.com/shaka-project/shaka-player/assets/131441182/7154e4c8-4937-48ff-8f3c-a2ab0e8a2eb8)

**Normal player using MSE- Shaka Demo:**
![image](https://github.com/shaka-project/shaka-player/assets/131441182/d9b5854e-afc4-4ee0-a3f3-e59fc54bba80)
![image](https://github.com/shaka-project/shaka-player/assets/131441182/4665ce7a-24b2-40c2-9d10-f698fc5638aa)
![image](https://github.com/shaka-project/shaka-player/assets/131441182/fffbd4ae-7c40-4bf6-ac6f-1323e0af2ff0)

**CBS News page:**
![image](https://github.com/shaka-project/shaka-player/assets/131441182/0562c3bc-eba1-4588-bd38-607c6837efbf)

**Comment by avelad** [comment] 2023-11-20 07:47
Duplicate of https://github.com/shaka-project/shaka-player/issues/1826

Right now no one is working on this new feature, but we are happy to review PR to add the feature. Note: for Media Playlist the functionality is supported, but not for Master Playlist.

**Closed by avelad** 2023-11-20 07:47 UTC
Labels: type: bug
