### ISSUE TITLE
Bucketize resolution names in the UI

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2090] opened 2019-08-08 20:44 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
The resolutions menu in the UI shows exact heights in pixels, rather than using well-known names for resolutions like 1080p and 4k.

**Describe the solution you'd like**
The exact width & height should be used to choose a specific name for the resolution.  The mapping could be configurable if needed.

**Describe alternatives you've considered**
Continue using height + 'p'?  Let apps override the naming entirely?

**Additional context**
Some of this could be done in a custom overflow menu item, but that's not very easy at the moment.

**Comment by gregmsanderson** [comment] 2019-08-09 18:55
Seeing this, I tried the Angel One demo on https://shaka-player-demo.appspot.com and it does list common resolutions as 360p, 480p. However it _duplicates_ them.

If you are working on that menu, it should remove duplicates. Perhaps it is parsing and showing both audio and video, but I'd think it should only list video ones?

![Screenshot 2019-08-09 at 19 49 57](https://user-images.githubusercontent.com/10390169/62802236-55b66180-badf-11e9-826f-3a13fe015a0f.png)

**Comment by TheModMaker** [comment] 2019-08-09 18:57
> Seeing this, I tried the Angel One demo on https://shaka-player-demo.appspot.com and it does list common resolutions as 360p, 480p. However it duplicates them.

#2085.

**Comment by gregmsanderson** [comment] 2019-08-09 19:05
Ah, the duplication has already been logged as a separate issue. Nice. Ignore this then

**Comment by joeyparrish** [comment] 2019-08-09 20:34
No worries, @gregmsanderson.  To see this issue in action, try playing something that doesn't have a 4:3 aspect ratio, like Sintel (which is 64:27).

**Comment by ismena** [comment] 2019-08-23 21:20
This was the duplicate of #2085 that has been fixed.

**Comment by TheModMaker** [comment] 2019-08-23 22:07
I don't think that's what @joeyparrish meant for this issue.  I think this issue was about taking videos that have similar resolutions and put them together.  Instead of using the height followed by the letter 'p', we should provide pre-defined buckets to put the videos into (that is configurable).  This will provide more "common" values for videos with slightly different sizes (e.g. we may not want to show an entry for `1081p`).

**Comment by ismena** [comment] 2019-08-23 22:16
Ah, yes, you're probably right.

**Comment by jbglaw** [comment] 2019-10-05 21:14
I'd actually like to see the complete list of resolutions along with their exact width/height values. Maybe shortened for common stuff (ie. 720p, 1080p.)
Also, in "auto" mode, it would be nice to have an indication on the demo app which resolution is in use right now.

**Closed** 2023-10-30 06:36 UTC
Labels: type: enhancement, component: UI, priority: P3
