### ISSUE TITLE
Is there any way to switch Video Player to Audio Player without reloading the manifest

### ISSUE THREAD

**Issue by praveenkumar215** [shaka-project/shaka-player#5341] opened 2023-06-21 09:21 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

4.3.5
**Please ask your question**
Hi Team,

Is there any way to switch Video Player to Audio Player without reloading the manifest?

Currently I am setting 
  playerConfig.manifest.disableVideo = false;
and calling player.load for switch from audio to video
 player.load(mainurl,startTime).then(()=>{
            console.log('manifest loaded');
            }).catch(()=>{
                console.log('error');
            }); 
       })

**Comment by WINOFFRG** [comment] 2023-06-21 14:52
Duplicate of https://github.com/shaka-project/shaka-player/issues/5237

**Closed** 2023-06-21 14:53 UTC
Labels: type: question
