### ISSUE TITLE
HLS mixed audio playlist transmux error (f.e. AWS Mediatailor streams)

### ISSUE THREAD

**Issue by CHaNGeTe** [shaka-project/shaka-player#6357] opened 2024-03-22 09:06 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the problem is related to FairPlay, have you read the tutorial?** N/A

**What version of Shaka Player are you using?** 4.7.11

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `main`?** Not tested yet

**Are you using the demo app or your own custom app?** Demo app

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** Chrome Mac OSX

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** N/A

**What are the manifest and license server URIs?** Hard to reproduce as depends on the Ad decision server, but I sent a sample to  shaka-player-maintainers@googlegroups.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?** Shaka demo defaults

**What did you do?**
Load a playlist coming from AWS Mediatailor that contains mixed audio content, some segments (AD prerolls) are .aac while content is .ts
I know codec switching has been implemented recently, but seems this scenario is not handled gracefully.

So right now the streaming_engine is calling:
```
await this.playerInterface_.mediaSourceEngine.setStreamProperties(
              mediaState.type, timestampOffset, appendWindowStart,
              appendWindowEnd, ignoreTimestampOffset,
              reference.mimeType || mediaState.stream.mimeType,
              reference.codecs || mediaState.stream.codecs, streamsByType);
 ```
 
 Reference mimetype is null, so mediaState.stream.mimeType gets picked instead.
 Reference.getUris() shows a url with .aac extension, but mimeType of mediaState.stream.mimeType is video/mp2t
 So those segments end up trying to be parsed by the ts_parser while they are AAC instead
 
```
const newMimeTypeWithAllCodecs =
          shaka.util.MimeUtils.getFullTypeWithAllCodecs(mimeType, codecs);
      const transmuxerPlugin =
          TransmuxerEngine.findTransmuxer(newMimeTypeWithAllCodecs);
 ```
 transmuxerPlugin gets the value of ts_parser
 
![image](https://github.com/shaka-project/shaka-player/assets/1237997/c26f89cc-dab8-4776-9c7f-ff08aa10c65b)

**What did you expect to happen?**

AAC segments not parsed as TS

**What actually happened?**

Shaka is attempting to parse AAC segments as TS
So `Found TS packet that do not start with 0x47` is logged
and player ends up on [Shaka Error MEDIA.TRANSMUXING_FAILED ()](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3018)

**Comment by CHaNGeTe** [comment] 2024-03-25 07:47
Seems to be related that the middle segments are the ones processed to guess the mimeType:
https://github.com/shaka-project/shaka-player/blob/067d9ce80f71b899be28c41b49b4bad17cb20427/lib/hls/hls_parser.js#L905-L907

I am trying to debug why codecSwitchIfNecessary_ is not detecting the codec switch for this case
https://github.com/shaka-project/shaka-player/blob/067d9ce80f71b899be28c41b49b4bad17cb20427/lib/media/media_source_engine.js#L1848

**Comment by avelad** [comment] 2024-03-25 15:00
With https://github.com/shaka-project/shaka-player/pull/6360 the issue is not longer reproduced

**Comment by CHaNGeTe** [comment] 2024-03-25 16:47
@avelad thanks for the update and the PR!
By any chance do you know if I can ship somehow the build to chromecast? Months ago I compiled the shaka library to test some things locally (web), but with chromecast I am a bit lost as I think the shaka lib is loaded by caf on a custom receiver.
I am using useShakaForHls and specifying the shaka version.

**Comment by avelad** [comment] 2024-03-25 16:49
> @avelad thanks for the update and the PR! By any chance do you know if I can ship somehow the build to chromecast? Months ago I compiled the shaka library to test some things locally (web), but with chromecast I am a bit lost as I think the shaka lib is loaded by caf on a custom receiver. I am using useShakaForHls and specifying the shaka version.

There is an open issue about this, https://github.com/shaka-project/shaka-player/issues/6352, subscribe to it, the team will answer it as soon as they have time.

**Comment by joeyparrish** [comment] 2024-03-28 15:51
I don't believe #6352 is related to how we ship Shaka updates to Chromecast.

If you need a Shaka Player fix for your Chromecast receiver, the process is:

1. File an issue
2. Send a PR or wait for someone else to create a PR
3. Wait for the PR to be reviewed and merged
4. A maintainer then has to merge an automated release PR to start the release process
5. When the GitHub release is complete, a semi-automated Google-internal process begins
6. In roughly 1-3 days, depending on human review timing, the Shaka Player release is available on the Google-owned CDN that CAF uses for Shaka builds
7. You can test Shaka availability in CAF by checking a URL like https://ajax.googleapis.com/ajax/libs/shaka-player/4.3.15/shaka-player.compiled.js - when the new version loads from that domain, you can refer to it in your receiver app
8. You update your receiver app's `shakaVersion` config

**Closed** 2024-04-01 07:26 UTC
Labels: type: bug, component: HLS, priority: P1
