### ISSUE TITLE
Shaka Player's seek bug with Firefox browser

### ISSUE THREAD

**Issue by interlark** [shaka-project/shaka-player#2858] opened 2020-09-20 11:21 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 3.0.4

**Can you reproduce the issue with our latest release version?** yes

**Can you reproduce the issue with the latest code from `master`?** yes

**Are you using the demo app or your own custom app?** custom

**If custom app, can you reproduce the issue using our demo app?** yes

**What browser and OS are you using?** Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** None

**What are the manifest and license server URIs?**
https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/BBB/master-no-scenecut.m3u8
https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/BBB/master.m3u8

https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/ElephantsDream/master-no-scenecut.m3u8
https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/ElephantsDream/master.m3u8

https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/Sintel/master-no-scenecut.m3u8
https://raw.githubusercontent.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut/master/demo/videos/Sintel/master.m3u8

**What did you do?**
Please, see [special repo](https://github.com/interlark/shaka-player-bug_fragmented-mp4-with-scenecut) for this info.

**What did you expect to happen?**
Navigate through timecodes (like youtube's [3:20,](#) [1:21](#), you know) without gitches and freezes.

**What actually happened?**
Video freezes and glitches on seeks through timecodes. You can see a [demo page](https://interlark.github.io/shaka-player-bug_fragmented-mp4-with-scenecut) to test it by yourself with FF browser.

**Comment by martinstark** [comment] 2020-09-21 09:01
Could this be related to/the same as [2427](https://github.com/google/shaka-player/issues/2427)? We are experiencing something similar on Firefox. For us, it seems related to seeking while Shaka is switching between variants. Seeking works fine if waiting until the stream has stabilized on a particular bitrate.

**Comment by joeyparrish** [comment] 2020-09-24 19:34
I'm working on a test failure that may be related.  I haven't found the root cause yet, nor a workaround that we would be willing to commit, but I have found a hack that somehow changes a race condition related to unbuffered seeking.

@interlark, would you be willing to try out this patch and tell me if the problem goes away?  If so, this bug and the test failure probably share a root cause.

```diff
diff --git a/lib/media/streaming_engine.js b/lib/media/streaming_engine.js
index 34100324..88c7bfac 100644
--- a/lib/media/streaming_engine.js
+++ b/lib/media/streaming_engine.js
@@ -1769,6 +1779,7 @@ shaka.media.StreamingEngine = class {
             mediaState.type);
       }
     }
+    await new Promise((r) => setTimeout(r, 100));
     this.destroyer_.ensureNotDestroyed();
 
     shaka.log.debug(logPrefix, 'cleared buffer');
```

**Comment by joeyparrish** [comment] 2020-09-24 22:04
Here's another patch I'd like you to try when you have time.  It fixes the (possibly related) test failure I'm working on.

```diff
diff --git a/lib/media/streaming_engine.js b/lib/media/streaming_engine.js
index 34100324..1c0f05f7 100644
--- a/lib/media/streaming_engine.js
+++ b/lib/media/streaming_engine.js
@@ -1752,6 +1752,8 @@ shaka.media.StreamingEngine = class {
     mediaState.waitingToFlushBuffer = false;
     mediaState.clearBufferSafeMargin = 0;
     mediaState.clearingBuffer = true;
+    mediaState.lastStream = null;
+    mediaState.lastSegmentReference = null;
 
     shaka.log.debug(logPrefix, 'clearing buffer');
 
@@ -1772,8 +1774,6 @@ shaka.media.StreamingEngine = class {
     this.destroyer_.ensureNotDestroyed();
 
     shaka.log.debug(logPrefix, 'cleared buffer');
-    mediaState.lastStream = null;
-    mediaState.lastSegmentReference = null;
     mediaState.clearingBuffer = false;
     mediaState.endOfStream = false;
     this.scheduleUpdate_(mediaState, 0);
```

**Comment by joeyparrish** [comment] 2020-09-25 22:06
@martinstark, #2427 seems to be related to DRM content according to the mozilla bug report linked at the bottom of the issue.  So this is likely something else.

@interlark, when you have time, please let us know if the second patch I provided makes any difference.  The second one fixes a seeking-related test failure on Firefox on Windows, so I'm hopeful this is related.

**Comment by interlark** [comment] 2020-09-26 07:16
@joeyparrish 
1. Second patch didn't solve the problem, Linux still has freezes and Windows still has glitches with the streams
2. I tried first diff too, still nothing.

I also tried to play around https://github.com/google/shaka-player/blob/1c00b4c1fb4a58ef7d7b602fb708cd71e7e1012c/lib/media/media_source_engine.js#L791
The problem's still there :(

**Comment by joeyparrish** [comment] 2021-01-06 21:02
I can't reproduce this issue today in Firefox 82 on Linux, using Shaka Player v3.0.6 or the latest nightly build from the master branch.

With your demo page (https://interlark.github.io/shaka-player-bug_fragmented-mp4-with-scenecut/demo/), in the same browser, when I seek, I get an error message in Firefox about how the file is "corrupt" and can't be played.

Do you still see this issue with the latest Shaka Player and Firefox versions?

**Comment by interlark** [comment] 2021-01-06 21:37
That's strange because video clips are not corrupted, you can check the source code. They are just encoded with extra scenecut frames (which is default behavior for h264 encoder).  I've checked it in Firefox 84.0.1 (64-bit) on Linux and Windows. Are you trying to reproduce it in MacOS?

**Comment by interlark** [comment] 2021-01-06 21:40
Probably, you can also play same stream with hls.js (there are links for shaka and hls.js) and check whether that "file is corrupt" message would still be there.

**Comment by joeyparrish** [comment] 2021-01-06 22:47
Do you have the same issue in Firefox 84 with Shaka Player v3.0.6?  With that version of Shaka Player, I don't see issues with seeking in Firefox 82 on Linux.  That's the only version and platform I've tested with today.

But I'm more interested in whether the issue persists with the latest Shaka Player release than what version of Firefox or OS we're on.

**Comment by interlark** [comment] 2021-01-07 11:35
I've tested the bug on 2 machines + 1 virtual. Shaka definitely has the bug, are you sure you clicked the right links?
I updated demo's shaka version up to 3.0.6 and recorded a screencast with Linux and Windows: https://youtu.be/P_aWcyjM8bM

**Comment by kocoten1992** [comment] 2021-01-07 15:40
On firefox on my computer, it lag like that too, even though it smooth on chrome.

**Comment by interlark** [comment] 2021-01-07 16:32
Yeah, It's smooth anywhere, except combination **Firefox** + **Shaka-Player**.

**Comment by joeyparrish** [comment] 2021-01-07 17:29
I'm sorry, but I still can't reproduce your results with Firefox 84 on Linux.  I'll try to record a video, and if I'm making a mistake, maybe you can spot what I'm doing wrong.

**Comment by joeyparrish** [comment] 2021-01-07 18:30
My results have changed for some reason.  On my local copy of Firefox on Linux, I now get decode failures both in your demo and mine.

I tried Firefox on a Linux machine in our test lab, which I have remote access to while working from home.  On that machine, I get no decode errors.  But, while I can access it remotely, I can't hear the sound.  So I did a screen recording on that machine, then transferred it to my home to see if the sound starts before the video as it does in your screen recording.  Only it can't capture the sound for some reason.  :-(

What I can _see_ in the recording, though, is that on the remote Linux machine, the video takes more than a second to start playing after a seek, leading me to believe that it is probably reproducing your issue.  But it's hard to tell since I have no access to audio from that machine.

@interlark, my guess is that this has to do with transmuxing or with multiplexed (audio+video) segments.  Can you please try the following scenarios?

1. content that is in separate TS streams for audio and video
2. content that is in MP4 instead of TS

My guess is that one of these changes to the content will cause the symptoms to go away, and that this will give us a stronger clue as to why it's behaving badly.

One key difference between us and hls.js is that we use different transmuxers, so the TS-formatted content could easily explain why there is a difference between the two players.  But multiplexed content is also a messy issue, and that could also explain the difference.  I don't know hls.js's treatment of muxed content, but it could be that they split it into two streams while transmuxing, which is something that we don't do.

**Comment by interlark** [comment] 2021-01-08 00:42
Looks like **demuxed** **MP4** and **MpegTS** works fine on FF.
![image](https://user-images.githubusercontent.com/20641837/103960532-24c6da00-5174-11eb-8696-2978de27ebe8.png)

**Comment by joeyparrish** [comment] 2021-01-11 18:26
Thanks for testing that!  I feel confident in saying that this is an issue with either muxed TS content generally or with the way it is created in mux.js (our third-party transmuxer).

I will see if I can create a simplified, non-Shaka repro case for the mux.js folks and file an issue there.  In the mean time, there's not anything we can do in Shaka Player to work around it at this time.  My advice would be to avoid muxed TS content if possible.

**Comment by joeyparrish** [comment] 2022-05-24 17:48
I never did create a repro case to send upstream to mux.js.  But this is no longer reproducible with FF 97 ESR, so I think whatever it is has been fixed in the browser.

**Closed by joeyparrish** 2022-05-24 17:48 UTC
Labels: type: external
