### ISSUE TITLE
Deflake tests on a VM

### ISSUE THREAD

**Issue by srampur** [shaka-project/shaka-player#1179] opened 2017-12-09 07:56 UTC
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes
**What version of Shaka Player are you using**:
master, commit bc7b56d97109c0392d199921bb51429ceb9a9852
**Can you reproduce the issue with our latest release version**:
Yes
**Can you reproduce the issue with the latest code from `master`**:
Yes
**Are you using the demo app or your own custom app**:
Issue observed while "Running the tests"
**If custom app, can you reproduce the issue using our demo app**:
The issue observed while running the tests
**What browser and OS are you using**:
Chrome, 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
**What are the manifest and license server URIs**:
None
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
python build/test.py --browsers Chrome

**What did you expect to happen?**
Pass all the tests

**What actually happened?**
Test failed with below error. Logs:

```
[INFO] Running test (1 / 1)...
Chrome 48.0.2564 (Linux 0.0.0) StreamingEngine gap jumping jumps small gaps in the middle FAILED
        Failed: Timeout waiting for time
            at stack (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2338:17)
            at buildExpectationResult (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2308:14)
            at Spec.Env.expectationResultFactory (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:858:18)
            at Spec.addExpectationResult (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:487:34)
            at Env.fail (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1286:25)
            at jasmineInterface.fail (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4558:23)
Chrome 48.0.2564 (Linux 0.0.0) StreamingEngine gap jumping jumps large gaps in the middle FAILED
        Failed: Timeout waiting for time
            at stack (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2338:17)
            at buildExpectationResult (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2308:14)
            at Spec.Env.expectationResultFactory (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:858:18)
            at Spec.addExpectationResult (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:487:34)
            at Env.fail (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1286:25)
            at jasmineInterface.fail (node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4558:23)
Chrome 48.0.2564 (Linux 0.0.0) StreamingEngine gap jumping won't jump large gaps with preventDefault() FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Chrome 48.0.2564 (Linux 0.0.0): Executed 1311 of 1358 (3 FAILED) (skipped 47) (10 mins 30.952 secs / 10 mins 20.988 secs)
[INFO] Run complete
[INFO] Result (exit code): 1

```

**Comment by srampur** [comment] 2017-12-09 09:29
Still fails when ran the test with the latest chrome

```
Chrome 63.0.3239 (Linux 0.0.0) StreamingEngine gap jumping jumps small gaps in the middle FAILED
        Failed: Timeout waiting for time
            at <anonymous>
Chrome 63.0.3239 (Linux 0.0.0) StreamingEngine gap jumping jumps large gaps in the middle FAILED
        Failed: Timeout waiting for time
            at <anonymous>
```

**Comment by joeyparrish** [comment] 2017-12-12 20:00
@srampur, we run all tests nightly on all supported platforms & browsers, and additionally on Chrome Linux on every change before it is pushed.  We have not been able to reproduce this failure.

I believe the default timeout is 2 minutes.  Are you able to reproduce the failure if you only run those specific tests?  For example, `./build/test.py --filter StreamingEngine.*gap.*middle` ?

While running tests, is your CPU maxed out?  How much CPU time is Chrome using during the test run?

**Comment by srampur** [comment] 2017-12-13 18:51
@joeyparrish , thank you for the details. 

Attached the screenshot of output of test ./build/test.py --filter StreamingEngine.*gap.*middle.

![image](https://user-images.githubusercontent.com/10064150/33956374-529c11c2-e064-11e7-9726-4623c90f96d1.png)

CPU % is below 50 and not much change in load average.
Please to note that the OS is Ubuntu with virtualbox. Does this affect?

**Comment by joeyparrish** [comment] 2017-12-13 18:57
It could be an issue with the virtual machine sharing time with the host CPU.  We do all of our testing on real hardware.

Ideally, we would be able to make the tests robust and flexible enough to work on VMs, but I am not sure what the root of the timeout is.

Can you try running tests with:

`./build/test.py --filter StreamingEngine.*gap.*middle --browsers Chrome --enable-logging=debug --runs 10`

That might give us enough information to hazard a guess.

**Comment by srampur** [comment] 2017-12-14 18:09
[test_errors_shakaplayer_bug1179.txt](https://github.com/google/shaka-player/files/1560299/test_errors_shakaplayer_bug1179.txt)

Thank you for the details. Please find the attached log.

**Comment by vaage** [comment] 2017-12-21 21:34
@joeyparrish What were you hoping to find in the debug log? I don't see anything that stands out to me.

**Comment by joeyparrish** [comment] 2017-12-22 00:26
Here's what looks like the relevant bit from the logs:

```
[INFO] Running test (1 / 10)...
Chrome 63.0.3239 (Linux 0.0.0) INFO LOG: 'Using native EME as-is.'
Chrome 63.0.3239 (Linux 0.0.0) INFO LOG: 'Using native MSE as-is.'
Chrome 63.0.3239 (Linux 0.0.0) INFO LOG: 'Using native Promises.'
Chrome 63.0.3239 (Linux 0.0.0) INFO LOG: 'Using native VTTCue.'                                                                                                                                                                                                                 
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'mvhd box is version 0.'                                                                                                                                                                                                                                               
LOG LOG: 'init: completed initial Stream setup'                                                                                                                                                                                                                                 
LOG LOG: '(audio:3)', 'looking up segment:', 'presentationTime=0', 'currentPeriod.startTime=0'
LOG LOG: 'tfdt box is version 0.'
LOG LOG: '(video:2)', 'looking up segment:', 'presentationTime=0', 'currentPeriod.startTime=0'
LOG LOG: 'tfdt box is version 0.'
LOG LOG: '(video:2)', 'startup complete'
LOG LOG: '(all) setting up Period 0'
LOG LOG: '(all) Period 0 is being or has been set up'
LOG LOG: '(all) Stream 3 is being or has been set up'
LOG LOG: '(all) Stream 2 is being or has been set up'
LOG LOG: '(all): seeked: buffered seek: playheadTime=8'
LOG LOG: 'tfdt box is version 0.'
LOG LOG: 'tfdt box is version 0.'
LOG LOG: '(audio:3)', 'buffered to end of presentation'
LOG LOG: '(video:2)', 'buffered to end of presentation'

  StreamingEngine
    gap jumping
      ✗ jumps small gaps in the middle
        Failed: Timeout waiting for time
            at <anonymous>
```

All 10 runs failed the same way, so it's not flaky.  Still, it doesn't behave the same way for us.

I need to look into the details of the test and see what might have happened.

For now, I'm going to put it in v2.4 and assign it to myself.  I should be able to look into it in the first week of January.

**Comment by srampur** [comment] 2017-12-22 07:08
@joeyparrish, do you need any other details from me? apart from the logs? like Ubuntu VM's details?

**Comment by joeyparrish** [comment] 2017-12-22 16:34
Not at the moment.  But I may end up sending you a patch to get more information from the test logs once I narrow down the cause.

**Comment by joeyparrish** [comment] 2018-01-16 22:53
This has been bumped down my priority list, but I will try to get back to you soon.

**Comment by joeyparrish** [comment] 2018-03-12 12:48
In general, a VM may be a good way to expose performance-dependent tests that need to be deflaked and made more robust.  We see occasional test failures even on real hardware, but those are much more difficult to reproduce.

I'm relabeling this as an enhancement to improve our tests by running them on a VM.

**Closed** 2022-03-31 17:43 UTC
Labels: type: code health, priority: P4
