### ISSUE TITLE
Nullp Resolution on Safari

### ISSUE THREAD

**Issue by GabrielGallina** [shaka-project/shaka-player#5330] opened 2023-06-19 16:23 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
Safari iOS

**What did you do?**
Play any video on Safari and change de resolution, but appears just "nullp"
![image](https://github.com/shaka-project/shaka-player/assets/106389208/6c2ea345-55e9-4230-923b-a150c7697b4f)

**What did you expect to happen?**
Appear resolutions to switch, like in other browsers

**What actually happened?**
When I'm using Safari, only the "nullp" resolution appears, I would like the other resolutions to appear as in other browsers to make the switch. I would like to understand if it could be some configuration or is it a shaka limitation

**Comment by avelad** [comment] 2023-06-20 10:28
@GabrielGallina can you share a stream so we can verify it? thank you!

**Comment by WINOFFRG** [comment] 2023-06-21 10:47
Duplicate of https://github.com/shaka-project/shaka-player/issues/4747 ?

**Comment by avelad** [comment] 2023-06-21 10:48
Maybe

**Comment by GabrielGallina** [comment] 2023-06-21 12:02
@avelad wich information from the stream would be needed to further evaluate?

**Comment by avelad** [comment] 2023-06-21 15:04
@WINOFFRG , @GabrielGallina is using iOS, so no MSE...

**Comment by avelad** [comment] 2023-06-27 07:23
On iOS/ipadOS, the preference is to use Safari's native HLS, but it does not return height/width information, so this information is not returned at this point. Thanks!

**Comment by joeyparrish** [comment] 2023-06-27 23:30
I would like to reopen this, to fix the UI.  The information may not be available, and we may not be able to select a specific resolution, but the UI should not show "nullp".

**Closed** 2023-06-28 10:56 UTC
Labels: type: bug, component: UI, priority: P2, browser: Safari, platform: iOS
