### ISSUE TITLE
DASH processManifest performance regression in 3.x

### ISSUE THREAD

**Issue by philippe-elsass-deltatre** [shaka-project/shaka-player#4062] opened 2022-03-24 13:09 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.x, 3.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Didn't try

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
webOS, Tizen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
webOS 5.00.35
Tizen firmware 2200.9

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration

**What did you do?**

Play a live stream with large DVR (several hours) using different versions of Shaka Player on webOS and Tizen TV (low performance devices)

**What did you expect to happen?**
Playback should be smooth

**What actually happened?**

Using Shaka Player 2.5.x, Shaka is able to load and process the growing live manifest every few seconds.

Using Shaka Player 3.x, the `processManifest` step takes several seconds.

With a 4+h DVR, every time the manifest is reloaded:

- On Tizen, it takes close to 2s
- On webOS, it takes over 10s

There is visibly a considerable performance degradation of the manifest parsing logic, making it barely tolerable on Tizen (UI is frozen during the parsing), and completely unusable on webOS.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-24 16:44
I did some profiling and code reading and I strongly suspect a refactoring which happened between 2.5 and 3:

- Most of the `for` loops have been converted to enumeration loops
- Enumerations are using JS generators
- Generators seem to be transpiled to ES5...

![image](https://user-images.githubusercontent.com/82216401/159967073-50f7f939-735f-4f74-b05b-071dbe009163.png)

Example in `MpdUtils.js`:
```javascript
// Shaka 2.5.x
for (let i=0; i < timePoints.length; ++i) {

// Shaka 3.x
const enumerate = (it) => shaka.util.Iterables.enumerate(it);
for (const {item: timePoint, next} of enumerate(timePoints)) {
```
This looks like an absolutely catastrophic refactoring idea.

**Comment by avelad** [comment] 2022-03-24 17:56
@joeyparrish / @theodab , can you check this? If so, I think it should be changed to improve performance.

**Comment by avelad** [comment] 2022-03-25 07:33
I have created https://github.com/shaka-project/shaka-player/pull/4064 to fix these issues.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 07:52
Amazing @avelad - I was precisely doing these changes locally to see if it was fixing the issue :D

**Comment by avelad** [comment] 2022-03-25 08:41
@philippe-elsass-deltatre Have you seen performance improvements with the fix?

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 09:09
@avelad when profiling with Chrome browser there is a 10x improvement at least.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 09:18
However I'm seeing a worrying climbing of the memory

**Comment by avelad** [comment] 2022-03-25 09:28
Have you seen any memory leak?

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 09:42
There seem to be a massive memory leak: even after unloading Shaka I see memory climbing and if I pause JS I end up in a `setTimeout` callback looking at variants/codecs/decodingInfos

**Comment by avelad** [comment] 2022-03-25 09:48
And is it caused by this change or is it reproduced from before in the master branch?

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 10:00
I don't know that's odd - the player seem to be leaking if I build from source tag v3.3.2. Maybe I'm doing it wrong.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 10:18
Is there something faster than `all.py` to build the library? `build.py` doesn't seem to produce the `shaka-compiled.js`

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 10:34
No I'm good, building from source is fine for `v3.3.2` and `main` - doesn't seem to leak.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 10:46
Ok finally your branch doesn't leak - I did have something wrong.

Performance-wise with release JS the branch is about 40% faster - I'll try that on device now.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 11:01
So... I under-estimated the penalty of the debug JS and my alarming "10s" on LG was a lot due to being a debug build.

Still the branch brings is a major improvement on LG device.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-25 11:20
Unfortunately Shaka 2.5.9 is still MUCH faster. Our LGs stutter with a live stream with 4h DVR with Shaka 3 (even optimised) while Shaka 2 handles it without a sweat.

**Comment by avelad** [comment] 2022-03-25 11:24
The good thing is that the fix is good, although it does not improve everything that it should, but it would be necessary to see what other parts can be optimized.

**Comment by joeyparrish** [comment] 2022-03-25 17:23
Thank you, @avelad, for fixing this!  Should we leave this issue open for further investigation, or should PR #4064 close it?

**Comment by avelad** [comment] 2022-03-25 18:08
I think that PR is an improvement but this issue should keep open for more investigation

**Comment by joeyparrish** [comment] 2022-03-25 20:56
I have done some analysis and have concluded that ES6 generators, even when not transpiled to ES5, are monstrously slow.  We use them in two methods of `shaka.util.Iterables` and in two places in `lib/cea/`.

Here's a comparison of three ways to iterate through a large array of 100k items:
1. Using shaka.util.Iterables.enumerate as transpiled to ES5
2. Using shaka.util.Iterables.enumerate in raw ES6
3. Using a version of shaka.util.Iterables.enumerate in raw ES6 with the generator removed

The results are shocking.  The first two methods are similar (159.8 runs / second vs 176.2 runs / second).  So the compiler does not seem to add _much_ in the way of overhead (around 10%).

But the third method, which is only two lines difference from the second, runs at 3141.2 runs / second, or 17.8x faster.

So we need to get rid of **all** generator usage and ban it at the compiler level.

To reproduce these results, open https://jsbench.me/jnl16wbdor/1 and click "Run" at the top.  Keep the tab in the foreground, or else the results will be thrown off by throttling in the browser.

**Comment by joeyparrish** [comment] 2022-03-25 22:14
@philippe-elsass-deltatre, please try this build which removes all generators (and makes no other changes):

 - commit: https://github.com/joeyparrish/shaka-player/commit/810df3d5cb82cbd2710f73a72cc7d2c0f758c012
 - build w/o UI: 
[shaka-player.compiled.js.txt](https://github.com/shaka-project/shaka-player/files/8354071/shaka-player.compiled.js.txt)
 - build w/ UI: [shaka-player.ui.js.txt](https://github.com/shaka-project/shaka-player/files/8354069/shaka-player.ui.js.txt)

If that is a meaningful improvement in performance for you, we can pursue something like this as a solution.  (Though this is just a drop-in, API compatible replacement of generators with returned Arrays.  We may want to evaluate individual cases and make more changes like @avelad's.)

**Comment by philippe-elsass-deltatre** [comment] 2022-03-26 08:54
Nice - I've never been a big fan of generators but now I have an excuse :D 

One thing I notice in Shaka 3 VS Shaka 2 is MUCH larger times spent in GC.  An `enumerate` function returning Arrays is ok for simple cases, but generally causes more garbage to be generated. One code part I found suspicious (but happened to be the same in v2) was the `MpdUtils.inheritAttribute` which creates multiple arrays where an old-school if/else would create less garbage.

**Comment by philippe-elsass-deltatre** [comment] 2022-03-26 08:56
I'll try your branch on Monday @joeyparrish - BTW it would be very handy if your Github CI would create an artefact with the `dist` content, so it's easier to get a legitimate build.

**Comment by avelad** [comment] 2022-03-28 07:07
@philippe-elsass-deltatre do you have some improvement in `MpdUtils.inheritAttribute`?

**Comment by philippe-elsass-deltatre** [comment] 2022-03-28 07:31
@joeyparrish so the good news is that your branch's timings are on par with @avelad's, which means replacing the loops may not be critical, however here's a timeline capture to compare Shaka 3 (left) and Shaka 2.5 (right) on device (same stream, about same time):
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/82216401/160348108-c99f46fc-6e2d-43e6-898e-f708e4c724ca.png">

**Comment by avelad** [comment] 2022-03-28 07:37
Are you using disableXlinkProcessing = true in v3?

**Comment by philippe-elsass-deltatre** [comment] 2022-03-28 07:54
Good call @avelad - unfortunately I don't see any performance difference (I double checked I got the config right).

**Comment by philippe-elsass-deltatre** [comment] 2022-03-28 09:41
Did some more testings and it's looking like Shaka 3.0.8 DASH processing is much faster than 3.3. Possibly on par with 2.5.
However both have massive GC times, causing most live playback to stutter on my webOS, as opposed to 2.5 which has very lean memory usage.

**Comment by avelad** [comment] 2022-03-28 09:52
Can you identify the version with the slow performance? 3.0.9, 3.0.10,...? If we identify the version we can do a bisec...

**Comment by philippe-elsass-deltatre** [comment] 2022-03-29 07:18
3.2.4 VS 3.3.0: almost double memory usage:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/82216401/160555300-09820768-6946-4924-8954-15da5d22dda4.png">

**Comment by philippe-elsass-deltatre** [comment] 2022-03-29 07:28
Every versions until 3.2.4 seem similar in terms of memory usage, then there's this doubling at 3.3.0 (in particular doubling of Nodes). The last PR merged in `main` improves CPU usage but doesn't improve memory usage.

Note: in comparison, Shaka 2.5 uses about half as much memory than the best 3.x. Generally excessive GC seem to be the main killer of TV devices.

**Comment by avelad** [comment] 2022-03-29 09:36
I've been looking around and my feeling is that it's something to do with mediaCapabilities.

**Comment by joeyparrish** [comment] 2022-03-30 23:46
If I recall correctly, the MediaCapabilities code processes a lot of Arrays.  Any way to identify from the debugger what is being collected when we spend too much time in GC?  I don't have much experience in this.

**Comment by avelad** [comment] 2022-04-01 07:00
@philippe-elsass-deltatre  Can you test with https://github.com/shaka-project/shaka-player/pull/4092 ? In my tests I have seen that avoiding two for loops and having two arrays reduces CPU and memory usage.

**Comment by philippe-elsass-deltatre** [comment] 2022-04-01 08:31
Hey @avelad, I'm really not seeing a difference in memory usage (compared to 3.3.2 release). Performance is better but it looks like it's still creating twice as much "nodes" than in previews 3.x (before 3.3.0) and that's really killing the TV.

**Comment by avelad** [comment] 2022-04-01 08:36
Well at least there is a difference for the better, but not substantial, I did not expect a radical improvement with a single change.

**Comment by avelad** [comment] 2022-04-01 08:37
@philippe-elsass-deltatre If you have any idea, or point of the code to improve I can take a look at it.

**Comment by philippe-elsass-deltatre** [comment] 2022-04-01 08:54
@avelad I'm finding, when doing a memory snapshot, that there is twice as many `shaka.media.SegmentReferences` created in Shaka 3.3+ than in previous versions, retaining twice as much memory.

**Comment by philippe-elsass-deltatre** [comment] 2022-04-01 09:07
@avelad I think it's related to these changes (addition of the `streamMap_` and the `closeSegmentIndex` closure):
<img width="909" alt="image" src="https://user-images.githubusercontent.com/82216401/161232325-39d606ca-027e-4c3b-a288-fd3a15512610.png">

**Comment by avelad** [comment] 2022-04-01 09:13
Maybe related to https://github.com/shaka-project/shaka-player/commit/fce5935800d5bb85dfe7a57be1ced6abcbf78628?

**Comment by philippe-elsass-deltatre** [comment] 2022-04-01 09:21
Yes that's it. Not sure what the PR was meant to fix exactly, but the side effect is doubling the memory usage.

**Comment by avelad** [comment] 2022-04-01 09:22
@joeyparrish, can that commit be reverted?

**Comment by philippe-elsass-deltatre** [comment] 2022-04-01 09:23
The PR surely had a good reason to be - you should first find that out.

**Comment by theodab** [comment] 2022-04-05 07:22
That change was made in preparation for b16d30c249586ae569fc9d632e3be593cb095ed8, which was ironically meant to reduce our memory usage. The `closeSegmentIndex` closure is meant to allow us to release the previous stream's segment index when switching streams, so that we only hold one segment index in memory at a time.

As for the actual performance... I tried taking heap snapshots in both nightly and v3.2.4, on macOS, and they both had the same number of SegmentReference objects, after waiting for the manifest to be updated. About the same number of SegmentIndex objects too. Perhaps, if GC is a big problem as you said, on Tizen we are having old SegmentIndex stick around and gum up the heap, or something to that effect.

**Comment by philippe-elsass-deltatre** [comment] 2022-04-05 08:09
@theodab it seems the "create only when needed" isn't working - on our live stream the 3.3.x player creates twice the amount of objects than previous versions (we were using 3.0.x before) and basically eats twice as much memory.

**Comment by avelad** [comment] 2022-04-11 15:08
@philippe-elsass-deltatre can you share the stream?

**Comment by joeyparrish** [comment] 2022-04-13 22:22
@philippe-elsass-deltatre, @avelad, I started looking into memory heap snapshots in Chrome across versions of Shaka Player.  I tested the latest releases of the last several release branches: v3.3.2, v3.2.4, v3.1.6, v3.0.15, and v2.5.23.

I started with VOD content, since I thought that would make my results more repeatable (fewer timing issues with regard to manifest updates).  I played the MP4-only version of Sintel as encoded by Shaka team (https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd), and took heap snapshots at about time index 40.

I should also mention that this is not as strictly scientific as it could be.  Each version of the demo is different at the demo app level, too, so changes in our usage of less.js, for example, can influence the allocation patterns of different versions of the demo.

With VOD, the memory consumed by things attached to `window` is similar across versions, trending slightly downward in the newer releases.

Focusing specifically on segments, v3.3 has fewer SegmentIndex objects and fewer SegmentReference objects.  All versions have one living SegmentIndex object with no data in it (not sure where that comes from), but beyond that, v3.3 only has one audio index and one video index, which is how it should be since implementing closeSegmentIndex().  Older v3's have one per video resolution we've played in the past.  v2.5 has one per resolution that exists in the manifest.

So for VOD, v3.3 has fewer SegmentReferences in memory than any previous version.

SegmentReferences have also gotten slightly larger over time.

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| SegmentReference size | 116 | 136 | 172 | 180 | 180 | 184 |
| num SegmentIndexes | 10 | 5 | 5 | 5 | 3 | 3 |
| num SegmentReferences | 2220 | 888 | 888 | 888 | 444 | 444 |

So the changes for closeSegmentIndex and friends seem to be effective, at least in VOD, at keeping down the number of SegmentReferences in memory.

However, anonymous Objects are trending up over time, as is the category that Chrome labels "system" (whatever that means):

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| Objects | 3300 | 6800 | 7100 | 5300 | 6200 | 7300 |
| "system" | 71k | 92k | 93k | 87k | 95k | 94k |

I have not yet found a good way to filter through those anonymous objects.  I can click on individual objects and see, for example, "this one's from less.js", or "this one is the shaka namespace", etc.  But to figure out how we doubled the number and where they come from, that won't help.

@philippe-elsass-deltatre, is this what you're seeing as the problem?  Anonymous objects?

I find myself wishing we used more namespaced classes, so that it was easier to filter and tell what things are.  We should think about getting rid of most "record" types in the future, if possible.

**Comment by joeyparrish** [comment] 2022-04-13 22:44
I started scrolling through the full list of anonymous objects in the debugger, and I noticed many with the same size.  All of the ones of that size that I clicked on where from tippy.js, the library which provides tooltips in our demo.  This made me very suspicious that I should have eliminated the demo from my testing at the very beginning.  So I tried a quick test, in which I removed all the dependencies I could from the demo:

1. mux.js (optional)
2. Cast SDK (optional)
3. IMA SDK (optional)
4. dialog polyfill (some browsers only)
5. TextEncoder polyfill (some browsers only)
6. Awesomplete, popper, and tippy (not optional per se, but also commented out the parts of the demo that reference them)

With that, I see a reduction from 7300 objects to 3400 objects.  I can't say for sure which dependency was responsible for those, but this is motivation enough to build a test harness that is as stripped down as possible, without any demo code.

**Comment by joeyparrish** [comment] 2022-04-13 23:48
It was worth the effort.  Here is the code:

memory.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="memory.js"></script>
  </head>
  <body>
    <video id="video"
           width="640"
           poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
           controls></video>
  </body>
</html>
```

memory.js:
```js
const manifestUri =
    'https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd';
const scriptRoot =
    'https://ajax.googleapis.com/ajax/libs/shaka-player';
const scriptName = 'shaka-player.compiled.js';

function initApp() {
  shaka.polyfill.installAll();
  window.player = new shaka.Player(video);
  player.load(manifestUri);
}

function loadShaka() {
  const version = location.search.substr(1);
  const url = version ?
    scriptRoot + '/' + version + '/' + scriptName :
    'dist/' + scriptName;

  const script = document.createElement('script');
  script.defer = false;
  script.async = false;
  script.onload = initApp;
  script.setAttribute('src', url);

  document.head.appendChild(script);
}

document.addEventListener('DOMContentLoaded', loadShaka);
```

I then used the query string to choose a version (or blank for the local build).  Because these are compiled builds, there is no class name info for shaka-namespaced objects.  Here are my results:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects | 626 | 653 | 673 | 685 | 705 | 727 |
| anonymous Object size | 593kB | 352kB | 414kB | 421kB | 360kB | 369kB |
| "system" objects | 44k | 43k | 44k | 44k | 44k | 53k | 
| "system" object size | 1.7MB | 1.6MB | 1.6MB | 1.6MB | 1.7MB | 2.1MB |
| "closure" objects | 8700 | 7200 | 7600 | 7600 | 7200 | 8500 |
| "closure" objects size | 1.0MB | 1.0MB | 1.0MB | 1.0MB | 1.0MB | 1.1MB |

I think it is safe to say, then, that although the demo app is creating many more objects, the Shaka library itself doesn't appear to be.  This is a test that does not use the UI, though.  I'll test again with the Shaka UI to see if we have any issues there.  I will also try with a live stream, which could make a difference as well.

**Comment by joeyparrish** [comment] 2022-04-20 17:30
With the UI:

memory-ui.html
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="memory-ui.js"></script>
  </head>
  <body>
    <div data-shaka-player-container style="width: 640px;">
      <video id="video"
             data-shaka-player
             poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
             style="width:100%;height:100%"></video>
    </div>
  </body>
</html>
```

memory-ui.js
```js
const manifestUri =
    'https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd';
const scriptRoot =
    'https://ajax.googleapis.com/ajax/libs/shaka-player';
const scriptName = 'shaka-player.ui.js';
const cssName = 'controls.css';

function initApp() {
  window.player = video.ui.getControls().getPlayer();
  player.load(manifestUri);
}

function loadShaka() {
  const version = location.search.substr(1);
  const linkUrl = version ?
    scriptRoot + '/' + version + '/' + cssName :
    'dist/' + cssName;
  const scriptUrl = version ?
    scriptRoot + '/' + version + '/' + scriptName :
    'dist/' + scriptName;

  const link = document.createElement('link');
  link.setAttribute('rel', 'stylesheet');
  link.setAttribute('type', 'text/css');
  link.setAttribute('href', linkUrl);

  document.head.appendChild(link);

  const script = document.createElement('script');
  script.defer = false;
  script.async = false;
  script.setAttribute('src', scriptUrl);

  document.head.appendChild(script);
}

document.addEventListener('DOMContentLoaded', loadShaka);
document.addEventListener('shaka-ui-loaded', initApp);
```

Results:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects | 1558 | 1924 | 1989 | 1991 | 2048 | 2505 |
| anonymous Object size | 1.3 MB | 849 kB | 919 kB | 956 kB | 839 kB | 977 kB |
| "system" objects | 70k | 70k | 72k | 72k | 73k | 105k |
| "system" object size | 2.5 MB | 2.5 MB | 2.6 MB | 2.6 MB | 2.6 MB | 5.2 MB |
| "closure" objects | 17k | 14k | 14k | 15k | 14k | 18k |
| "closure" objects size | 2.1 MB | 2.0 MB | 2.1 MB | 2.1 MB | 2.1 MB | 2.5 MB |

The number of objects and the increase in number of objects across versions are both a bit worse with the UI than without it, but nowhere near the 2x figure seen in the full demo.  There is a sharp uptick in "system objects" in the nightly build, but it's not clear what those are.

**Comment by joeyparrish** [comment] 2022-04-20 19:09
For the live stream test, I used https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd, but otherwise the code was the same as the non-UI test above.  This manifest uses SegmentTemplate+duration, rather than an explicit list of segments.

I took a snapshot after 1 minute of playback, then again after 10 minutes of playback.  I clicked the debugger's "collect garbage" button right before each snapshot.

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-19) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects (1m) | 553 | 1811 | 1913 | 610 | 1963 | 1690 |
| anonymous Objects (10m) | 556 | 534 | 602 | 617 | 638 | 1682 |
| anonymous Object size (1m) | 275 kB | 788 kB | 879 kB | 336 kB | 870 kB | 772 kB |
| anonymous Object size (10m) | 288 kB | 292 kB | 327 kB | 342 kB | 359 kB | 776 kB |
| "system" objects (1m) | 44k | 67k | 72k | 47k | 73k | 101k |
| "system" objects (10m) | 44k | 42k | 47k | 48k | 47k | 101k |
| "system" object size (1m) | 1.7 MB | 2.5 MB | 2.7 MB | 1.9 MB | 2.7 MB | 5.1 MB |
| "system" object size (10m) | 1.7 MB | 1.5 MB | 1.7 MB | 1.9 MB | 1.7 MB | 5.1 MB |
| "closure" objects (1m) | 6k | 13k | 14k | 7k | 14k | 17k |
| "closure" objects (10m) | 6k | 6k | 7k | 7k | 7k | 17k |
| "closure" objects size (1m) | 777 kB | 2.0 MB | 2.1 MB | 992 kB | 2.2 MB | 2.2 MB |
| "closure" objects size (10m) | 900 kB | 919 kB | 1.0 MB | 1.0 MB | 1.0 MB | 2.3 MB |

Not sure what to make of this data yet.

**Comment by avelad** [comment] 2022-04-22 15:31
@joeyparrish , have you been able to see what has caused such an increase in memory/object usage?

**Comment by joeyparrish** [comment] 2022-04-22 16:06
Here's the results of my various runs side-by-side:

VOD:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects | 626 | 653 | 673 | 685 | 705 | 727 |
| anonymous Object size | 593kB | 352kB | 414kB | 421kB | 360kB | 369kB |

VOD+UI:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects | 1558 | 1924 | 1989 | 1991 | 2048 | 2505 |
| anonymous Object size | 1.3 MB | 849 kB | 919 kB | 956 kB | 839 kB | 977 kB |

Live:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-19) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects (10m) | 556 | 534 | 602 | 617 | 638 | 1682 |
| anonymous Object size (10m) | 288 kB | 292 kB | 327 kB | 342 kB | 359 kB | 776 kB |

Here are the same tables expressed in percentages relative to the previous release branch:

VOD:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects |  | +4.3% | +3.0% | +1.8% | +2.9% | +3.1% |
| anonymous Object size |  | -40.7% | +17.6% | +1.7% | -14.5% | +2.5% |

VOD+UI:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-13) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects |  | +23.5% | +3.4% | +0.1% | +2.9% | +22.3% |
| anonymous Object size |  | -34.7% | +8.2% | +4.0% | -12.2% | +16.4% |

Live:

| attribute | v2.5 | v3.0 | v3.1 | v3.2 | v3.3 | nightly (2022-04-19) |
| --- | --- | --- | --- | --- | --- | --- |
| anonymous Objects (10m) |  | -4.0% | +12.7% | +2.5% | +3.4% | +163.6% |
| anonymous Object size (10m) |  | +1.4% | +12.0% | +4.6% | +5.0% | +116.1% |

Total memory usage for VOD actually got **better** in the transition to v3.0.  The number of objects increased slightly for VOD, while bytes consumed is down.

The UI allocated signficantly more objects in the v3.0 transition, and again in v4.0 (prerelease).

Allocations for live were mostly flat in the v3.0 transition, and got worse in v3.1, and much much worse in v4.0 (prerelease).  The v4.0 numbers for live seem so bad that I question my data.

Collecting this data without automation is really hard, and I won't be surprised if I messed it up somehow.  I also won't be surprised to learn that eliminating generators caused more object allocations in some area, or if a particular change in the main branch (but not in v3.3) is causing the uptick.

The worst increase in memory usage appears to be the demo app itself.  We added additional third-party UI dependencies to the demo that are not in the library, so that's not surprising.  So I would advise making sure that memory testing is done outside the demo.  See my code snippets above for the test harnesses I used.

**Closed** 2022-05-02 19:58 UTC
Labels: type: bug, type: performance, priority: P1, component: DASH

**Comment by cristian-atehortua** [comment] 2022-08-12 14:28
Hi, just looking at this issue because we are facing a big rebuffering problem on webOS devices 3.x and 4.4.
Our live manifests have a 4H DVR window and because of that Audio tracks on it are represented by a SegmentTimeline with around 2500 Segments. That is because each audio segment's duration differs from the next.

I saw the function that is wasting more time to execute is `MpdUtils.createTimeline` and a big part of that time is what the system waste on `getAtribute` for each attribute of each segment.

I was thinking that a good approach to solve the issue is to make this processing on demand, only when the segment is about to be used. I know this implies a big refactor on the way SegmentIndex works but maybe you can take this as a reference to improve it What do you think?

**Comment by joeyparrish** [comment] 2022-08-12 20:04
Thanks for the hint!  Yes, I think you're right that this would be a big refactor to SegmentIndex.  Perhaps we can find a new way to abstract SegmentReference to make this work.  A parse-on-demand structure would require us to keep the XML elements in memory, but perhaps this would still be a win.

**Comment by avelad** [comment] 2023-02-09 09:35
I think the problem has been mitigated with the latest versions. can you check it?

**Comment by cristian-atehortua** [comment] 2023-02-10 19:03
Hi @avelad, I didn't look to perform better in the latest versions.

We found that this has a special impact when a live manifest has more than one audio track. It looks like Shaka parses each AdaptationSet even if that audio track is not selected. Maybe a "quick" win could be to delay parsing of the audio tracks until they're selected. What do you think @joeyparrish?

**Comment by theodab** [comment] 2023-02-14 08:18
We already added support for delaying the parsing of HLS media playlists, so some of the work for variants not fully loading until chosen is already done.
I'm still not sure if the required changes to the DASH parser would be "quick", though, even with that. When we changed the HLS parser that way, we were finding new bugs with it for weeks.

**Comment by cristian-atehortua** [comment] 2023-02-14 13:21
Well, based on the workaround we applied I think delaying could be a practical solution.

To workaround on the issue we preprocess the manifest and we just keep a single audio track, deleting completely the AdaptationSets that don't match the user's language preference. This is a feature loss but we had to do it because if not, our streams will not be playable. I think we can avoid the feature loss if Shaka optimize the way it process the manifest.

Just to clarify, this happens with our live streams that has the representation with SegmentTimeline and only on WebOS v3 and v4 since this platforms looks to be very limited in resources.

**Comment by theodab** [comment] 2023-02-14 20:17
Well, I don't think it will have memory savings as great as preprocessing the manifest by removing entire tracks. We will need to keep the stuff we haven't parsed in memory, after all, so it can be parsed later. But I think it's probably worth a try.

I have other higher-priority issues I need to get to first, though, so I won't be able to work on this right away.
