### ISSUE TITLE
Memory leak on multi-period streams

### ISSUE THREAD

**Issue by bbert** [shaka-project/shaka-player#6239] opened 2024-02-09 10:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.2.x => 4.7.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
chrome, windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/4577dca5f8a44756875ab5cc913cd1f1/index.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Play stream and take memory heap snapshots using chrome dev tools at different times

**What did you expect to happen?**
Memory heap to be stable

**What actually happened?**

Memory heap grows consistently for multi-period streams.
On mono-period streams, we dot not notice the same result.

Please find screenshots:

- Heap snapshots to illustrate inscrease of memory consumption:
![image](https://github.com/shaka-project/shaka-player/assets/5312520/9a6a0c72-86ba-4dfb-8b7d-35264c5966c1)

- Snapshots comparison after 45 minutes
![image](https://github.com/shaka-project/shaka-player/assets/5312520/4ff0fba7-48b0-41a5-a685-5750c9b58a05)

- Details and allocation call stack (based on v4.5.x) of retained objects
![image](https://github.com/shaka-project/shaka-player/assets/5312520/b4caa67d-35a3-4caf-aaa6-56abfe89012d)

Please note that all objects (Text, Element, NodeList ...) are allocated in the same place.

**Comment by bbert** [comment] 2024-02-19 07:36
I'm not sure this is a duplicate of #6070 since #6070 memory issue is related to SegmentTimeline and the one described in this issue is more generally related to multi-periods, and noticeably since at least v 4.2.x.

**Comment by avelad** [comment] 2024-05-06 15:17
@bbert Can you test if it still happens with 4.8.1? Thanks!

**Comment by bbert** [comment] 2024-05-13 12:08
@avelad Have you tested on your side?
I still observe memory increase:
![image](https://github.com/shaka-project/shaka-player/assets/5312520/90522429-5cf5-426c-9b2e-8f64fc3b400d)

**Comment by avelad** [comment] 2024-05-13 12:14
We solved a memory leak, but I didn't know if it had solved all your problems or not.

**Comment by avelad** [comment] 2024-05-13 12:47
Do you want send a PR to fix it?

**Comment by bbert** [comment] 2024-05-13 13:13
For the time being, I'm not enough aware of source code to try to fix it in the shot term.

It seems indeed that the initial reason of the identified memory leak has been fixed (as discussed in #6070), but here is a potential clue to identify the leak:

![image](https://github.com/shaka-project/shaka-player/assets/5312520/2cb14930-ad3e-4aef-b8bb-d96489f760a2)

**Comment by MichaelSweden** [comment] 2024-05-14 12:09
I have tested the stream in this issue with Cobalt browser with a simple html page and default shaka config. Using main branch (12 May, last commit 5f8628a4a). I can confirm growing memory usage. Also tested in Chromium (124.0.6367.155, Xubuntu 22.04) and see these JS heap size:
5 min : 12-16 MB
1 hour : 83-91 MB
2 hours : 174-179 MB
3 hours : 257-263 MB

PS. We have a similar problem with another dash live stream and I have a fix for it. However that fix doesn't solve this issue.

**Comment by avelad** [comment] 2024-07-15 15:34
In version 4.10.6 we have introduced some improvements, can you validate if it is enough or do we need more improvements? Thanks!

**Comment by bbert** [comment] 2024-07-23 09:42
Hi @avelad 
From my point of view and the quick test I've done, there is no real improvement.

![image](https://github.com/user-attachments/assets/ed595344-6429-4141-89e7-8caa3936d723)

**Comment by avelad** [comment] 2024-08-22 14:40
I can reproduce the issue on the main branch

**Comment by avelad** [comment] 2024-08-27 11:54
I'm testing with the main branch and I'd say the problem is much smaller now, @bbert can you check it?

![imagen](https://github.com/user-attachments/assets/6e5fe441-c386-47fc-bee6-8b5f7cd25eff)
the difference between each snapshot is 5 minutes (aprox)

**Comment by bbert** [comment] 2024-09-05 13:11
@avelad I have made some tests also with main branch, I still notice memory leaks more like 4 to 6MB every 5 minutes, similar to what I had previously measured.

![image](https://github.com/user-attachments/assets/9ddcf17a-a3c9-4525-b454-6d4bef54ce9f)

**Comment by avelad** [comment] 2024-09-05 14:19
I found a leak in `shaka.media.MetaSegmentIndex`, `this.indexes_` always grows and never deletes indexes that are no longer valid, so every time an old period is deleted from the manifest, so it remains referenced (`shaka.dash.TimelineSegmentIndex`). @bbert If you have any ideas to fix this, they're welcome!

**Comment by avelad** [comment] 2024-09-13 14:13
@bbert I think we have improved the memory usage significantly, you can check it in the main and nightly branches. If the problem is solved for you, please let us know.

**Comment by avelad** [comment] 2024-09-16 12:03
thanks for the update @bbert! Since we have already improved everything we could, I proceed to close the issue as resolved!

**Closed by avelad** 2024-09-16 12:03 UTC
Labels: flag: seeking PR, status: waiting on response, type: performance, priority: P2, component: DASH
