### ISSUE TITLE
Missing audio stream in hls playback

### ISSUE THREAD

**Issue by Karma2424** [shaka-project/shaka-player#6036] opened 2024-01-02 20:59 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to fairplay

**What version of Shaka Player are you using?**

v4.7.1 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes 

**Are you using the demo app or your own custom app?**
Demo 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10.0; Win64; x64 Chrome/120

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not using embedded device

**What are the manifest and license server URIs?**

```xml
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Hindi",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="hi",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Telugu",AUTOSELECT=YES,LANGUAGE="te",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_33638_tel=33600.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Tamil",AUTOSELECT=YES,LANGUAGE="ta",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_33639_tam=33600.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Kannada",AUTOSELECT=YES,LANGUAGE="kn",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_33643_kan=33600.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Malayalam",AUTOSELECT=YES,LANGUAGE="ml",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_33644_mal=33600.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-33",NAME="Marathi",AUTOSELECT=YES,LANGUAGE="mr",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_33645_mar=33600.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=212000,AVERAGE-BANDWIDTH=193000,CODECS="mp4a.40.2,avc1.42E015",RESOLUTION=426x240,FRAME-RATE=25.000,AUDIO="audio-aacl-33"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_33637_hin=33600-video=148000.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Hindi",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="hi",CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Telugu",AUTOSELECT=YES,LANGUAGE="te",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_98835_tel=98800.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Tamil",AUTOSELECT=YES,LANGUAGE="ta",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_98836_tam=98800.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Kannada",AUTOSELECT=YES,LANGUAGE="kn",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_98840_kan=98800.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Malayalam",AUTOSELECT=YES,LANGUAGE="ml",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_98841_mal=98800.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-98",NAME="Marathi",AUTOSELECT=YES,LANGUAGE="mr",CHANNELS="2",URI="/jiotv/m3u8/Pogo_Hindi_MOB-audio_98842_mar=98800.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=407000,AVERAGE-BANDWIDTH=370000,CODECS="mp4a.40.2,avc1.42E015",RESOLUTION=512x288,FRAME-RATE=25.000,AUDIO="audio-aacl-98"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_98834_hin=98800-video=250000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=650000,AVERAGE-BANDWIDTH=591000,CODECS="mp4a.40.2,avc1.4D4015",RESOLUTION=512x288,FRAME-RATE=25.000,AUDIO="audio-aacl-98"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_98834_hin=98800-video=458400.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=931000,AVERAGE-BANDWIDTH=847000,CODECS="mp4a.40.2,avc1.4D401E",RESOLUTION=768x432,FRAME-RATE=25.000,AUDIO="audio-aacl-98"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_98834_hin=98800-video=699600.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1122000,AVERAGE-BANDWIDTH=1020000,CODECS="mp4a.40.2,avc1.4D401F",RESOLUTION=1024x576,FRAME-RATE=25.000,AUDIO="audio-aacl-98"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_98834_hin=98800-video=863200.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2075000,AVERAGE-BANDWIDTH=1886000,CODECS="mp4a.40.2,avc1.64001F",RESOLUTION=1024x576,FRAME-RATE=25.000,AUDIO="audio-aacl-98"
/jiotv/m3u8/Pogo_Hindi_MOB-audio_98834_hin=98800-video=1680400.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=22000,URI="/jiotv/m3u8/keyframes/Pogo_Hindi_MOB-video=148000.m3u8",CODECS="avc1.42E015",RESOLUTION=426x240
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=37000,URI="/jiotv/m3u8/keyframes/Pogo_Hindi_MOB-video=250000.m3u8",CODECS="avc1.42E015",RESOLUTION=512x288
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=102000,URI="/jiotv/m3u8/keyframes/Pogo_Hindi_MOB-video=699600.m3u8",CODECS="avc1.4D401E",RESOLUTION=768x432
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=126000,URI="/jiotv/m3u8/keyframes/Pogo_Hindi_MOB-video=863200.m3u8",CODECS="avc1.4D401F",RESOLUTION=1024x576
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```json
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "persistentSessionOnlinePlayback": false,
    "persistentSessionsMetadata": [],
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "keySystemsMapping": {},
    "parseInbandPsshEnabled": false,
    "minHdcpVersion": "",
    "ignoreDuplicateInitData": true
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "raiseFatalErrorOnManifestUpdateRequestFailure": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      },
      "sequenceMode": false,
      "enableAudioGroups": false,
      "multiTypeVariantsAllowed": true
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "defaultAudioCodec": "mp4a.40.2",
      "defaultVideoCodec": "avc1.42E01E",
      "ignoreManifestProgramDateTime": false,
      "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
      "useSafariBehaviorForLive": true,
      "liveSegmentsDelay": 3,
      "sequenceMode": true,
      "ignoreManifestTimestampsInSegmentsMode": false,
      "disableCodecGuessing": false,
      "allowLowLatencyByteRangeOptimization": true
    },
    "mss": {
      "sequenceMode": false,
      "keySystemsBySystemId": {
        "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
      }
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "gapJumpTimerTime": 0.25,
    "durationBackoff": 1,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30,
    "parsePrftBox": false,
    "segmentPrefetchLimit": 0,
    "liveSync": false,
    "liveSyncMaxLatency": 1,
    "liveSyncPlaybackRate": 1.1,
    "liveSyncMinLatency": 0,
    "liveSyncMinPlaybackRate": 1,
    "allowMediaSourceRecoveries": true,
    "minTimeBetweenRecoveries": 5
  },
  "mediaSource": {
    "codecSwitchingStrategy": "smooth",
    "sourceBufferExtraFeatures": "",
    "forceTransmux": false,
    "insertFakeEncryptionInInit": true
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": false,
    "restrictToScreenSize": false,
    "ignoreDevicePixelRatio": false,
    "clearBufferSwitch": false,
    "safeMarginSwitch": 0
  },
  "autoShowText": 3,
  "preferredAudioLanguage": "en-US",
  "preferredAudioLabel": "",
  "preferredTextLanguage": "en-US",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoHdrLevel": "AUTO",
  "preferredVideoLayout": "",
  "preferredVideoLabel": "",
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferSpatialAudio": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "useHeaders": false
  },
  "cmsd": {
    "enabled": true,
    "applyMaximumSuggestedBitrate": true,
    "estimatedThroughputWeightRatio": 0.5
  },
  "lcevc": {
    "enabled": false,
    "dynamicPerformanceScaling": true,
    "logLevel": 0,
    "drawLogo": false
  },
  "ads": {
    "customPlayheadTracker": false
  }
}
```

**What did you do?**

Play the stream

**What did you expect to happen?**
Expected the player to show all audio streams

**What actually happened?**

Player is not showing hindi audio stream so its not playable its only not working on shaka-player the stream works on [hls](https://hlsjs.video-dev.org/)

**Comment by avelad** [comment] 2024-01-08 09:01
Duplicate of https://github.com/shaka-project/shaka-player/issues/5836

**Closed by avelad** 2024-01-08 09:01 UTC
Labels: type: bug
