### ISSUE TITLE
Doesn't play intermittently in Safari.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6749] opened 2024-06-04 14:08 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

4.8.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
 demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
mac safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 100,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "persistentSessionOnlinePlayback": false,
    "persistentSessionsMetadata": [],
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "keySystemsMapping": {},
    "parseInbandPsshEnabled": false,
    "minHdcpVersion": "",
    "ignoreDuplicateInitData": true
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 100,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "raiseFatalErrorOnManifestUpdateRequestFailure": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
      },
      "sequenceMode": false,
      "enableAudioGroups": false,
      "multiTypeVariantsAllowed": true,
      "useStreamOnceInPeriodFlattening": false,
      "updatePeriod": -1
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "defaultAudioCodec": "mp4a.40.2",
      "defaultVideoCodec": "avc1.42E01E",
      "ignoreManifestProgramDateTime": false,
      "ignoreManifestProgramDateTimeForTypes": [],
      "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
      "useSafariBehaviorForLive": true,
      "liveSegmentsDelay": 1.5,
      "sequenceMode": true,
      "ignoreManifestTimestampsInSegmentsMode": false,
      "disableCodecGuessing": false,
      "allowLowLatencyByteRangeOptimization": true
    },
    "mss": {
      "sequenceMode": false,
      "keySystemsBySystemId": {
        "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
      }
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 100,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 5,
    "bufferBehind": 30,
    "evictionGoal": 1,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "gapJumpTimerTime": 0.25,
    "durationBackoff": 1,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": false,
    "useNativeHlsForFairPlay": true,
    "inaccurateManifestTolerance": 0,
    "lowLatencyMode": true,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 0.1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30,
    "parsePrftBox": false,
    "segmentPrefetchLimit": 2,
    "prefetchAudioLanguages": [],
    "disableAudioPrefetch": false,
    "disableTextPrefetch": false,
    "disableVideoPrefetch": false,
    "liveSync": true,
    "liveSyncMaxLatency": 2.5,
    "liveSyncPlaybackRate": 1.1,
    "liveSyncMinLatency": 2,
    "liveSyncMinPlaybackRate": 1,
    "liveSyncPanicMode": false,
    "liveSyncPanicThreshold": 60,
    "allowMediaSourceRecoveries": true,
    "minTimeBetweenRecoveries": 5,
    "vodDynamicPlaybackRate": false,
    "vodDynamicPlaybackRateLowBufferRate": 0.95,
    "vodDynamicPlaybackRateBufferRatio": 0.5,
    "infiniteLiveStreamDuration": false
  },
  "mediaSource": {
    "codecSwitchingStrategy": "smooth",
    "forceTransmux": false,
    "insertFakeEncryptionInInit": true
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": false,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": false,
    "restrictToScreenSize": false,
    "ignoreDevicePixelRatio": false,
    "clearBufferSwitch": false,
    "safeMarginSwitch": 0
  },
  "autoShowText": 3,
  "preferredAudioLanguage": "",
  "preferredAudioLabel": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoHdrLevel": "AUTO",
  "preferredVideoLayout": "",
  "preferredVideoLabel": "",
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferSpatialAudio": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "textDisplayer": {
    "captionsUpdatePeriod": 0.25
  },
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "rtpSafetyFactor": 5,
    "useHeaders": false,
    "includeKeys": []
  },
  "cmsd": {
    "enabled": true,
    "applyMaximumSuggestedBitrate": true,
    "estimatedThroughputWeightRatio": 0.5
  },
  "lcevc": {
    "enabled": false,
    "dynamicPerformanceScaling": true,
    "logLevel": 0,
    "drawLogo": false
  },
  "ads": {
    "customPlayheadTracker": false,
    "skipPlayDetection": false
  }
}
```

**What did you do?**

I played the above m3u8 by setting useNativeHlsOnSafari to false in Mac Safari.

**What did you expect to happen?**
3016 VIDEO_ERROR occurs intermittently. The error does not occur 100% of the time, but occurs intermittently about 50% of the time.

**What actually happened?**

It plays in Chrome, Opera, and Firefox, but there are times when it doesn't play in Safari. What's the reason?

**Are you planning send a PR to fix it?**

**Comment by joeyparrish** [comment] 2024-06-04 21:43
Is there a version that works consistently for you?  If it's a regression, and we know a "good" version, that might help us identify the root of the problem more quickly.

https://index-dot-shaka-player-demo.appspot.com/ has links to prebuilt versions from every branch, if that helps you identify a good version quickly.

**Comment by brodiddev** [comment] 2024-06-05 02:02
4.9.1, 4.7.11 The same 3015 error occurs in both versions.

failed to get Buffered range for video
- InlalidStateError: The object is in an invalid state. 

video:10 - failed fetch and append: code = 3015
unhandled promise rejection: shaka.util.Error

**Comment by brodiddev** [comment] 2024-06-11 04:40
Safari issues still exist :(

**Comment by avelad** [comment] 2024-06-18 14:56
```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

**Comment by brodiddev** [comment] 2024-06-19 04:59
t is as follows:

https://api.sooplive.com/media/live/brodi/master.m3u8

**Comment by avelad** [comment] 2024-06-19 05:41
Duplicate of https://github.com/shaka-project/shaka-player/issues/6850

**Closed by avelad** 2024-06-19 05:41 UTC
Labels: type: bug, component: HLS, browser: Safari
