### ISSUE TITLE
CS ad w/ autoplay restrictions

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#2437] opened 2020-03-03 21:28 UTC
Repro:
Load the [Sintel asset](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled) with a CS ad on the nightly.

It should start with an ad, but it doesn't (I'm using Chrome on Mac, not sure if it matters). The timeline gets colored with ad breaks, so presumably the player knows about the ads.

Not sure if it's a demo problem or an ad logic problem.

**Comment by joeyparrish** [comment] 2020-03-03 21:31
Works for me on Chrome 80 stable on gLinux.  I clicked your link, and the ad played.  Then I reloaded, and the ad played again.

Have you disabled your ad blocker?  :-)

**Comment by joeyparrish** [comment] 2020-03-03 21:32
Also, I'm seeing this revision on the nightly: v2.5.9-master-74-g6d666950 (uncompiled)

We had a problem on our build bot overnight that prevented the nightly from being updated on the normal schedule.  It didn't get properly updated until a couple hours ago.  So please try clearing cache and reloading the nightly one more time to see if it was an outdated version causing the issue.

**Comment by ismena** [comment] 2020-03-03 21:49
Cache cleared, no ad-blocker!

The weird thing is, I remember it working on my Linux machine as well! On my Mac it works when I select the Sintel asset on the page, but not on reload/via direct link. At least we know it's not affecting every user, which is good. :-|

Can you please try on Mac just to see if this IS Mac-related or if my particular Mac doesn't feel like showing ads tonight..?

**Comment by theodab** [comment] 2020-03-03 21:52
I'm reproducing this on the nightly. It only seems to happen when the asset is loaded as the demo starts, as part of the URL parameters.

**Comment by joeyparrish** [comment] 2020-03-03 21:54
Could it be a race condition?  When it reproduces on reload, what happens when you subsequently click "play" under the same asset?

**Comment by theodab** [comment] 2020-03-03 21:58
If you play the asset manually, ads are displayed.
I'm wondering if the UI initializes before the IMA SDK is fully loaded, or something.

**Comment by joeyparrish** [comment] 2020-03-03 22:28
That seems the most likely explanation at this point.

**Comment by theodab** [comment] 2020-03-03 22:31
On further testing, I think this might have to do with autoplay restrictions?
On Chrome, the video autoplays on reload in localhost, and the ads play. On the other hand, the video does not autoplay on reload when run from nightly, and the ads are gone.
On the other hand, in Firefox, the video doesn't autoplay on reload either when run in localhost, or from nightly... and the ads are gone in both cases.
Could it be that IMA SDK is yielding to autoplay restrictions by not reporting the presence of ads, or refusing to play them, or something like that?

**Comment by joeyparrish** [comment] 2020-03-03 22:39
I doubt autoplay has anything to do with it.  It's too inconsistent across devices & platforms.  If you add an arbitrary and longish delay (say, 1-2s) before `player.load()`, I bet the effect goes away in all cases.

**Comment by theodab** [comment] 2020-03-03 23:00
I just tried that, and the ads still don't play in localhost, on Firefox... unless the user presses the screen during that delay, in which point it does work.

Also, there's this error in the console:
> client_side_ad_manager.js:92 There was an ad error from the IMA SDK: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.

So it definitely looks like this is IMA SDK trying to honor the autoplay restrictions.

**Comment by theodab** [comment] 2020-03-03 23:04
If we can recover from this state, we should. Perhaps on getting this specific error, we could try to get ads again after the video starts playing, or something like that? It's weird for the ads to just be gone, but the ad points to still be show up in the seek bar.
Otherwise, if it turns out this is irrecoverable, I guess we can mark this as external.

**Comment by ismena** [comment] 2020-03-04 17:33
Thanks for the investigation! Let me try and see if we can recover.

**Comment by ismena** [comment] 2020-03-04 18:24
Okay, it doesn't look like we can easily recover from this state. 
I tried:
- initiating another ad request immediately after the failed one
- repeating the request after user has initiated playback
- creating a new request with the same ad tag as the failed one and sending it in both of the situation described above

I'll keep this open in case I get other ideas of if the IMA team has guidance on this. For now, I'll make sure the ad markers are removed from the timeline if a request fails and mark this as external.

**Comment by joeyparrish** [comment] 2022-05-24 17:41
We have no control over this, and we don't have a bug link for IMA to track any work on this.  Closing.

**Closed by joeyparrish** 2022-05-24 17:41 UTC
Labels: type: external, component: ads
