### ISSUE TITLE
PTS rollover handling incorrectly applied to DASH and fMP4 HLS

### ISSUE THREAD

**Issue by NoChance777** [shaka-project/shaka-player#2808] opened 2020-08-19 07:19 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.3 (shaka 2.5.x release is working without the issue)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
I have used the demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome/MacOS 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Have been sent by email

**What did you do?**
Start playing DASH stream with embedded WebVTT subtitles

**What did you expect to happen?**
subtitles should be displayed

**What actually happened?**
With DASH or HLS with MPEG-TS, the maximum PTS is 2^33 = 8589934592 . There are packager on the market (eg. Harmonic), which are messing up this rollover within the vtt files. There are always several .vtt files arriving with values above 8589934592, before the rollover is working. This is a bug on a packager side, and I guess you are trying to work around this bug. We are doing the same in our packager code, but only for MPEGTS input.
With DASH or HLS with fMP4 (that’s what we are using), this limit does not exist, but the rollover code is still applied.

[Commit that brings this bug](https://github.com/google/shaka-player/commit/1ada5e75748a2fe72b40e060fd6eacfb2129b748)
[W3 docs](https://www.w3.org/2013/12/byte-stream-format-registry/mp2t-byte-stream-format.html#mpeg2ts-discontinuities)

**Comment by TheModMaker** [comment] 2020-10-27 19:25
The problem is that TS segments will always have a small timestamp due to the rollover problem.  To fix this, we adjust the WebVTT timestamps backward so they appear at the same time relative to the TS segment.  You can also have both TS and MP4 in the same manifest (though we won't switch between them).  This can complicate where the segments and text samples should be put.

What we should be doing is adjusting the TS segments forward so they appear at the correct time even though their timestamps aren't big enough to hold the correct time.  So if a TS segment says it should be at 4 seconds, we may need to add the rollover so it appears after the previous rollover.  We can use the WebVTT timestamps to find where to adjust the first segments.

I also wonder if we handle mid-stream rollovers correctly.  So if we have a segment with a large timestamp and the next segment has a small one, will it work.  The browser is supposed to handle this while playing, but this can complicate seeking.

**Comment by TheModMaker** [comment] 2021-04-19 17:25
I had intended to fix this for v3.1, thinking I could just revert that change and it would work out.  But unfortunately, we no longer parse segment times for WebVTT, so reverting that change wouldn't do what I wanted.  This means that there is no simple fix for this issue and we'd need to do the "full" fix for handling TS timestamps.

Since this change would be a large change and might introduce subtle bugs, we're going to wait until v3.2 to make this change.  We may be able to put this in a v3.1.x bugfix release, depending on how clean the fix is.

**Comment by avelad** [comment] 2022-05-17 11:50
I don't know if this is resolved with the latest changes in HLS, @joeyparrish , can you check it?

**Comment by joeyparrish** [comment] 2022-05-17 20:55
I believe this is resolved now since #4217.

**Closed by joeyparrish** 2022-05-17 20:55 UTC
Labels: type: bug, component: HLS, priority: P1
