### ISSUE TITLE
LG WebOS Shaka player is throwing 6006 error code while playing the content when internet connection is not available

### ISSUE THREAD

**Issue by cbpanchal** [shaka-project/shaka-player#5106] opened 2023-03-21 11:01 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, but did not found any relevant issue

**What version of Shaka Player are you using?**
4.2.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
our own custom app

**If custom app, can you reproduce the issue using our demo app?**
did not checked because, our own custom app is using the reference of demo app

**What browser and OS are you using?**
Chrome and LG WebOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG WebOS

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

We are blocking the TV from the internet access, as the TV is on the same server environment in which our movie contents and widevine DRM licence is exist, and connected with the same network IP

**What did you expect to happen?**
Shaka player should work without internet if all the contents are available in the same network and DRM licence as well

**What actually happened?**

It's not working as expected, shaka player throwing 6006 error code 

So here in sort my question is does shaka plater requires an internet connection to play the content if the all movie contents are deployed in the same network IP?

**Comment by cbpanchal** [comment] 2023-03-27 05:25
@joeyparrish  can you please check this and give a direction

**Comment by joeyparrish** [comment] 2023-03-27 16:38
[Error 6006 is `FAILED_TO_GENERATE_LICENSE_REQUEST`](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006):

> The CDM was unable to generate a license request for the init data it was given. The init data may be malformed or in an unsupported format.
> * error.data[0] is an error message string from the browser.
> * error.data[1] is the error object from the browser.
> * error.data[2] is a string with the extended error code, if available.

This is out of the player's (JS) control.  The CDM failed to generate a license request.  That happened in C++ inside the platform, probably in Widevine CDM code (though it could also be in the browser's code).  I see no reason it should fail without an internet connection at that level, since the CDM is not supposed to directly communicate with any server outside the control of the application (JS).

Please file a support request against either [Widevine](https://widevine.com) or LG or both.

**Comment by cbpanchal** [comment] 2023-03-29 07:12
@joeyparrish Thanks for the response, could you please explain more about it `Widevine CDM code (though it could also be in the browser's code)`
and how actually licence generate process is happening from `shaka → widewine → LG WebOS`

Thanks

**Comment by cbpanchal** [comment] 2023-03-29 09:43
@joeyparrish  Also sometimes the different behaviour we have seen that the licence network call is not made by shaka player even though it's called fro the JS, but we are able to see our server mpd movie calls in the network tab but not widevine licence, and movie is not playing at all, this is happening when we block the TV from the internet

Can you please help in that scenario as well, Thanks

**Comment by joeyparrish** [comment] 2023-03-29 17:42
1. Shaka (JS) sets up `MediaKeys` (EME API object).  `MediaKeys` is implemented in C++ in the browser, and talks to the Widevine CDM, which is a separate C++ component.
2. Shaka calls `mediaKeys.createSession()` to get a `MediaKeySession` object
3. Shaka calls [`session.generateRequest()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession/generateRequest). The browser delegates the generateRequest call to the CDM, which generates a license request.
4. The request message is sent back through the browser to JavaScript (Shaka) via a [`message` event](https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession/message_event).
5. Shaka Player then sends the contents of that message event to the configured license server.
6. If the server returns a successful license response, Shaka calls [`session.update()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession/update) with the license response.  The browser delegates that response down to the CDM.  The CDM may accept or reject this response.  If accepted, the CDM has the decryption keys for the content.

If creating `MediaKeys` fails (step 1), you get [Shaka error 6002 (`FAILED_TO_CREATE_CDM`)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6002).

If the call to `createSession()` fails (step 2), you get [Shaka error 6005 (`FAILED_TO_CREATE_SESSION`)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6005).

If the call to `generateRequest()` fails (step 3), you get [Shaka error 6006 (`FAILED_TO_GENERATE_LICENSE_REQUEST`)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006).

If the call to `generateRequest()` succeeds, but the message event never arrives (step 4), Shaka doesn't do anything.  (This shouldn't happen, and would indicate a bug in the browser or CDM.)

If the license server rejects the request (step 5), you get [Shaka error 6007 (`LICENSE_REQUEST_FAILED`)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6007).

If the call to `update()` fails (step 6), you get [Shaka error 6008 (`LICENSE_RESPONSE_REJECTED`)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6008).

If you don't get any errors, you can add logs to drm_engine.js around these API calls, to see which steps are completing and which are hung.  This could help you figure out what information you need to provide to LG and/or Widevine in a bug report.

I hope this helps!

**Comment by cbpanchal** [comment] 2023-03-30 07:10
Hi @joeyparrish  Thanks for the detailed information, may i know how to add the logs? or listen the event listeners for the above mentioned steps by you, in our code we are using a `"shaka-player": "^4.2.3", ` as a node module in our app

Also the set log level is not working by set it by `shaka.log.setLevel(shaka.log.Level.DEBUG`) it says method not found  `shaka.log`

Can you please help me with the above questions, it would be really helpful for me to triage and fix this issue

here is the code snippet for shaka initialization 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/20139279/228757275-53e95351-1318-4c0b-93f5-83448d403fdb.png">

Thanks

**Comment by cbpanchal** [comment] 2023-03-31 18:13
@joeyparrish  I managed to work with shaka player debug library and able to set the log level as DEBUG and tried to reproduce the scenario, below are the captured console logs, could you please check if you are able to see what is happening here, it will help me to understand and redirect further 

Thanks

2.174b8114.chunk.js:2 ARIAMixin interface not detected. Installing polyfill.
2.174b8114.chunk.js:2 MediaSource.install
2.174b8114.chunk.js:2 Using native MSE as-is.
2.174b8114.chunk.js:2 Patching vp09 support queries.
2.174b8114.chunk.js:2 randomUUID.install
2.174b8114.chunk.js:2 Symbol.install
2.174b8114.chunk.js:2 VideoPlayPromise.install
2.174b8114.chunk.js:2 Using native VTTCue.
2.174b8114.chunk.js:2 MediaCapabilities: install
2.174b8114.chunk.js:2 EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
2.174b8114.chunk.js:2 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
2.174b8114.chunk.js:2 Starting unload...
2.174b8114.chunk.js:2 EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
2.174b8114.chunk.js:2 Starting attach...
2.174b8114.chunk.js:2 EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
2.174b8114.chunk.js:2 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
2.174b8114.chunk.js:2 EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support. 
2.174b8114.chunk.js:2 Starting load of https://ourmoviecontent.mpd...
2.174b8114.chunk.js:2 No Period ID given for Period with start time 0,  Assigning a default
2.174b8114.chunk.js:2 Found variant with audio and video content, so filtering out audio-only content.
52.174b8114.chunk.js:2 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior in the future, potentially including failure to play.
52.174b8114.chunk.js:2 navigator.requestMediaKeySystemAccess failed.
22.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Native encryptionScheme support found.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
22.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Native encryptionScheme support found.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
22.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Native encryptionScheme support found.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
22.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Native encryptionScheme support found.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
22.174b8114.chunk.js:2 McEncryptionSchemePolyfill: Native encryptionScheme support found.
2.174b8114.chunk.js:2 McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support.
2.174b8114.chunk.js:2 MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"video/mp4; codecs=\"avc1.4D401F\"","width":426,"height":240,"bitrate":562029,"framerate":23.976023976023978},"audio":{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":134718,"samplerate":48000,"spatialRendering":false},"keySystemConfiguration":{"keySystem":"com.adobe.primetime","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"audio":{},"video":{}}} DOMException: Unsupported keySystem
2.174b8114.chunk.js:2 MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"video/mp4; codecs=\"avc1.4D401F\"","width":640,"height":360,"bitrate":903749,"framerate":23.976023976023978},"audio":{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":134718,"samplerate":48000,"spatialRendering":false},"keySystemConfiguration":{"keySystem":"com.adobe.primetime","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"audio":{},"video":{}}} DOMException: Unsupported keySystem
2.174b8114.chunk.js:2 MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"video/mp4; codecs=\"avc1.4D401F\"","width":854,"height":480,"bitrate":1557849,"framerate":23.976023976023978},"audio":{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":134718,"samplerate":48000,"spatialRendering":false},"keySystemConfiguration":{"keySystem":"com.adobe.primetime","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"audio":{},"video":{}}} DOMException: Unsupported keySystem
2.174b8114.chunk.js:2 MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"video/mp4; codecs=\"avc1.4D401F\"","width":1280,"height":720,"bitrate":2004560,"framerate":23.976023976023978},"audio":{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":134718,"samplerate":48000,"spatialRendering":false},"keySystemConfiguration":{"keySystem":"com.adobe.primetime","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"audio":{},"video":{}}} DOMException: Unsupported keySystem
2.174b8114.chunk.js:2 MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"video/mp4; codecs=\"avc1.4D401F\"","width":1280,"height":720,"bitrate":3027933,"framerate":23.976023976023978},"audio":{"contentType":"audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":134718,"samplerate":48000,"spatialRendering":false},"keySystemConfiguration":{"keySystem":"com.adobe.primetime","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"audio":{},"video":{}}} DOMException: Unsupported keySystem
2.174b8114.chunk.js:2 Created MediaKeys object for key system com.widevine.alpha
2.174b8114.chunk.js:2 Creating new temporary session
2.174b8114.chunk.js:2 Already got the variants' decodingInfo.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 Ignoring duplicate init data.
2.174b8114.chunk.js:2 codecs avc-aac avg bandwidth 2650964.5
2.174b8114.chunk.js:2 No exact match for variant role could be found.

main.3df3c72c.chunk.js:1 ShakaPlayer.error bubbles: falsecancelable: falsecurrentTarget: shaka.PlayerdefaultPrevented: falsedetail: shaka.util.ErrorisTrusted: falsestopped: falsetarget: shaka.PlayertimeStamp: 118063.51500000001type: "error"__proto__: Object(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2onError @ 2.174b8114.chunk.js:2onError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2

main.3df3c72c.chunk.js:1 ShakaPlayer.error Error: Widevine DRM not initialized on the TV(…)Nt @ main.3df3c72c.chunk.js:1(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2onError @ 2.174b8114.chunk.js:2onError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2

**main.3df3c72c.chunk.js:1 ShakaPlayer.error Error: Shakaplayer closed{"severity":2,"category":6,"code":6006,"data":["Unfulfilled promise rejected automatically during destruction.",{},null],"handled":false,"message":"Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Unfulfilled promise rejected automatically during** 

destruction.,InvalidStateError: Unfulfilled promise rejected automatically during destruction.,)","stack":"Error: Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Unfulfilled promise rejected automatically during destruction.,InvalidStateError: Unfulfilled promise rejected automatically during destruction.,)\n    at new shaka.util.Error (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:97307)\n    at http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:240636\n    at <anonymous>"}(…)Nt @ main.3df3c72c.chunk.js:1(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2onError @ 2.174b8114.chunk.js:2onError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2
hcap_1_23_2.js:45 command_id = 146 added, {"command_id" : "146", "onFailure" : {/*function*/}, "onSuccess" : {/*function*/}, "param_text" : "{"command_id":"146","command":"get_power_mode"}"}
main.3df3c72c.chunk.js:1 ShakaPlayer.error bubbles: falsecancelable: falsecurrentTarget: shaka.PlayerabrManagerFactory_: ()abrManager_: shaka.abr.SimpleAbrManageradManager_: shaka.ads.AdManagerassetUri_: nullattachEventManager_: shaka.util.EventManagerattachNode_: ObjectbufferObserver_: nullbufferPoller_: nullcheckVariantsTimer_: shaka.util.TimercleanupOnUnload_: Array[0]cmcdManager_: shaka.util.CmcdManagerconfig_: ObjectcurrentAdaptationSetCriteria_: shaka.media.PreferenceBasedCriteriacurrentTextForced_: falsecurrentTextLanguage_: ""currentTextRole_: ""detachNode_: ObjectdispatchTarget: shaka.PlayerdrmEngine_: nulldrmNode_: ObjectfullyLoaded_: falseglobalEventManager_: shaka.util.EventManagerisTextVisible_: falselastTextFactory_: ()lcevcCanvas_: nulllcevcDil_: nulllisteners_: shaka.util.MultiMaploadEventManager_: shaka.util.EventManagerloadMode_: 1loadNode_: ObjectmanifestNode_: Objectmanifest_: nullmaxHwRes_: ObjectmediaSourceEngine_: shaka.media.MediaSourceEnginemediaSourceNode_: ObjectnetworkingEngine_: shaka.net.NetworkingEnginenextExternalStreamId_: 1000000000parserFactory_: nullparserNode_: Objectparser_: nullplayRateController_: nullplayheadObservers_: nullplayhead_: nullqualityObserver_: nullregionTimeline_: nullsrcEqualsDrmNode_: ObjectsrcEqualsNode_: Objectstats_: shaka.util.StatsstreamingEngine_: nullunloadNode_: ObjectupdatedStartTime_: nullvideoContainer_: nullvideo_: video.shakaplayerwalker_: shaka.routing.Walker__proto__: shaka.util.FakeEventTargetdefaultPrevented: falsedetail: shaka.util.ErrorisTrusted: falsestopped: falsetarget: shaka.PlayertimeStamp: 118731.86000000002type: "error"__proto__: Object(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2shaka.Player.onVideoError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2
main.3df3c72c.chunk.js:1 ShakaPlayer.error Error: {"severity":2,"category":3,"code":3016,"data":[4,null,null],"handled":false,"message":"Shaka Error MEDIA.VIDEO_ERROR (4,,)","stack":"Error: Shaka Error 
MEDIA.VIDEO_ERROR (4,,)\n    at new shaka.util.Error 
(http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:97307)\n    at shaka.Player.videoErrorToShakaError_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:540820)\n    at shaka.Player.onVideoError_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:541031)\n    at HTMLVideoElement.<anonymous> (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:470817)"}(…)Nt @ main.3df3c72c.chunk.js:1(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2shaka.Player.onVideoError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2

main.3df3c72c.chunk.js:1 ShakaPlayer.error Error: Shakaplayer closed{"severity":2,"category":3,"code":3016,"data":[4,null,null],"handled":false,"message":"Shaka Error MEDIA.VIDEO_ERROR (4,,)","stack":"Error: Shaka Error MEDIA.VIDEO_ERROR (4,,)\n    at new shaka.util.Error (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:97307)\n    at shaka.Player.videoErrorToShakaError_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:540820)\n    at shaka.Player.onVideoError_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:541031)\n    at HTMLVideoElement.<anonymous> (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:470817)"}(…)Nt @ main.3df3c72c.chunk.js:1(anonymous function) @ main.3df3c72c.chunk.js:1shaka.util.FakeEventTarget.dispatchEvent @ 2.174b8114.chunk.js:2shaka.Player.onError_ @ 2.174b8114.chunk.js:2shaka.Player.onVideoError_ @ 2.174b8114.chunk.js:2(anonymous function) @ 2.174b8114.chunk.js:2
hcap_1_23_2.js:45 command_id = 146 received, {"command" : "get_power_mode", "command_id" : "146", "mode" : 1, "result" : true}
2.174b8114.chunk.js:2 The walker saw an error:

2.174b8114.chunk.js:2 Error Message: Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.

2.174b8114.chunk.js:2 Error Stack: Error: Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.
    at $jscomp.generator.Engine_.program_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:324257)
    at $jscomp.generator.Engine_.nextStep_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:42511)
    at $jscomp.generator.Engine_.next_ (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:41475)
    at $jscomp.generator.Generator_.next (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:42956)
    at t (http://127.0.0.1:8051/as/app/1/1///static/js/2.174b8114.chunk.js:2:43375)
    at <anonymous>
22.174b8114.chunk.js:2 Starting unload...

**Comment by cbpanchal** [comment] 2023-04-03 05:45
@joeyparrish  Can someone check my above comments

**Comment by cbpanchal** [comment] 2023-04-05 12:30
Hi @joeyparrish just wanted to know, if someone can check this on your behalf

**Comment by cbpanchal** [comment] 2023-04-07 13:07
@joeyparrish  hello some one can please check my analysis and logs https://github.com/shaka-project/shaka-player/issues/5106#issuecomment-1492403012 here if you can find anything

**Comment by cbpanchal** [comment] 2023-04-18 11:33
@joeyparrish  this is very long pending issue for me, can you pleas review it once
Thanks!

**Comment by subhanahmed047** [comment] 2023-08-22 07:12
what version of the LG WebOS have you tested this on? I can confirm that I see the same error (`FAILED_TO_GENERATE_LICENSE_REQUEST`) when trying to play Widevine DRM content. 

I've tested on a webOS 3.5 (2017). 
You can reproduce the issue by using the following Widevine manifest:

manifest: https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd
license Uri: https://cwip-shaka-proxy.appspot.com/no_auth

here is the metadata that I pass into the generateRequest function.

![Meta Data](https://i.imgur.com/djXlFQ6.png)


and here is the error response I get:

![Error](https://i.imgur.com/kfc44NS.png)

Happy to provide more information.

**Comment by avelad** [comment] 2024-04-10 10:12
Since we still do not officially support WebOS and it is only community supported, I am seeing that it is a WebOS and external problem, so I am closing the issue.

**Closed by avelad** 2024-04-10 10:12 UTC
Labels: type: external, platform: WebOS
