### ISSUE TITLE
HLS fmp4 (byte range requests) seeking not working in iOS

### ISSUE THREAD

**Issue by Benny739** [shaka-project/shaka-player#4152] opened 2022-04-25 19:57 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3.3

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
not tried

**Are you using the demo app or your own custom app?**
codepen

**What browser and OS are you using?**
iOS 15.4 iPhone 13 Pro (xCode simulator)

**What did you do?**
Seek on iOS Safari

**What did you expect to happen?**
Seeking works

**What actually happened?**
Video hangs and playback is not possible 

Codepens to reproduce:
Seeking not working with shaka:
https://codepen.io/benny739/pen/BaJgadL

Seeking working with safari native hls playback:
https://codepen.io/benny739/pen/yLpdyZm

It's the same stream for both codepens.
The seeking works everywhere except in iOS. Without seeking the video plays through fine.

**Comment by avelad** [comment] 2022-05-17 11:47
Maybe related to https://github.com/shaka-project/shaka-player/issues/3367

**Comment by theodab** [comment] 2022-05-17 18:45
I tried this out on both a real iPhone SE running 15.4.1, and the same iPhone 13 Pro simulator running iOS 15.4 you mentioned testing it on.

In both, seeking seemed to work fine. I tried both seeking with the scrubber, and seeking with the console, and it was able to keep playing after both.

I did notice that if I seeked into the last ~10 seconds of the presentation it would sometimes not play from that point, but seeking out would make it play again. That also happens on non-iOS Safari, though, so I doubt that's what you were talking about.

The iPhone simulator is a simulator, not an emulator; that is to say, it does not run a full copy of iOS on your computer, but instead implements the outward APIs of iOS using their OSX equivalents. If you are seeing a problem on the iOS simulator, it's possible the actual problem might be related to the computer the simulator is running on, instead. Have you tried this on a real iPhone?

**Comment by theodab** [comment] 2022-05-17 19:08
I tested some more, and I have been able to get it to hang.

I think Alvaro might be right that this is a duplicate of #3367. This issue doesn't specify, but I've only been able to make the player in the codepen hang by making unbuffered seeks via the scrubber, which is what the problem was in that issue. I still haven't reproduced by seeking in the console.

**Comment by joeyparrish** [comment] 2022-05-17 20:01
It doesn't seem to be specific to byte-range requests, so let's close this as a duplicate.  @Benny739, please subscribe to #3367 for updates.

**Comment by joeyparrish** [comment] 2022-05-17 20:01
Duplicate of #3367.

**Closed by joeyparrish** 2022-05-17 20:01 UTC
Labels: type: bug, priority: P1, platform: iOS
