### ISSUE TITLE
Depending on the network speed, requests to the license server are sent or not (race condition?)

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#5176] opened 2023-04-25 09:52 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest version

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
OS : Linux Ubuntu 22.04
Browsers : Firefox 112.0.1 (64-bit) & Chrome 112.0.5615.165 (Official Build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest URI : https://dpk3dq0d69joz.cloudfront.net/origin/HLS_140672_0-VO-cenc.ism/stream.mpd

License server URI : https://widevine-dash.ezdrm.com/proxy?pX=BA5EDC&username=artevodpreprod_s-oualid%40artefrance.fr&contentId=HLS_140672_0-VO&playerName=artevod-web-player&playerVersion=3.0.3&deviceId=02988f87bdf02813242192d49ff3646e&requestUuid=c91783f8-d1ba-4eab-993c-4fccc948e34a

Demo app link : https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dpk3dq0d69joz.cloudfront.net/origin/HLS_140672_0-VO-cenc.ism/stream.mpd;license=https://widevine-dash.ezdrm.com/proxy?pX=BA5EDC&username=artevodpreprod_s-oualid%40artefrance.fr&contentId=HLS_140672_0-VO&playerName=artevod-web-player&playerVersion=3.0.3&deviceId=02988f87bdf02813242192d49ff3646e&requestUuid=c91783f8-d1ba-4eab-993c-4fccc948e34a;panel=CUSTOM%20CONTENT;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```json
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {
      "com.widevine.alpha": "https://widevine-dash.ezdrm.com/proxy?pX=BA5EDC&username=artevodpreprod_s-oualid%40artefrance.fr&contentId=HLS_140672_0-VO&playerName=artevod-web-player&playerVersion=3.0.3&deviceId=02988f87bdf02813242192d49ff3646e&requestUuid=c91783f8-d1ba-4eab-993c-4fccc948e34a"
    },
    "clearKeys": {},
    "advanced": {
      "com.widevine.alpha": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "",
        "audioRobustness": "",
        "sessionType": "",
        "serverCertificate": {},
        "serverCertificateUri": "",
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "keySystemsMapping": {},
    "parseInbandPsshEnabled": false
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "dash": {
      "clockSyncUri": "https://shaka-player-demo.appspot.com/time.txt",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
      },
      "sequenceMode": false
    },
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "durationBackoff": 1,
    "forceTransmux": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30,
    "parsePrftBox": false
  },
  "mediaSource": {
    "sourceBufferExtraFeatures": ""
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": false,
    "restrictToScreenSize": false,
    "ignoreDevicePixelRatio": false
  },
  "autoShowText": 3,
  "preferredAudioLanguage": "en-US",
  "preferredTextLanguage": "en-US",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "useHeaders": false
  },
  "lcevc": {
    "enabled": false,
    "dynamicPerformanceScaling": true,
    "logLevel": 0,
    "drawLogo": false
  }
}
```

**DASH manifest file contents**
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Unified Streaming Platform (version=1.10.12-18737) -->
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  type="static"
  mediaPresentationDuration="PT56M0.085333S"
  maxSegmentDuration="PT3S"
  minBufferTime="PT10S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period
    id="1"
    duration="PT56M0.085333S">
    <BaseURL>dash/</BaseURL>
    <AdaptationSet
      id="1"
      group="1"
      contentType="audio"
      minBandwidth="64001"
      maxBandwidth="192000"
      segmentAlignment="true"
      audioSamplingRate="48000"
      mimeType="audio/mp4"
      codecs="mp4a.40.2"
      startWithSAP="1">
      <AudioChannelConfiguration
        schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
        value="2">
      </AudioChannelConfiguration>
      <!-- Common Encryption -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        xmlns:cenc="urn:mpeg:cenc:2013"
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="81CC8C2D-CA57-452C-A3A4-DD35BF2430D7">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate
        timescale="48000"
        initialization="HLS_140672_0-VO-cenc-$RepresentationID$.dash"
        media="HLS_140672_0-VO-cenc-$RepresentationID$-$Time$.dash">
        <SegmentTimeline>
          <!-- Some long data -->
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="audio=64001"
        bandwidth="64001">
      </Representation>
      <Representation
        id="audio=128000"
        bandwidth="128000">
      </Representation>
      <Representation
        id="audio=192000"
        bandwidth="192000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="292000"
      maxBandwidth="1173000"
      maxWidth="854"
      maxHeight="480"
      segmentAlignment="true"
      mimeType="video/mp4"
      startWithSAP="1">
      <!-- Common Encryption -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        xmlns:cenc="urn:mpeg:cenc:2013"
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="F5C0B65F-2C0C-4963-85CE-3A417481EEF0">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate
        timescale="12800"
        initialization="HLS_140672_0-VO-cenc-$RepresentationID$.dash"
        media="HLS_140672_0-VO-cenc-$RepresentationID$-$Time$.dash">
        <SegmentTimeline>
          <S t="0" d="38400" r="1119" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=292000"
        bandwidth="292000"
        width="426"
        height="240"
        sar="640:639"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=586000"
        bandwidth="586000"
        width="640"
        height="360"
        sar="1:1"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1173000"
        bandwidth="1173000"
        width="854"
        height="480"
        sar="1280:1281"
        codecs="avc1.640028"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="3"
      group="2"
      contentType="video"
      par="16:9"
      segmentAlignment="true"
      width="1280"
      height="720"
      sar="1:1"
      mimeType="video/mp4"
      codecs="avc1.640028"
      startWithSAP="1">
      <!-- Common Encryption -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        xmlns:cenc="urn:mpeg:cenc:2013"
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="9F0F8E01-2ED6-4451-AD3F-39E04AF463B1">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
      </ContentProtection>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate
        timescale="12800"
        initialization="HLS_140672_0-VO-cenc-$RepresentationID$.dash"
        media="HLS_140672_0-VO-cenc-$RepresentationID$-$Time$.dash">
        <SegmentTimeline>
          <S t="0" d="38400" r="1119" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=2350000"
        bandwidth="2350000"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**What did you do?**
Play the video in the shaka player demo app, and open the settings menu to list the available resolutions.

**What did you expect to happen?**
The available resolutions (apart from `auto`) should be :
- 720p
- 480p
- 360p
- 240p

This is what I correctly observe in Firefox:
![Screenshot from 2023-04-25 11-12-05](https://user-images.githubusercontent.com/3329077/234238575-fed5eff1-2bd0-464f-b737-92fd065e0049.png)

**What actually happened?**
In Chrome, only the "HD" resolution (720p) is displayed:
![Screenshot from 2023-04-25 11-12-22](https://user-images.githubusercontent.com/3329077/234238790-94528873-2f7d-42ec-b6ea-95d3215e2eed.png)

In both browsers, the `com.widevine.alpha` key system is used.

It looks like in Chrome, only one AdaptationSet is loaded, this one :
```xml
    <AdaptationSet
      id="3"
      group="2"
      contentType="video"
      par="16:9"
      segmentAlignment="true"
      width="1280"
      height="720"
      sar="1:1"
      mimeType="video/mp4"
      codecs="avc1.640028"
      startWithSAP="1">
```
... and the other one containing the lower 480p, 360p & 240p resolutions simply gets discarded 🤔 ...

It looks like a bug in shaka player to me, so your help is welcome!
Thanks!

**Comment by joeyparrish** [comment] 2023-04-25 23:25
The player reports that some DRM keys are missing which it believes are required for those other variants.

**Comment by joeyparrish** [comment] 2023-04-25 23:37
If you run the demo app and open the JS debugger, you can get a handle to the player with:

```js
player = video.ui.getControls().getLocalPlayer()
```

Here's a nasty list expression that gives you a nice readable version of what keys the player thinks is required for each resolution:

```js
Array.from(new Set(player.getManifest().variants.map(
    v => v.video.height + ': ' + Array.from(v.drmInfos[0].keyIds).sort().join(", ")))).sort()
```

On Chrome, I get this:

``` 
240: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
360: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
480: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
720: 81cc8c2dca57452ca3a4dd35bf2430d7, 9f0f8e012ed64451ad3f39e04af463b1
```

Here's an expression for map of the keys we actually have:

```js
player.drmEngine_.keyStatusByKeyId_
```

Which in Chrome are:

```
Map(2) {'9f0f8e012ed64451ad3f39e04af463b1' => 'usable', '81cc8c2dca57452ca3a4dd35bf2430d7' => 'usable'}
```

This explains why some variants are not used in Chrome.  We don't have the necessary keys to decrypt them.

One of two things must be happening:
1. On Firefox, we get different keys
2. On Firefox, we see different key requirements for those variants

-----

### Can you please try those snippets in the debugger on Firefox and let us know which is the case?

-----

If you're getting different keys in Chrome vs Firefox, then you need to fix your license server or license proxy.  If a third party provides that service, please contact them.

If you get the same keys on both browsers, but the player determines that the requirements for the variants are different, we have two more possibilities:

1. The server serves a different manifest to each browser
2. The player reads the same manifest differently on two different browsers

If the server is serving different manifests, then that would be resolved in your server.  This seems very unlikely, though.

If the player reads the same manifest differently in the two browsers, that would be a player bug.  This also seems a little unlikely to me, but it's possible.

**Comment by loicraux** [comment] 2023-04-26 10:06
Thanks for the detailed debugging tips @joeyparrish ! 

On Firefox, I get the following :

Map of required keys for each variant (this is the same as in Chrome) :
```
240: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
360: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
480: 81cc8c2dca57452ca3a4dd35bf2430d7, f5c0b65f2c0c496385ce3a417481eef0
720: 81cc8c2dca57452ca3a4dd35bf2430d7, 9f0f8e012ed64451ad3f39e04af463b1
```
=> We get the same keys on both browsers.

The map of usable keys (`player.drmEngine_.keyStatusByKeyId_`) : 
```
Map(3) { f5c0b65f2c0c496385ce3a417481eef0 → "usable", 81cc8c2dca57452ca3a4dd35bf2430d7 → "usable", 9f0f8e012ed64451ad3f39e04af463b1 → "usable" }
```
As we can see, the f5c0b65f2c0c496385ce3a417481eef0 key for lower resolutions video streams is considered usable on Firefox. So somehow the player determines that the requirements for the variants are different...

I've compared the manifest files served to Chrome and Firefox, they are strictly the same.

**Comment by loicraux** [comment] 2023-04-26 12:48
I just observed something very interesting :

If I turn on network throttling in Chrome DevTools (set to 'Fast 3G'), ... I get all the resolutions in Chrome :

![image](https://user-images.githubusercontent.com/3329077/234579515-8272f30b-3f71-45ef-bb53-6e99e52a1de0.png)

**Comment by loicraux** [comment] 2023-05-09 07:38
I can still reproduce the problem in Chrome today with the latest version of Shaka Player, can someone please take a look? Thanks !

**Comment by loicraux** [comment] 2023-09-08 08:33
Hi !

I've reproduced both issues with the original demo app link given in this issue description :

- In Chrome only the 720p resolution is listed, whereas in Firefox (both are using Widevine), all the resolutions 720p, 480p, 360p & 240p are listed

- If I turn on Network Throttling in Chrome DevTools (set to Slow or Fast 3G), then all the resolutions are listed in Chrome.

Idk if both issues are indeed the same...

**Comment by joeyparrish** [comment] 2023-09-08 15:26
It definitely sounds like a race to me.  I'm not sure where it could be, but I'll take a look.

**Comment by avelad** [comment] 2024-01-15 10:52
Can you check if the error still occurs in version 4.7.4? Thank you!

**Comment by loicraux** [comment] 2024-01-23 13:28
> Can you check if the error still occurs in version 4.7.4? Thank you!

I just reproduced the issue using latest version of shaka player 4.7.6 in the shaka player demo page :

Manifest URL is : https://dpk3dq0d69joz.cloudfront.net/origin/HLS_140672_0-VO-cenc.ism/stream.mpd

Custom License Server URL is :
https://widevine-dash.ezdrm.com/proxy?username=artevodpreprod_v-chagny%40artefrance.fr&contentId=HLS_140672_0-VO&playerName=artevod-web-player&playerVersion=4.2.1&deviceId=0041be4e0d87a5db3a734634ba9b9586&requestUuid=ea3016d2-17f8-4105-a93a-ec89839f9cf3&pX=BA5EDC

**What did you do?**
Play the video in the shaka player demo app, and open the settings menu to list the available resolutions.

**What did you expect to happen?**
The available resolutions (apart from auto) should be :

720p
480p
360p
240p

**What actually happened?**
- In Firefox, it works OK.
- In Chrome, only the "HD" resolution (720p) is displayed. If I switch to _Slow 3G_ in Network Throtlling mode in Chrome DevTools, then all the resolutions are correctly shown in Chrome.

@shaka-bot reopen

**Comment by avelad** [comment] 2024-01-23 13:41
@loicraux  I can reproduce the error in version 4.7.6 and in nightly, but not in my local using the main branch, it is strange, I will investigate the problem further.

**Comment by avelad** [comment] 2024-01-23 14:08
I have found the error, the problem is that its manifest does not include pssh information, so we have to wait for the browser's encrypted event. This means that if we have no restrictions, the highest quality is chosen, then we only have the initialization segment (pssh info) of the audio and the 720p quality in Chrome. In Firefox we do not have the Network Information API so we start at a lower quality but quickly jump to 720p, which causes 3 sessions to be created in the DRM and we obtain the 3 keys, but in Chrome we only obtain 2.

**Comment by avelad** [comment] 2024-01-23 14:09
A possible solution is to identify that the manifest does not have pssh information and in that case always wait to obtain a key before indicating that a quality is not compatible. See https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L6541

**Comment by loicraux** [comment] 2024-01-23 14:19
> A possible solution is to identify that the manifest does not have pssh information and in that case always wait to obtain a key before indicating that a quality is not compatible. See https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L6541

Thanks for analyzing the problem and determining its cause!
So, to be clear, this is a fix to be applied to Shaka Player?

**Comment by avelad** [comment] 2024-01-23 14:21
I have to create a PR to fix it, but yes.

**Closed** 2024-01-23 18:49 UTC
Labels: type: bug, priority: P1, browser: Chrome, component: Widevine
