### ISSUE TITLE
Integration test failures on browsers without h264 and aac

### ISSUE THREAD

**Issue by JakubRimal** [shaka-project/shaka-player#2865] opened 2020-09-22 09:42 UTC
_(Originally discussed in https://github.com/google/shaka-player/pull/2849)_

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
n/a

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID:    Fedora
Description:    Fedora release 32 (Thirty Two)
Release:    32
Codename:    ThirtyTwo

Chromium 85.0.4183.102 Fedora Project

Mozilla Firefox 80.0.1

Python 3.8.5

**What did you do?**

run `./build/test.py`

**What did you expect to happen?**
test will pass

**What actually happened?**
test fails with the following output:

```
[WARNING] Using default browsers: ['Chrome', 'Firefox']
[INFO] Generating Closure dependencies...
[INFO] Compiling the library (ui, release)...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Running test (1 / 1, 0 failed so far)...
Chrome 85.0.4183.83 (Fedora 0.0.0) CastUtils serialize/deserialize TimeRanges deserialize into equivalent objects FAILED
    Error: Failed: Type negotiation should happen before MediaSourceEngine.init!
        at <Jasmine>
        at Function.jasmineAssert (test/test/boot.js:38:7 <- test/test/boot.js:41:7)
        at _loop (lib/media/media_source_engine.js:296:20 <- lib/media/media_source_engine.js:7145:32)
        at _class._callee2$ (lib/media/media_source_engine.js:294:53 <- lib/media/media_source_engine.js:7197:19)
        at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
    NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.42c01e"') is unsupported.
    error properties: Object({ INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25, code: 9 })
    Error: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.42c01e"') is unsupported.
        at _loop (lib/media/media_source_engine.js:311:48 <- lib/media/media_source_engine.js:7168:85)
        at _class._callee2$ (lib/media/media_source_engine.js:294:53 <- lib/media/media_source_engine.js:7197:19)
        at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
        at Generator.invoke [as _invoke] (node_modules/babel-polyfill/dist/polyfill.js:7138:22)
        at Generator.prototype.<computed> [as next] (node_modules/babel-polyfill/dist/polyfill.js:6952:21)
        at step (lib/media/media_source_engine.js:6705:191)
        at lib/media/media_source_engine.js:6705:361
    Error: Expected 0 to be greater than 0.
        at <Jasmine>
        at UserContext.<anonymous> (test/cast/cast_utils_unit.js:251:33 <- test/cast/cast_utils_unit.js:363:33)
        at <Jasmine>
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls overflow menu allows picture-in-picture only when the content has video FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls resolutions menu clears the buffer when changing resolutions FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls resolutions menu displays resolutions based on current stream FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) CastReceiver sends update messages every stage of loading FAILED
        [object Object] thrown
Chrome 85.0.4183.83 (Fedora 0.0.0) ERROR
  An error was thrown in afterAll
  Failed: Unhandled rejection in Promise: shaka.util.Error {
    "severity": 2,
    "category": 4,
    "code": 4032,
    "data": [],
    "handled": false,
    "message": "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()"
  }
  Error: Failed: Unhandled rejection in Promise: shaka.util.Error {
    "severity": 2,
    "category": 4,
    "code": 4032,
    "data": [],
    "handled": false,
    "message": "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()"
  }
      at <Jasmine>
      at test/test/boot.js:56:5 <- test/test/boot.js:59:5
Chrome 85.0.4183.83 (Fedora 0.0.0) ERROR
  Disconnected, because no message in 300000 ms.
Chrome 85.0.4183.83 (Fedora 0.0.0) CastUtils serialize/deserialize TimeRanges deserialize into equivalent objects FAILED
        Error: Failed: Type negotiation should happen before MediaSourceEngine.init!
            at <Jasmine>
        at Function.jasmineAssert (test/test/boot.js:38:7 <- test/test/boot.js:41:7)
        at _loop (lib/media/media_source_engine.js:296:20 <- lib/media/media_source_engine.js:7145:32)
        at _class._callee2$ (lib/media/media_source_engine.js:294:53 <- lib/media/media_source_engine.js:7197:19)
        at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
    NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.42c01e"') is unsupported.
    error properties: Object({ INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25, code: 9 })
    Error: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.42c01e"') is unsupported.
        at _loop (lib/media/media_source_engine.js:311:48 <- lib/media/media_source_engine.js:7168:85)
        at _class._callee2$ (lib/media/media_source_engine.js:294:53 <- lib/media/media_source_engine.js:7197:19)
        at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
        at Generator.invoke [as _invoke] (node_modules/babel-polyfill/dist/polyfill.js:7138:22)
        at Generator.prototype.<computed> [as next] (node_modules/babel-polyfill/dist/polyfill.js:6952:21)
        at step (lib/media/media_source_engine.js:6705:191)
        at lib/media/media_source_engine.js:6705:361
    Error: Expected 0 to be greater than 0.
        at <Jasmine>
        at UserContext.<anonymous> (test/cast/cast_utils_unit.js:251:33 <- test/cast/cast_utils_unit.js:363:33)
        at <Jasmine>
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls overflow menu allows picture-in-picture only when the content has video FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls resolutions menu clears the buffer when changing resolutions FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) UI controls resolutions menu displays resolutions based on current stream FAILED
        Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
Chrome 85.0.4183.83 (Fedora 0.0.0) CastReceiver sends update messages every stage of loading FAILED
        [object Object] thrown
Chrome 85.0.4183.83 (Fedora 0.0.0) ERROR
  An error was thrown in afterAll
  Failed: Unhandled rejection in Promise: shaka.util.Error {
    "severity": 2,
    "category": 4,
    "code": 4032,
    "data": [],
    "handled": false,
    "message": "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()"
  }
  Error: Failed: Unhandled rejection in Promise: shaka.util.Error {
    "severity": 2,
    "category": 4,
    "code": 4032,
    "data": [],
    "handled": false,
    "message": "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()"
  }
      at <Jasmine>
      at test/test/boot.js:56:5 <- test/test/boot.js:59:5
Chrome 85.0.4183.83 (Fedora 0.0.0): Executed 1744 of 1988 (5 FAILED) (skipped 30) ERROR (24.181 secs / 21.252 secs)
Firefox 80.0 (Fedora 0.0.0): Executed 1905 of 1988 (skipped 83) SUCCESS (6 mins 3.424 secs / 5 mins 58.52 secs)
Chrome 85.0.4183.83 (Fedora 0.0.0): Executed 1744 of 1988 (5 FAILED) (skipped 30) ERROR (24.181 secs / 21.252 secs)
[INFO] Run complete
[INFO] Result (exit code): 1
```

**Comment by joeyparrish** [comment] 2020-09-23 03:01
Can you please visit this page in that same copy of Chrome, and copy the output here?  https://shaka-player-demo.appspot.com/support.html

That will give us an idea of what codecs and formats are supported by the browser.  We may have made some bad assumptions somewhere.

**Comment by JakubRimal** [comment] 2020-09-23 09:09
Not sure if it does matter, but it's Chromium (version from the oficial Fedora repository), not Chrome.

```
Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
v3.0.4
{
  "manifest": {
    "application/dash+xml": true,
    "video/vnd.mpeg.dash.mpd": true,
    "application/x-mpegurl": true,
    "application/vnd.apple.mpegurl": true,
    "application/x-offline-manifest": true,
    "mpd": true,
    "m3u8": true,
    "application/vnd.ms-sstr+xml": false,
    "ism": false
  },
  "media": {
    "video/mp4; codecs=\"avc1.42E01E\"": false,
    "video/mp4": true,
    "video/mp4; codecs=\"avc3.42E01E\"": false,
    "video/mp4; codecs=\"hev1.1.6.L93.90\"": false,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": false,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": false,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": false,
    "video/mp4; codecs=\"vp9\"": false,
    "video/mp4; codecs=\"vp09.00.10.08\"": true,
    "video/mp4; codecs=\"av01.0.01M.08\"": true,
    "audio/mp4; codecs=\"mp4a.40.2\"": false,
    "audio/mp4": true,
    "audio/mp4; codecs=\"ac-3\"": false,
    "audio/mp4; codecs=\"ec-3\"": false,
    "audio/mp4; codecs=\"opus\"": true,
    "audio/mp4; codecs=\"flac\"": true,
    "video/webm; codecs=\"vp8\"": true,
    "video/webm": true,
    "video/webm; codecs=\"vp9\"": true,
    "video/webm; codecs=\"vp09.00.10.08\"": true,
    "audio/webm; codecs=\"vorbis\"": true,
    "audio/webm": true,
    "audio/webm; codecs=\"opus\"": true,
    "video/mp2t; codecs=\"avc1.42E01E\"": false,
    "video/mp2t": false,
    "video/mp2t; codecs=\"avc3.42E01E\"": false,
    "video/mp2t; codecs=\"hvc1.1.6.L93.90\"": false,
    "video/mp2t; codecs=\"mp4a.40.2\"": false,
    "video/mp2t; codecs=\"ac-3\"": false,
    "video/mp2t; codecs=\"ec-3\"": false,
    "text/vtt": true,
    "application/mp4; codecs=\"wvtt\"": true,
    "application/mp4": true,
    "application/ttml+xml": true,
    "application/mp4; codecs=\"stpp\"": true
  },
  "drm": {
    "org.w3.clearkey": {
      "persistentState": false
    },
    "com.widevine.alpha": {
      "persistentState": false
    },
    "com.microsoft.playready": null,
    "com.apple.fps.3_0": null,
    "com.apple.fps.2_0": null,
    "com.apple.fps.1_0": null,
    "com.apple.fps": null,
    "com.adobe.primetime": null
  },
  "offline": true
}
```

**Comment by joeyparrish** [comment] 2020-09-23 16:38
Ah, I see.  No proprietary codecs such as h264 or aac are supported.  Conversely, we support browsers that don't have vp9 or opus, where h264 and aac are the only options.

So anywhere we have integration test cases that use h264 or aac content, we need to have an alternative source in vp9 or opus.

Thanks!

**Comment by Ognengineer** [comment] 2021-12-03 09:29
Hey guys, I've come across a similar problem verifying assets playing on the project I work for. In fact, I'm automating the regression tests using cypress and when I come to a step for verifying the video asset is playing, I got an exception with the same codes. 
"category": 6,
"code:" 6001,
and 
"category": 4,
"code": 4032,
Tried on all chromium based browsers and firefox :(

**Comment by avelad** [comment] 2022-05-19 11:25
I think the problem should be "will not implement" because with github actions you can test PR, also this combination is not the most used. @joeyparrish , what do you think?

**Comment by joeyparrish** [comment] 2022-05-23 15:11
You might be right.  In theory, I think I would accept a PR to skip tests that depend on AAC or H264 when they are missing.  But since we have no such devices of our own, I think new test cases would get added that would break it again.

If someone wants to do the work to add alternative content with VP9 and Opus for all test cases, I think I would accept that, too.  But the same issue applies, I think.  If we don't exercise that path ourselves, we will eventually regress.

So none of these solutions is sustainable without an easy way to disable H264/AAC in a node of our Selenium grid.

I'll leave it open for a few days to see if anyone is interested in doing this work.  If not, the robot will close the issue.

Thanks!

**Closed** 2022-05-30 15:41 UTC
Labels: type: bug, status: waiting on response, priority: P3
