### ISSUE TITLE
Fallback for DASH streams with 404 in some fragments.

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#4093] opened 2022-03-31 15:35 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Please ask your question**

Hi!

We have sometimes an issue that produces some fragments to return a 404 and I would like to know if they may be skipped.

I've seen a configuration parameter named `failureCallback`, could it be used to catch the error and switch to another bitrate where the fragment may exist? If not, is there any other way to manage this situation for VOD and Live Streams? Maybe seeking to next fragment?

Thanks!

**Comment by adgllorente** [comment] 2022-03-31 15:45
Just like that! But for DASH

**Comment by joeyparrish** [comment] 2022-04-12 20:45
Also sounds like https://github.com/shaka-project/shaka-player/issues/2144

**Comment by joeyparrish** [comment] 2022-04-12 20:47
But we don't have anything like that today.  Should we consider this a duplicate of #2144, to skip a segment that fails?  Or is more like #2541, where you want to failover to another URL per-segment (rather than skip it)?

If it's a failover you want, we have that for DASH already.  Just use multiple BaseURL elements, and we'll go to the next one when there's a failure.

**Comment by adgllorente** [comment] 2022-04-22 08:07
@joeyparrish I agree with @avelad in #2144, shaka should continue playback in live streams, however, we may take a look to multiple BaseURL elements, do you have a link with more information about this? I haven't found any information in the documentation.

**Comment by avelad** [comment] 2022-05-04 12:35
@adgllorente I think this solution would help you: https://github.com/shaka-project/shaka-player/pull/4189 , can you confirm?

**Comment by joeyparrish** [comment] 2022-05-05 16:01
Solved by #4189

**Closed by joeyparrish** 2022-05-05 16:01 UTC
Labels: status: duplicate
