### ISSUE TITLE
In case of error, would like to know request headers and response body

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5721] opened 2023-10-04 13:50 UTC
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.4.2

**Please ask your question**
Is there any way in which we get the exposed request headers and response body. I understand that many events are not related to network related such as manifest parsing errors, drm errors etc. I am foucsing currently on error from cdn. Also I think writing an interceptor for segments that runs on every segment download can hamper performance. Since the networkengine internally has access to the api requests are these exposed somewhere.

**Comment by theodab** [comment] 2023-10-05 08:53
I think this is a duplicate of 5719, if I'm understanding correctly? I'll close this for now, but if you think your issue is substantially different you can ask Shaka bot to re-open with `@shaka-bot reopen`.

**Closed by theodab** 2023-10-05 08:53 UTC
Labels: type: question
