### ISSUE TITLE
Subtitle appearing twice

### ISSUE THREAD

**Issue by davidmagine** [shaka-project/shaka-player#7293] opened 2024-09-12 11:17 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

not related

**What version of Shaka Player are you using?**

4.7.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
not applicable

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
not applicable

**What browser and OS are you using?**
LG WebOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG model 55UK6400PLF, webOS 4.4.2-11 and a few other LG model tv and webOS versions

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 5
    },
    "servers": {
      "com.widevine.alpha": "****"
    },
    "advanced": {
      "com.widevine.alpha": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "SW_SECURE_DECODE",
        "audioRobustness": "SW_SECURE_CRYPTO",
        "sessionType": "",
        "serverCertificateUri": "",
        "individualizationServer": ""
      }
    }
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 5
    },
    "availabilityWindowOverride": null
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 5
    },
    "rebufferingGoal": 8,
    "bufferingGoal": 32,
    "stallThreshold": 2,
    "stallSkip": 0.05
  },
  "mediaSource": {},
  "offline": {},
  "abr": {
    "defaultBandwidthEstimate": 10000000,
    "restrictions": {
      "minWidth": 1
    }
  },
  "preferredAudioLanguage": "no"
}
```

**What did you do?**

Play a video with subtitle

**What did you expect to happen?**
Only one line of subtitle to appear

**What actually happened?**

Occasionally the subtitle will appear twice at different position
Video
https://github.com/shaka-project/shaka-player/assets/119855296/b8038fcb-dacb-45ea-a6c3-333fe59537f1
Image
![image](https://github.com/user-attachments/assets/e2dc9793-8095-4019-85a8-183bb89fcfc0)
VTT subtitle files (segments 37 and 38)
[vtt.zip](https://github.com/shaka-project/shaka-player/files/13633543/vtt.zip)

**Are you planning send a PR to fix it?**

**Additional notes:**
There is no textDisplayFactory set in our configuration and we are using the default. We are also not calling setVideoContainer

**Comment by avelad** [comment] 2024-09-12 11:19
Duplicate of https://github.com/shaka-project/shaka-player/issues/7293

**Closed by avelad** 2024-09-12 11:19 UTC
Labels: type: bug

**Comment by davidmagine** [comment] 2024-09-12 11:29
@avelad, think you tag the wrong ticket. I am unable to open https://github.com/shaka-project/shaka-player/issues/6007 that's why i created a new ticket with more information

**Comment by avelad** [comment] 2024-09-12 11:39
This is duplicate of https://github.com/shaka-project/shaka-player/issues/6773 It's a problem in the platform itself that we need to fix somehow :/
