### ISSUE TITLE
Typescript typings for events on shaka.Player

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5344] opened 2023-06-21 19:33 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, not sure if it's https://github.com/shaka-project/shaka-player/issues/1564

**Is your feature request related to a problem? Please describe.**

Yes, It's so good to see that Shaka already has inbuilt typescript support. Since I work with Shaka in React Typescript, I have been adding listeners on player. So `player.addEventListener` I wish we could have some typing support of all custom events available on `shaka.Player` class.

**Describe the solution you'd like**

All events listed here https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event atleast on `shaka.Player` should be avaiable instead of `type: string` So something like `ShakaPlayerEventMap` type being exported.

**Describe alternatives you've considered**

For any events, I need to use right now I have added them in global scope of typescript. And as I keep using more and more I am adding here below. Indeed the worst the work around.

```ts
type ShakaPlayerEvents = Array<
	'loading' | 'buffering' | 'trackschanged' | 'manifestparsed' | 'loaded'
>;
```

**Additional context**

None

**Comment by avelad** [comment] 2024-05-08 13:02
Duplicate of https://github.com/shaka-project/shaka-player/issues/1564

**Closed by avelad** 2024-05-08 13:02 UTC
Labels: type: enhancement, priority: P2
