### ISSUE TITLE
HTTP redirect during manifest update 

### ISSUE THREAD

**Issue by bbert** [shaka-project/shaka-player#7323] opened 2024-09-16 16:12 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.11.0
The issue has been introduced since version 4.4.x.
The version 4.3.16 does not encounter this issue.

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo ap

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chrome/windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default

**What did you do?**

Start playback of a live stream with manifest updates.
Once started, during the session, the manifest update request returns a redirect (307) with a new manifest url.

This test scenario can be reproduced using a local proxy software tool that is able to return a customized response, with a 307 redirect to a new manifest URL.

**What did you expect to happen?**
After manifest redirection occurs, all requests (manifest update and segment requests) should use the new BaseURL derived from the new redirected manifest url.

**What actually happened?**

Manifest update requests are correctly fetched from new BaseURL, but the segments requests are still using the original BaseURL from the original manifest url.

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment] 2024-09-18 08:47
@bbert Do you know which commit introduces the regression?

**Comment by bbert** [comment] 2024-09-18 09:36
It seems related to introduction of content steering support (https://github.com/shaka-project/shaka-player/pull/5884), when the `getBaseUris()` method in `DashParser` has been introduced:

```
    let calculatedBaseUris;
    const getBaseUris = () => {
      if (!calculatedBaseUris) {
        calculatedBaseUris = shaka.util.ManifestParserUtils.resolveUris(
            manifestBaseUris, uris);
      }
      return calculatedBaseUris || [];
    };
```

**Comment by avelad** [comment] 2024-09-18 10:18
@bbert Can you check if this patch would fix this issue?

```diff
diff --git a/lib/dash/dash_parser.js b/lib/dash/dash_parser.js
index 5b5e5921d..1ac30b6de 100644
--- a/lib/dash/dash_parser.js
+++ b/lib/dash/dash_parser.js
@@ -192,6 +192,9 @@ shaka.dash.DashParser = class {
 
     /** @private {function():boolean} */
     this.isPreloadFn_ = () => false;
+
+    /** @private {?Array.<string>} */
+    this.lastCalculatedBaseUris_ = [];
   }
 
   /**
@@ -602,7 +605,6 @@ shaka.dash.DashParser = class {
     }
 
     const uriObjs = TXml.findChildren(mpd, 'BaseURL');
-    let calculatedBaseUris;
     let someLocationValid = false;
     if (this.contentSteeringManager_) {
       for (const uriObj of uriObjs) {
@@ -615,9 +617,10 @@ shaka.dash.DashParser = class {
         }
       }
     }
+    this.lastCalculatedBaseUris_ = null;
     if (!someLocationValid || !this.contentSteeringManager_) {
       const uris = uriObjs.map(TXml.getContents);
-      calculatedBaseUris = shaka.util.ManifestParserUtils.resolveUris(
+      this.lastCalculatedBaseUris_ = shaka.util.ManifestParserUtils.resolveUris(
           manifestBaseUris, uris);
     }
 
@@ -625,8 +628,8 @@ shaka.dash.DashParser = class {
       if (this.contentSteeringManager_ && someLocationValid) {
         return this.contentSteeringManager_.getLocations('BaseURL');
       }
-      if (calculatedBaseUris) {
-        return calculatedBaseUris;
+      if (this.lastCalculatedBaseUris_) {
+        return this.lastCalculatedBaseUris_;
       }
       return [];
     };
```

**Comment by bbert** [comment] 2024-09-18 10:27
That's the one I just tried myself, and that works.
But I just don't know if that can have any side effect, and if the same patch has to be applied in method `getFrameUris()`

**Comment by avelad** [comment] 2024-09-18 10:32
The only adverse effect is that we have to store an array, perhaps a bit more memory. Applying this same thing to frameUris is complicated, because we would have to use a map, and then we could incur in a memory leak :( For now, since your case is solved with this fix, when I create the PR I will close it, and if someone in the future has a problem with `getFrameUris` we will have to find a solution that does not break anything or produces a memory leak...

**Closed** 2024-09-18 11:08 UTC
Labels: type: bug, priority: P2, component: DASH
