### ISSUE TITLE
DASH + ad insertion: Uncaught exception in promise in 4.7.0

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#6010] opened 2023-12-11 15:10 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.6.3, 4.7.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome/MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Can be provided in email if needed

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default demo app

**What did you do?**

Play dash manifest with ad insertion, problem occurs when switching between content and ads

**What did you expect to happen?**
No uncaught exception in the console

**What actually happened?**

Error in the console:
<img width="710" alt="image" src="https://github.com/shaka-project/shaka-player/assets/56258400/3af98a18-c94c-4483-97b7-cd3801361b7a">

The codecs in the array:
<img width="315" alt="image" src="https://github.com/shaka-project/shaka-player/assets/56258400/f9784b7b-b493-480c-8dd7-f1d0ec2817bb">

The error says `MANIFEST.HLS_COULD_NOT_GUESS_CODECS` but HLS is not involved.

Content will continue playing, but the console will fill up with errors.

I didn't see the issue on 4.6.3, but I did see it in 4.7.0, perhaps this commit is a good place to start?
https://github.com/shaka-project/shaka-player/commit/24e32559bff6457aa8a1b356f26d83b6a320b9b2

**Comment by littlespex** [comment] 2024-02-26 22:49
This issue still occurs, and the error message is very misleading.

**Comment by avelad** [comment] 2024-02-26 22:57
@littlespex can you send a fix for it? Thanks!

**Comment by cristian-atehortua** [comment] 2024-02-27 20:10
@littlespex can you share in which scenario and which Shaka's version is happening? For our case, the issue is no longer happening for version >=4.7.4.

**Comment by joeyparrish** [comment] 2024-02-27 20:16
This change in v4.7.4 could explain an exception being fixed:

https://github.com/shaka-project/shaka-player/pull/6073/files#diff-4264ba5cebc3bca4b16e2beb0d42d2679f27d7a9ed3f43d57ab2dc17471a0e19L236-L241

**Comment by littlespex** [comment] 2024-02-27 21:43
This issue happens in all 4.7.x versions for us. This is another period flattening bug:
The stream we are testing is a DAI generated manifest that has mixed video codecs across periods:
- Ads have `avc1` and `hev` adaptations
- Content has `dvhe`, `hvc1`, and `avc1` adaptations
Because there is no matching advanced codec from ads -> content, the period flattening logic combines `hev` and `hvc1` into a single codec string, separated by a comma. Later, when it tries to guess the correct codec to play, its sees the comma and thinks its a video + audio codec string. It splits the string and assumes the second value is the audio codec, which it's not, and throws the ill named `HLS_COULD_NOT_GUESS_CODECS` because niether `hvc` or `hev` are valid audio codecs.

![Screenshot 2024-02-23 at 14 49 53](https://github.com/shaka-project/shaka-player/assets/1508707/0f26e1c9-4d6f-493c-be6e-61796feced0d)

**Comment by willdharris** [comment] 2024-03-13 17:53
I'm working with @littlespex and @dsparacio on this issue. 

With our content, after the streams from all periods are combined, we end up with multiple video streams that include multiple codecs concatenated in the stream's `codecs` property.  For example: `hev1.2.4.L63.90,hvc1.2.4.L63.90` and `dvhe.05.01,avc1.42c00d`.

![outputstreams](https://github.com/shaka-project/shaka-player/assets/66787651/3fd0809f-5ede-47db-a612-e584a97ba63a)


Later on when the manifest is filtered for [decoding configs](https://github.com/shaka-project/shaka-player/blob/4ae15c2c6fe2be98a7a6e9960ce48181f45e1324/lib/util/stream_utils.js#L720-L745) and [media capabilities](https://github.com/shaka-project/shaka-player/blob/4ae15c2c6fe2be98a7a6e9960ce48181f45e1324/lib/util/stream_utils.js#L401-L424), we hit the issue @littlespex described above. If `codecs` includes a comma, it's assumed the stream is multiplexed (video + audio) and ultimately fails with `HLS_COULD_NOT_GUESS_CODECS` because the second codec is not a valid audio stream.   

We identified this became an issue for us with the addition of the `Handle mixed-codec variants feature`: https://github.com/shaka-project/shaka-player/pull/5950, where codecs of the same content type are being concatenated. 

https://github.com/shaka-project/shaka-player/blob/7fd99b7c2663903f3fa3991acfbab3782ddb0e07/lib/util/periods.js#L786-L795

I'm not sure I fully understand the intention here. Does a stream need to list both codecs for the mixed-codec feature to work properly? Are these codecs combined to say, "if the first codec is not available in a period but the second is, use the second"? 

But then with https://github.com/shaka-project/shaka-player/pull/6047, `filterDuplicateCodecs_` was added which essentially removes the second concatenated codec. 

https://github.com/shaka-project/shaka-player/blob/4ae15c2c6fe2be98a7a6e9960ce48181f45e1324/lib/util/periods.js#L725-L760

That fix works when concatenated codecs have the same codec base, i.e. avc and avc `avc1.42c01e, avc1.640028`, but doesn't work if the codec bases are different, i.e hev and hvc `hev1.2.4.L63.90,hvc1.2.4.L63.90`. Which probably explains why the originally reported issue was resolved with the fix but not with our content.

My outstanding questions regarding the approach we should take for a fix:
1. Should the concatenated codecs be filtered to remove the "duplicate" codec? We can add a fix here for the additional codecs that aren't being caught. But does this break the mixed-codec feature?
2. Should the codecs remain concatenated? Then in the stream utils where [multiplexed streams are split](https://github.com/shaka-project/shaka-player/blob/4ae15c2c6fe2be98a7a6e9960ce48181f45e1324/lib/util/stream_utils.js#L403-L424), add a check that only runs the multiplexed code if the concatenated codecs are different types (video vs audio).

**Comment by dsparacio** [comment] 2024-03-13 19:16
More context, our content carries hvc and dvhe. hev is inserted by DAI. Additionally, DAI is mixing color space when DVHE is selected as they do not plan to provide a DVHE adpod encode as of today.  

In 4.3.6, the mixed case was working with HEV and HVC but not HEV and DVHE.  So this is why we looked into latest and found this new issue.  If we remove DAI from the mix, 4.7.11 is working as expected regarding the codec selection and period flattening.  We hope if we fix the mix codecs issue we should be able to get the expected outcome for period mixtures
```
 [HEV] [DVHE] [HEV] [DVHE] [HEV]
 [HEV] [HVC] [HEV] [HVC] [HEV]
```
We are working with the DAI team, asking for DVHE to be available in addition to hevc for other reasons beyond this issue.

**Comment by theodab** [comment] 2024-03-15 10:34
> I'm not sure I fully understand the intention here. Does a stream need to list both codecs for the mixed-codec feature to work properly? Are these codecs combined to say, "if the first codec is not available in a period but the second is, use the second"?

This was a fix for an issue from an internal client, who had multiperiod streams where some periods only had opus audio and some periods only had aac audio.

> Should the concatenated codecs be filtered to remove the "duplicate" codec? We can add a fix here for the additional codecs that aren't being caught. But does this break the mixed-codec feature?

I think it might break the mixed-codec feature, yeah. Annoyingly the sample content I was given for the original bug is no longer hosted online, so to confirm this I would have to make new content.

> Should the codecs remain concatenated? Then in the stream utils where [multiplexed streams are split](https://github.com/shaka-project/shaka-player/blob/4ae15c2c6fe2be98a7a6e9960ce48181f45e1324/lib/util/stream_utils.js#L403-L424), add a check that only runs the multiplexed code if the concatenated codecs are different types (video vs audio).

On initial inspection this feels like the better solution, but I can't be sure.

Honestly, it'd probably be a good idea to make some content that can be put into the Shaka Player demo anyway, so we can confirm that future changes don't break this feature. I'll hack something together tomorrow.

**Comment by willdharris** [comment] 2024-03-15 14:53
@theodab Thanks for the response. Yeah I came across the code in [getDecodingInfosForVariant_](https://github.com/shaka-project/shaka-player/blob/292ef20d80019191a98f64a5f6106f92277991a4/lib/util/stream_utils.js#L539-L571) where the concatenated codecs are each checked for support. So I see why both codecs should be there. The problem right now, is that with two video codecs, we don't reach that part of the code due to an earlier error in `getDecodingConfigs_`. I think it makes sense to add a check to only run the multiplexed code for multiplexed content. 

I have a fix in progress and will try to get a PR up today.

**Comment by theodab** [comment] 2024-03-16 09:06
I made a sample asset, and tested a basic solution along the lines of the second solution you mentioned.

I think there is just a fundamental problem in how I wrote #5950.
The sample content I had, each period had a different codec but the same mimeType.
And the solution I wrote handled that case, but it doesn't handle variants that have multiple mimeTypes properly. Specifically, if there are multiple mimeTypes, we will test compatibility only with the first mimeType. For example, if we go from `video/webm; codecs="vp09.00.41.08"` to `video/mp4; codecs="avc1.4d401f"`, we test to see if the stream is supported as though it was `video/webm; codecs="vp09.00.41.08,avc1.4d401f"`... which is wrong, because at no point are we using avc1 in webm, a combination not supported by Chrome.

This is kind of a problem because we still might create these variants, even though we can't play them. Also because it means the documentation for `manifest.dash.multiTypeVariantsAllowed` is wrong.

I'll make a change to fix how the multi-type support handles streams that switch between mimeTypes. MediaSource can play such content, we just get confused when we try to determine if they are playable or not. I think this will involve reverting how codecs are stored in streams (so they won't be combined together anymore), and instead add a new value that just stores an array of the final full mimeTypes of each stream and uses that for compatibility checks.

**Comment by willdharris** [comment] 2024-03-18 12:35
Thanks @theodab. There were still some issues with the fix I was working on last week, so I did not submit a PR. We'll defer to your changes and re-test when that's available.

**Comment by dsparacio** [comment] 2024-03-18 17:24
@theodab any idea on your timeline on this change. Just to feedback to the DAI team next Monday when we meet on this.

**Comment by theodab** [comment] 2024-03-20 09:48
I have an experimental PR out for this now. I've tested it with the sample asset I made, and it seems to help, but it'd be nice to know if it solves the actual content you are having issues with.

**Comment by willdharris** [comment] 2024-03-20 18:43
Thanks @theodab. I tested our content with your branch `theodab:fixMultiMimeTypeBranch`. This gets us past the `HLS_COULD_NOT_GUESS_CODECS` error, but now we're seeing a `6001 / REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error.

I'm also getting this error with other DRM content (not mixed codecs) in `fixMultiMimeTypeBranch`. That same content plays with no errors in `main`.

```
"Error: Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()
    at new shaka.util.Error (http://127.0.0.1:5501/lib/util/error.js:101:15)
    at shaka.media.DrmEngine.queryMediaKeys_ (http://127.0.0.1:5501/lib/media/drm_engine.js:955:13)
    at shaka.media.DrmEngine.init_ (http://127.0.0.1:5501/lib/media/drm_engine.js:412:20)
    at async shaka.media.PreloadManager.initializeDrmInner_ (http://127.0.0.1:5501/lib/media/preload_manager.js:538:5)
    at async shaka.media.PreloadManager.start (http://127.0.0.1:5501/lib/media/preload_manager.js:387:7)
    at async mutexWrapOperation (http://127.0.0.1:5501/lib/player.js:1407:9)
    at async shaka.Player.load (http://127.0.0.1:5501/lib/player.js:1449:11)"
```
![shaka-6001](https://github.com/shaka-project/shaka-player/assets/66787651/7b713a00-2372-4379-98e7-18e956cc1985)

We are working on getting shareable content that we can pass along.

**Comment by willdharris** [comment] 2024-03-20 21:52
I think I found the cause of the `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error. Added a comment on the PR.

**Comment by willdharris** [comment] 2024-03-21 20:24
@theodab The last commit resolves the `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` error now. However we've hit one more issue with our content. This a DAI stream, with clear and encrypted periods. The pre-roll ad plays, but does not transition to the encrypted content period. No errors in the logs.

In this branch, I see 2 calls to `MediaKeys.createSession` both at the end of the ad period, just before the encrypted content period. 
In previous Shaka versions where this content works (i.e. 4.6.15), there is a single call to `MediaKeys.createSession` at the very start of the pre-roll ad.

I also found there may be a conflict  with the [Remove DOM Parser](https://github.com/shaka-project/shaka-player/pull/6063) feature. If I revert that commit, and related commits (https://github.com/shaka-project/shaka-player/pull/6063, https://github.com/shaka-project/shaka-player/pull/6198, https://github.com/shaka-project/shaka-player/pull/6267) from your branch the issue is resolved. Not sure of the correlation yet.

Still working on getting a shareable stream. Will send that over asap.

**Comment by willdharris** [comment] 2024-03-25 18:28
@theodab I just emailed content URIs for our test content to the maintainers group.

Again, the initial `HLS_COULD_NOT_GUESS_CODECS` error is resolved with the current PR. Now the period transition from unencrypted pre-roll to encrypted content is not working. Reproducible on Desktop Chrome.

**Comment by willdharris** [comment] 2024-04-08 21:40
Tested the fix again today with our content and confirmed the `HLS_COULD_NOT_GUESS_CODECS` issue is resolved. 

The ad to content freeze appears to be due to the content period being Widevine L1 encrypted. There's no problem with playback on HW CDM devices. In previous versions of Shaka, on non-HW CDMs, the content falls back to SD variants and playback continues. Now playback just stalls with no error. But that is unrelated to this specific issue and we will open a separate issue if needed.

**Closed** 2024-04-10 09:48 UTC
Labels: type: bug, priority: P1, component: DASH

**Comment by theodab** [comment] 2024-04-10 10:15
There we go. Sorry it took so long to merge that!
