### ISSUE TITLE
Reproducible black screen after reloading shaka-player (widevine, Windows 11, Nvidia RTX 4090) 

### ISSUE THREAD

**Issue by alessandroceleste** [shaka-project/shaka-player#5385] opened 2023-07-01 03:50 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.7 (uncompiled) from [https://shaka-player-demo.appspot.com/demo/](https://shaka-player-demo.appspot.com/demo/)

**Can you reproduce the issue with our latest release version?**
Yes (v4.3.7)

**Can you reproduce the issue with the latest code from `main`?**
Yes (v4.3.7-main-34-gb1e7cc4e6)

**Are you using the demo app or your own custom app?**
Demo app and third-party apps.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Microsoft Windows 11 Pro, 10.0.22621 Build 22621
Google Chrome, Mozilla Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not applicable.

**What are the manifest and license server URIs?**

If required, I can send the information later.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

If required, I can send the information later.

**What did you do?**

- Close all open tabs
- Visit the website [https://shaka-player-demo.appspot.com/demo/#audiolang=de-DE;textlang=de-DE;uilang=de-DE;panel=HOME;build=uncompiled](https://shaka-player-demo.appspot.com/demo/#audiolang=de-DE;textlang=de-DE;uilang=de-DE;panel=HOME;build=uncompiled)
- Whenever I refresh the webpage my monitor becomes black for ca. 2 seconds
- After the black screen, the monitor reports a video signal from the HDMI interface

**What did you expect to happen?**
No, black screen.

**What actually happened?**

- PC has iGPU (Intel) and dGPU (Nvidia RTX 4090)
- Monitor is Asus VS248H (tested with all 4 monitors available of the same model)
- Issue appears only with dGPU
- Issue appears only with Windows OS (with Ubuntu it is working correctly)
- Issue seems to be related to widevine (playready is working as expected - tested here with MS Edge: https://bitmovin.com/demos/drm - MS Edge in combination with widevine doesn't work correctly)
- Closing browser tab with loaded player causes the black screen
- Reloading the browser tab causes the black screen
- If an additional browser tab is open (with widevine loaded), the issue doesn't appear when reloading/closing one of the two open browser tabs
- With TV monitor Samsung UE55ES6300 the issue doesn't appear at all

I have used the browser inspection utility to find out at which point the monitor becomes black in the code (debugging mode). Unfortunately, the issue occurs "randomly" after the call of `async setupPlayer_()` in `main.js`:

I also found out that the issue appears after a certain amount of time while pausing the code after the call of `await this.setupPlayer_();` Possibly a destroy method is called (?).

Important to remember that the issue is/could also be related to:
- widevine
- Windows 11
- Nvidia dGPU RTX 4090

Does anybody know what the root cause of this issue could be?

**Comment by alessandroceleste** [comment] 2023-07-06 19:35
Since I am not sure if the issue is related to Shaka-Player, I would like to analyze the issue in more detail.

If we would assume that the dGPU driver is working correctly, can anybody immagine why the issue is only present with dGPU (Nvidia)? iGPU (Intel) doesn't cause any black screens. Using another display (TV, see above) solves the issue. Unfortunately, I don't have any other dGPU for testing (AMD, Intel).

I could imagine that the different monitor ICs use different signal loss detection timeouts. Maybe Widevine/Shaka-Player/Nvidia take too long to initialize the hardware when player is in the initialization phase? Maybe Intel iGPU has faster initialization?

I'm also in contact with Nvidia to sense the different root cause options. By the way, I tested many different Nvidia driver versions, but without success.

**Comment by joeyparrish** [comment] 2023-07-07 04:52
I would assume that it has something to do with Widevine.  The Shaka Player demo probes Widevine support on startup, which may trigger something in a video driver for all I know.

One way to isolate this is to try building a simple app that uses the player, but does not call `probeSupport()` or configure DRM.  You can follow the ["basic usage" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) for that, which should refer to clear content.

In any case, there is absolutely nothing in JavaScript that should give us control over such low-level details.  Whatever you find for a root cause, it is very unlikely to be something that can be fixed in a web page.  I would guess it is much more likely to be something in a driver or in the Widevine CDM.  (But a driver issue seems most likely.)  Since the Widevine CDM on Windows is probably not using your video drivers for actual key handling, it may turn out to be related to activating HDCP.

I hope that helps!  If you need further help, please reach out to Nvidia or Widevine.  I don't believe there's anything we can do in JS-land.

If you feel that this issue should be reopened for any reason, just put `@shaka-bot reopen` in a comment.  Thanks!

**Closed by joeyparrish** 2023-07-07 04:52 UTC
Labels: type: bug, type: external, platform: Windows, component: Widevine

**Comment by alessandroceleste** [comment] 2023-07-12 20:28
@joeyparrish Thanks for your response. Disabling `probeSupport()` does work as expected by you (issue not appearing).
Nearly at the same time, Nvidia came back to me with a new solution.

I could find out that the issue is related to the "Generic Monitor Drivers":
![image](https://github.com/shaka-project/shaka-player/assets/37930300/777fc9ae-0485-4efa-8184-b00658285cf2)

```
Driver date: 21/06/2006
Driver version: 10.0.22621.1928
```

I disabled all monitors with "disable device" in the device manager. Nevertheless, all monitors do work. The issue with the black screen is gone in that configuration. I absolutely do not understand why the issue is only related to Widevine in combination with dPGU but I'm glad that there is a workaround for this issue.

I hope that this comment helps other people with similar issues to solve them quickly. It took a lot of time to me debugging this issue. Although the issue is not caused by the software of this project, this report may help other people with similar issues since it is difficult to find the root cause of this kind of issue.

If the issue should return for any reason I will update my comment to inform other people.

**Comment by joeyparrish** [comment] 2023-07-12 22:15
Thank you so much for the update!  This is really useful information.

I might guess that Widevine is doing something like initializing HDCP (output protection on the monitor), and that this step causes the display interruption for certain drivers.  But I don't have any good way of knowing for sure.
