### ISSUE TITLE
Catch-up, player stops when manifest transitions from 'dynamic' to 'static'

### ISSUE THREAD

**Issue by mrp1977** [shaka-project/shaka-player#2581] opened 2020-05-20 09:41 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.11

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
DEMO APP

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome on Mac (Same on all browsers)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

```sh
echo "https://live.unified-streaming.com/scte35/scte35.isml/.mpd?vbegin=$(($(date -u +%s)-240))&vend=$(($(date -u +%s)+30))"
```

This will give you the time relevant URL

**What did you do?**
Added a vbegin time in the past and a vend time in the future to the livestream URL

**What did you expect to happen?**
Clip plays from beginning to end based on times given

**What actually happened?**
Playback stops as soon as Manifest transitions from Dynamic to static (as vend time reaches wallclock)

I have attached an examples of the dynamic and static manifests

[dynamicmanifest.txt](https://github.com/google/shaka-player/files/4655925/dynamicmanifest.txt)
[staticmanifest.txt](https://github.com/google/shaka-player/files/4655926/staticmanifest.txt)

le of the dynamic and static manifests

**Comment by joeyparrish** [comment] 2020-05-21 20:08
The usual problem we've seen in the past is that timestamps are changed when content transitions to static, and based on your attachments, it looks like that might be the case here, too.

If the MPD describes a segment with a presentation timestamp of (hypothetically) 1,000,000, then we update the manifest and that same segment now has a presentation timestamp of (for example) 12, playback will definitely break.

In your attachments, the dynamic version uses presentation timestamps which are aligned to the unix epoch of Jan 1, 1970.  Then the static version uses `presentationTimeOffset=1589965084`, which aligns the content with the period start time of `0`.  Since this is fundamentally a different timeline, the player has no way to reconcile this.

The static version makes sense on its own, of course, as VOD content, but not as an *update* to the dynamic version.

**Comment by joeyparrish** [comment] 2020-05-21 20:09
I would advise you to report this to Unified Streaming as a bug.  If we can help explain this in any way, we would be happy to help.  And if Unified Streaming has some advice about some way that players could hypothetically make this make sense across an update, we would be happy to hear that and make changes to Shaka Player if we can.

**Comment by boy-vd** [comment] 2020-06-15 13:43
Hi @joeyparrish, thanks for picking up this issue and providing feedback so quickly. Like @mrp1977, I represent Unified Streaming and a more in-depth explanation on what you think is wrong with the content would be really helpful, especially if you have suggestions on how it should be improved.

I think I understand your point about the content the anchor of the timeline for the content in the dynamic MPD being UNIX epoch, while it is '0' for the static MPD. However, there doesn't seem to be a clear way to anchor the content in the static MPD to UNIX epoch as well, as 'availabilityStartTime' seems to be meaningful in a dynamic context only (although it's not forbidden to keep it when switching an MPD from dynamic to static according to paragraph 4.6.2 of the DASH-IF Guidelines for Implementation version 4.3:

> The MPD@availabilityStartTime should be removed or be maintained from the live MPD since all resources referenced in the MPD are available. If the MPD@availabilityStartTime is maintained for a portion of the live program that is offered in the static MPD the Period@start value (including the presentation time offset and the start number) and the presentation duration shall be set accordingly. The relationship to the wall-clock time should be maintained by offsetting the Period@start without changing the MPD@availabilityStartTime.

Also, I'm sorry for only getting back to you about this now, but in the meantime we were waiting for a response from dash.js on this same issue. They have now made it work in their player: https://github.com/Dash-Industry-Forum/dash.js/issues/3263.

**Comment by sandersaares** [comment] 2020-07-16 07:57
This is an interesting scenario that I feel we should better illustrate also in the DASH-IF guidelines. I filed an issue in the DASH-IF repo for this, with some initial thoughts on how to handle it: https://github.com/Dash-Industry-Forum/Guidelines-TimingModel/issues/56

Does the mechanism I propose in the referenced issue appear to be applicable to this scenario?

**Comment by martinstark** [comment] 2022-01-11 10:50
Would be great to see full shaka support for this. We work with clients that have startover / record & watch features that we currently use manifest network filter "hacks" to make work in shaka. Full support would be great.

**Comment by martinstark** [comment] 2022-04-04 12:21
We're using the type of manifest described in this issue, with a network filter to make shaka able to play the stream and complete the dynamic to static transition without shutting down, and maintaining a sensical seekRange.

The network filter modifies the manifest before it is fed to shaka, by taking the `t` value of the `SegmentTimeline` `S` and applying it as the `presentationTimeOffset` on the `SegmentTemplate` **while the manifest is still dynamic**.

![image](https://user-images.githubusercontent.com/901824/161540699-4dc45ef6-589e-4ce8-8b6d-197be6690668.png)

This has worked like a charm on versions of shaka up to and including 3.1.1. The commit that made it stop working is https://github.com/shaka-project/shaka-player/commit/b3166db4bc7cac968a03796bc9c2d7e598fb88c7. Since this commit was made, the streams have started stalling unpredictably after the manifest turns static, with shaka unable to find the correct segment in maybe 20% of stream starts.

![image](https://user-images.githubusercontent.com/901824/161540606-4970ee5f-23b2-403a-8188-a941ca6a5df8.png)

Shaka holds a reference to the full array of segments, and shows the correct seekRange, but can not play past a certain point in the stream due to some internal calculation going wrong that I haven't been able to pin down.

Related https://github.com/shaka-project/shaka-player/issues/3902

I was able to use this stream url to reproduce the issue using the reference stream from Unified Streaming:

```
echo "https://demo.unified-streaming.com/k8s/live/stable/scte35.isml/.mpd?vbegin=$(($(date -u +%s)-2000))&vend=$(($(date -u +%s)+30))"
```

@joeyparrish any input would be appreciated

**Comment by avelad** [comment] 2023-01-31 18:01
Can you test with v4.3.4? Thanks!

**Comment by martinstark** [comment] 2023-01-31 18:07
We're still seeing the issue in 4.3.3, is https://github.com/shaka-project/shaka-player/pull/4914 the commit that potentially fixes the issue in 4.3.4? I'll get it checked out tomorrow.

**Comment by avelad** [comment] 2023-01-31 18:10
> We're still seeing the issue in 4.3.3, is #4914 the commit that potentially fixes the issue in 4.3.4? I'll get it checked out tomorrow.

It fixes some cases, I hope it fixes this one.

**Comment by martinstark** [comment] 2023-02-08 14:27
@avelad we're still seeing DASH stalls on 4.3.4, but our issue is probably different from the one in this particular ticket. 

I opened my own ticket (and eventually closed it) here: #3902. The symptoms and way to reproduce #3902 are still the same in 4.3.4, but there is no longer a need for a custom network filter since shaka can handle the dynamic->static transition on its own now.

**Comment by unext-wendong** [comment] 2023-03-06 08:40
We are also seeing the same behavior using 4.3.4, i.e. playback stopped when the DASH manifest switched from "dynamic" to "static".

Just to share what we observed in case it's helpful.

In our case we are playing a DASH live streaming content with a startover window served from AWS MediaLive/MediaPackage (a time-shifted viewing in AWS's terminology).

Reproduce procedure:
1. Start the live streaming on AWS.
2. Start the playback using a URL with time-shifted viewing enabled.
3. Keep the playback on.
The player updates the manifest regularly as in normal live streamings. Newer manifests have a larger timeShiftBufferDepth but are all with the same the starting segment.
4. Stop the live streaming on AWS.
5. Observe the playback.
The player updates the manifest again and then the playback stops. It appears the player went into stalling state.

We compared the 2 manifests right before the playback stop. And here are the main differences:
- a. "MPD.type" is changed from "dynamic" to "static".
- b. "MPD.publishTime / minimumUpdatePeriod / availabilityStartTime / suggestedPresentationDelay / timeShiftBufferDepth" are replaced with "MPD.mediaPresentationDuration".
- c. In "SegmentTemplate", the attribute "presentationTimeOffset" is added. In 2/3 of the "SegmentTemplate", the attribute value is same as the "S.t" of the first "S" in its "SegmentTimeline".

See the attached files for the full manifests.
[manifest_2nd_before_stop.txt](https://github.com/shaka-project/shaka-player/files/10895941/manifest_2nd_before_stop.txt) (dynamic)
[manifest_1st_before_stop.txt](https://github.com/shaka-project/shaka-player/files/10895944/manifest_1st_before_stop.txt) (static)

**Comment by unext-wendong** [comment] 2023-03-06 09:28
The behavior on the latest 4.3.5 is same.

**Comment by unext-wendong** [comment] 2023-11-07 02:33
I can still reproduce it on the latest nightly bulid: v4.5.0-72-g2eedb12a1 (uncompiled)

**Comment by nikhilxperi** [comment] 2024-03-06 17:11
I can still reproduce it in the latest build. Could you please confirm if it is scheduled to be fixed in the upcoming version?

**Comment by joeyparrish** [comment] 2024-03-06 21:57
I could definitely schedule fixes if I knew the cause of every bug.  But then the schedule would be short indeed.  😁 Without knowing the cause, we can't know how long it will take to diagnose and fix.  That makes sense, right?

But you could definitely contribute if you want to debug or work on a fix yourself.  All are welcome!  I don't believe anyone is actively working on this issue right now.

**Comment by nikhilxperi** [comment] 2024-05-20 13:56
Hi we are able to reproduce the issue, i have shared the playback URL over the email(shaka-player-maintainers@googlegroups.com)  To reproduce the issue, please keep the start time in past and end time in future. And seek the playback in past. when clock time reach to end time, manifest change from 'dynamic' to 'static'. that time playback should continue from seek position. but playback stop. request you to please check and help here

**Comment by avelad** [comment] 2024-05-27 08:11
> Hi we are able to reproduce the issue, i have shared the playback URL over the email([shaka-player-maintainers@googlegroups.com](mailto:shaka-player-maintainers@googlegroups.com)) To reproduce the issue, please keep the start time in past and end time in future. And seek the playback in past. when clock time reach to end time, manifest change from 'dynamic' to 'static'. that time playback should continue from seek position. but playback stop. request you to please check and help here

I sent you a reply to your email. Please check it.

**Comment by nikhilxperi** [comment] 2024-05-27 08:27
> > Hi we are able to reproduce the issue, i have shared the playback URL over the email([shaka-player-maintainers@googlegroups.com](mailto:shaka-player-maintainers@googlegroups.com)) To reproduce the issue, please keep the start time in past and end time in future. And seek the playback in past. when clock time reach to end time, manifest change from 'dynamic' to 'static'. that time playback should continue from seek position. but playback stop. request you to please check and help here
> 
> I sent you a reply to your email. Please check it.

@avelad thank you for the help. we will check on it

**Comment by avelad** [comment] 2024-07-12 07:59
@mrp1977 Your url `echo "https://live.unified-streaming.com/scte35/scte35.isml/.mpd?vbegin=$(($(date -u +%s)-240))&vend=$(($(date -u +%s)+30))"` returns a 404, can you review it? Thanks!

**Comment by mrp1977** [comment] 2024-07-12 08:03
@avelad We have since changed our demo setup. The following should replace the above
"https://demo.unified-streaming.com/k8s/live/stable/scte35.isml/.mpd?vbegin=$(($(date -u +%s)-240))&vend=$(($(date -u +%s)+30))"

**Comment by avelad** [comment] 2024-07-12 08:56
I have a local fix to make this work, I still have to make it pretty and make sure it doesn't break any other streams.

**Closed** 2024-07-12 14:18 UTC
Labels: type: bug, priority: P2, component: DASH
