### ISSUE TITLE
Regression: New segments are not fetched after seeking until the player is out of buffer

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#5785] opened 2023-10-19 22:53 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not related

**What version of Shaka Player are you using?**
v4.5.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Chrome on Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/m3u8s/11331.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
  streaming: {
    rebufferingGoal: 5,
    bufferingGoal: 20
  }
}
```

**What did you do?**

I'm observing this issue in v4.5.0 and v4.4.0, but not in v4.3.0. Then I did a git bisect which pointed to commit c42565ccb9c69455307742e1f5c3c763892ec1c6.

Minimal repro with shaka player built at commit c42565c:
https://personal-data-2018.s3.amazonaws.com/shaka.html

**What did you expect to happen?**

Buffer should keep growing after seeking to near the location where the playback buffer ends. 

**What actually happened?**

New segments are not fetched after seeking until the player is out of buffer.

**Comment by avelad** [comment] 2023-10-23 07:54
@wjywbs are you interested in create a PR for fix it? Thank you!

**Comment by wjywbs** [comment] 2023-10-23 11:17
Hi @avelad, I don't understand how c42565c causes this regression. c42565c is supposed to fix the AV sync issue in #4589.

**Comment by avelad** [comment] 2023-10-30 10:58
I tested your page changing to https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.compiled.js and works fine, so the problem is fixed in the main branch. Can you try it? Thanks!

**Comment by wjywbs** [comment] 2023-10-30 20:03
I'm seeing the same behavior when using https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.compiled.js. When the video starts to play and I seek to a few seconds before the end of buffer, new segments are not fetched until the player is out of buffer.

**Comment by avelad** [comment] 2023-10-31 14:55
@wjywbs I have tried to reproduce it but I have not been able to, can you share a video of the Shaka demo just in case I do something wrong...

**Comment by wjywbs** [comment] 2023-11-08 13:58
Currently the nightly shaka player fails to play the video. Error: Cannot read properties of null (reading 'getIteratorForTime')

https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/m3u8s/11331.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

I will record a video with shaka player v4.5.0

**Comment by wjywbs** [comment] 2023-11-08 14:13
Here's a recording of this issue with shaka player v4.5.0:

https://github.com/shaka-project/shaka-player/assets/6233680/7c4acb0b-15ec-4a69-a055-e8d05c25a122

**Comment by avelad** [comment] 2023-12-04 16:02
Can you test if with version 4.7.0 the problem still occurs? Thank you!

**Comment by wjywbs** [comment] 2023-12-11 16:56
v4.7.0 has the same issue in v4.5.0

@shaka-bot reopen

**Comment by avelad** [comment] 2024-01-15 10:55
Can you check if the error still occurs in version 4.7.4? Thank you!

**Comment by wjywbs** [comment] 2024-01-15 19:24
Yes, this issue still happens in v4.7.4

**Comment by wjywbs** [comment] 2024-02-01 12:56
I comment out [this line](https://github.com/shaka-project/shaka-player/blob/v4.7.8/lib/media/streaming_engine.js#L1255) locally and this issue does not happen anymore.

**Closed** 2024-04-11 06:24 UTC
Labels: type: bug, component: HLS, priority: P1
