### ISSUE TITLE
Time-shifted HLS live playback stalls when actual live event ends

### ISSUE THREAD

**Issue by TommiRautanen** [shaka-project/shaka-player#6408] opened 2024-04-05 07:47 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not FairPlay related

**What version of Shaka Player are you using?**
4.3.4

**Can you reproduce the issue with our latest release version?**
Haven't tried.

**Can you reproduce the issue with the latest code from `main`?**
Haven't tried.

**Are you using the demo app or your own custom app?**
Custom Chromecast receiver using default Shaka v4.3.4

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**
-

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
`manifest.hls.useSafariBehaviorForLive=false` + `manifest.availabilityWindowOverride: 48 * 3600`

**What did you do?**
I played time-shifted live HLS TS stream.

**What did you expect to happen?**
When actual live event has ended, encoder adds `#EXT-X-ENDLIST` to the end of the playlist to signal end of the broadcast. But time-shifted playback should continue as source is still there.

**What actually happened?**
Shaka stalled playback. Only thing I noticed in the console was this warning and that Shaka has set absoluteStartTime to null:
<img width="727" alt="Screenshot 2024-04-05 at 10 04 01" src="https://github.com/shaka-project/shaka-player/assets/99327481/cc1cf21a-08db-4a3c-864b-fde92880cb93">

**Comment by TommiRautanen** [comment] 2024-04-05 12:07
@avelad do you think this is a bug in Shaka or perhaps there is some configurational thing I am missing? I can try and test on Monday using demo player.

**Comment by TommiRautanen** [comment] 2024-04-09 07:32
@avelad Shaka 4.7.11 in Chromecast seems to handle time-shifted HLS live playback better, it didn't stall playback but instead kept playing for some time. Any idea what change between versions 4.3.4 and 4.7.11 might've fixed this?

However, after playing the stream for a while following error was thrown to the console:
<img width="813" alt="Screenshot 2024-04-09 at 10 04 53" src="https://github.com/shaka-project/shaka-player/assets/99327481/5aaf73ed-53e4-40f1-858a-28cfc3b13500">

I managed to bypass this error by seeking forward until it occured again.

**Comment by avelad** [comment] 2024-04-09 07:37
In order to fix this, we need a test stream (if we can customize the start and end parameters of the event that would be ideal)

**Comment by CarlLindqvist** [comment] 2024-04-09 07:59
This last error with the "Possible encoding problem" seems to be an issue with handling TS rollover, which happens in this segment. I have saved that part here as a short test clip for easy replication of the issue:
https://downloads.a2d.tv/tswrap/av.m3u8

**Comment by avelad** [comment] 2024-04-09 08:01
TS rollover is implemented in https://github.com/shaka-project/shaka-player/pull/6363 and will be released in 4.7.12. Thanks!

**Comment by avelad** [comment] 2024-04-10 11:23
Can you review if the issue is resolved in 4.7.12? Thanks!

**Comment by TommiRautanen** [comment] 2024-04-12 07:28
4.7.12 seems to work!

**Comment by avelad** [comment] 2024-04-12 07:31
Thanks!

**Closed by avelad** 2024-04-12 07:31 UTC
Labels: type: bug, status: waiting on response, component: HLS, platform: Cast
