### ISSUE TITLE
Abr Manager Variants out of sync on multi period live DASH playout

### ISSUE THREAD

**Issue by jlnabais** [shaka-project/shaka-player#3048] opened 2020-12-15 09:47 UTC
We are experiencing a problem on live (linear) streams, where after a new period is parsed and latter the bandwidth changes, on the adaptation event, then if we query the available tracks to get the selected bitrate, we get to a point where there's no active track

This happens because the ABR Manager variants are not updated, making the streaming engine `currentVariant_` also outdated, when the ABR manager suggests a new bandwidth, latter when compared with the manifest variants of the player will not match any since the player holds reference to the new Manifest variants.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
`master` branch (commit `ed953bf76cd90e5cdabd9071c14035ff4b442d00 `)

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
Using the demo app with a few changes, for logging (see patch file appended).
[patch.diff.zip](https://github.com/google/shaka-player/files/5690463/patch.diff.zip)

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
macOS Mojave 10.14.6 (18G6020)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://skyglobal-my.sharepoint.com/:x:/g/personal/joao_nabais_sky_uk/EbXNloRdYSREpl4RvbXOs7oB2Kb-kpILbf0-_1ykCNoh2w?e=xkTWQY

**What did you do?**

1 - Play the stream;
2 - On chrome dev tools force a bitrate change (using for instance `Slow 3G` setting);
3 - See a log like: `[Changed Bitrate] TRAKCS: false,false,false,false,false,true`, indicating that there is an active track (the `true` one);
4 - Wait for a new period to be detected on the DASH Manifest (should see a log like: `[Changed Bitrate] NEW PERIOD DETECTED`);
5 - Force the stream to another bitrate again (using for instance `online` setting) on chrome dev tools;
6 - By this point you should be able to see a log indicating that theres in no active track (all `false`) :
    `[Changed Bitrate] TRAKCS: false,false,false,false,false,false`

**What did you expect to happen?**
To always have an active track

**What actually happened?**

We get to a point where there are no active tracks

**Comment by jlnabais** [comment] 2021-01-04 09:27
Hello 👋 
Any update on the above?

**Comment by TheModMaker** [comment] 2021-02-23 21:49
I can't access the URL you provided.

**Comment by jlnabais** [comment] 2021-03-24 16:35
@TheModMaker I think this was reproducible with any live (multeperiod) stream.

**Comment by TheModMaker** [comment] 2021-03-24 16:55
I can reproduce with `Tears of Steel (live, DASH, Server Side ads)`.

**Comment by ismena** [comment] 2021-04-23 23:56
Changing priority since this doesn't directly affect playback.
We are working on this, but won't hold the 3.1 release for it. If it's not fixed by the end of next week, it'll go into 3.2.

**Comment by avelad** [comment] 2021-07-13 18:13
@ismena I think this error produces: https://github.com/google/shaka-player/issues/3431 and https://github.com/google/shaka-player/issues/3510

**Comment by caridley** [comment] 2021-07-21 14:20
> @ismena I think this error produces: #3431 and #3510

I agree that fixing this problem should fix #3510

I do not think that fixing this problem will fix #3431 which is caused by a loss of period specific bitrates during period flattening.

**Comment by avelad** [comment] 2023-01-30 08:47
Can you test with 4.3.3? Thanks!

**Closed** 2023-02-06 09:43 UTC
Labels: type: bug, status: waiting on response, priority: P2, component: DASH
