### ISSUE TITLE
Adaptive protection mode based on Widevine keys requirement?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6436] opened 2024-04-11 19:51 UTC
We have a dash playlist with multiple tracks; our widevine license server sends some of them to be viewed in L3 devices and others (higher qualities) in L1.
However, if we send all of them, we do not get the ability to display only the keys that the system can, instead, we get error 6001 for the full content.

Is there any workaround for this?

Thanks!

**Comment by avelad** [comment] 2024-04-12 17:44
@joeyparrish can you review it?

**Comment by caridley** [comment] 2024-04-16 13:58
Fixing this problem is also a high priority for us. We entered this ticket in July of 23- https://github.com/shaka-project/shaka-player/issues/5421.

**Comment by avelad** [comment] 2024-04-17 11:01
@caridley @MarianoFacundoArch If someone provides me with the proper streams with this case, I can try to make a fix for this.

**Comment by MarianoFacundoArch** [comment] 2024-04-17 13:51
I can try to provide a stream with the case. 
Any config of your choice? I would do 

For video tracks:
HD, UHD1, UHD2: HDCP V2_2 - HW_SECURE_ALL
SD: HDCP_NONE - SW_SECURE_CRYPTO

Audio:
Default - SW_SECURE_CRYPTO - HDCP_NONE

---
Does that config sound good?

**Comment by caridley** [comment] 2024-04-17 16:48
I just sent a stream and DRM URL to shaka-player-maintainers@googlegroups.com

**Comment by avelad** [comment] 2024-04-19 11:57
I have received @caridley stream and can reproduce the error, since there is an open issue and this is a question. I'm closing the question and will start working on resolving https://github.com/shaka-project/shaka-player/issues/3051 asap.

**Closed by avelad** 2024-04-19 11:57 UTC
Labels: type: question, component: Widevine

**Comment by avelad** [comment] 2024-04-19 13:59
@caridley FYI: https://github.com/shaka-project/shaka-player/pull/6457 (still in progress)
