### ISSUE TITLE
High memory pressure with live dash playback

### ISSUE THREAD

**Issue by Illmatikx** [shaka-project/shaka-player#6070] opened 2024-01-10 09:14 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not applicable

**What version of Shaka Player are you using?**
4.7.0

**Can you reproduce the issue with our latest release version?**
Not tested, but compared the branch against 4.7.0

**Can you reproduce the issue with the latest code from `main`?**
Not tested, but compared the branch against main

**Are you using the demo app or your own custom app?**
Custom app (just a page with shaka player)

**If custom app, can you reproduce the issue using our demo app?**
Not tried

**What browser and OS are you using?**
Web: Windows Chrome 120.0.6099.199 (Official Build) (64-bit)
webos 4,6: chromium 53 and 79 respectively
tizen 4: chromium 56

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
webos 4: 43UM7300PLB (2019)
webos 6: 43UP81006LA (2021)
tizen 4: UE43NU7400U (2018)

**What are the manifest and license server URIs?**
I will send you the URL via email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Player configuration is attached.
[player_config_web.txt](https://github.com/shaka-project/shaka-player/files/13884569/player_config_web.txt)

**What did you do?**
Started playback of identical live dash stream with 4.3.0 and 4.7.0 shaka versions and kept it up to 2 hours. I monitored memory with distinct tools (depending on the platform), but namely on web I made heapdumps every 10-30 minutes.

**What did you expect to happen?**
Memory footprint should not be growing after buffer filling for 4.7.0 (as it is true for 4.3.0). Also, memory allocation rate should be smaller for 4.7.0 similar to 4.3.0 (tested on smart tv devices with webos 4/6 and tizen 4). 

**What actually happened?**
Shaka 4.7.0 memory footprint grew over time during live playback (no interaction with the custom demo app, tested on web and webos 4/6). Allegedly, memory growth depends on DVR window size since it stabilized after 60 minutes of test on web (timeShiftBufferDepth is 1 hour). During two tests I observed heap reaching 39 and 68 MB respectively whereas with shaka 4.3.0 playback its size was around 11-12 MB.
![shaka-smtvweb-heapdumps](https://github.com/shaka-project/shaka-player/assets/30461882/f4439cce-2d31-49d2-ae8b-dd12da238e9c)
Another one issue - memory allocation/clean up magnitude is much higher for 4.7.0 in comparison to 4.3.0 under the same testing conditions (tested on webos 4/6 and tizen 4 with 1h DVR). The consequence of high memory pressure on low-end smart tv devices is UI freezing during interaction with the app: OS and browser are busy with memory housekeeping tasks like swapping, GC, OS level memory allocation delays etc. Mere live playback with our own app started to freeze on webos 4 2019 device after ~15 minutes without any UI interaction.
![webos6_shaka_470_memory](https://github.com/shaka-project/shaka-player/assets/30461882/72b44960-a2bd-408b-9597-6a8272383397)
![webos6_shaka_430_memory](https://github.com/shaka-project/shaka-player/assets/30461882/f41af9a3-7907-48d6-8717-1757991d49c3)

Heapdumps comparison refers to memory kept by SegmentIndex/XML DOM data structures. As for high memory allocation rate, I am pondering about evict() changes in TimelineSegmentIndex class:  slice() was added to timeline and references objects, which is about shallow copies of arrays (relevant changes may be in https://github.com/shaka-project/shaka-player/pull/5061).

**Comment by nrcrast** [comment] 2024-01-17 14:36
Interesting. I will start to investigate this a bit too. Maybe using `splice` instead of `slice` would avoid some of the extra allocations.

**Comment by OrenMe** [comment] 2024-01-17 15:16
Thanks for the feedback @ricardo-a-alves-alb and thanks @nrcrast, sounds like u might know possible root cause, we were about to start doing bisect to find the PR that started it but from these comments maybe u can spot it faster then us

**Comment by nrcrast** [comment] 2024-01-17 15:21
It's probably just the PR that introduced the TimelineSegmentIndex -- #5061. Not 100% sure but that was a large change and I'd imagine if there was a memory issue with it, it would have been there since the beginning.

**Comment by OrenMe** [comment] 2024-01-17 15:39
I remember this PR, and I actually think @avelad mentioned it to me on another issue related to performance on smart TV but we didn't notice improvement with VST specifically and assumed our app might consume too much memory maybe to feel the gains so we started improving more on FE side.
I also suspect that if you do not see this issue it might be related to dash manifest features, and maybe specific manifests suffer more than others, just a guess but it seems you did impressive work in that PR and I believe u would have saw such issues.
Are you able to check this and maybe create some PR? I will be able to test it on our side and provide a feedback

**Comment by nrcrast** [comment] 2024-01-19 14:40
I think I've found one of the issues -- the `initSegmentReference` sticks around forever. When all references have been evicted from the `TimelineSegmentIndex`, we should be freeing everything we can so it can be garbage collected. 

At that point, the `TimelineSegmentIndex` really only exists as a shell to keep track of `numEvicted`.

**Comment by OrenMe** [comment] 2024-01-22 15:13
@nrcrast thanks for the update, any chance you are planning to push this fix so we can test it?

**Comment by nrcrast** [comment] 2024-01-22 15:46
Hi! I will push at some point this week. I want to do some long running tests here myself so I'm confident in the fix myself before I push anything. I can push a branch though at some point if you want to do some preliminary testing before I open a PR.

**Comment by Iragne** [comment] 2024-01-26 09:53
> I think I've found one of the issues -- the `initSegmentReference` sticks around forever. When all references have been evicted from the `TimelineSegmentIndex`, we should be freeing everything we can so it can be garbage collected.
> 
> At that point, the `TimelineSegmentIndex` really only exists as a shell to keep track of `numEvicted`.

you mean in the release function of "shaka.dash.TimelineSegmentIndex" we should also this.initSegmentReference_ = null;

Happy to check your branch, i'm testing it too

**Comment by nrcrast** [comment] 2024-01-26 15:30
It cannot be released in the `release` method, as the init segment reference can only be released once it's guaranteed that the SegmentIndex has evicted all of its entries. 

The issue with releasing _everything_ in the overridden `release` method is that `release` is called also when you switch variants. When you switch variant, the segment index for Variant A is closed and then re-opened if you then switch back to that variant. At that time, all information needed to re-create the segment index must still exist somewhere in memory. 

I am still chasing down the issue here -- it seems that for some reason even though I'm setting `initSegmentReference` to null in the TimelineSegmentIndex, something is still holding onto it preventing it from being garbage collected. 

I've just made a branch with this change in it as well as using splice if you also want to do some testing:
https://github.com/nrcrast/shaka-player/tree/timeline-segment-index-free-all

**Comment by Iragne** [comment] 2024-01-27 10:05
Hi @nrcrast  I tried to chase it down till the segment reference "partialReferences" and "initSegmentReference" but i'm not sure it's correct. 

Thanks for the information about release and it's at the end what i thought reading more deeply the code.

**Comment by Illmatikx** [comment] 2024-01-30 10:40
Hello. Seems that leaking memory and high allocation rate are still present in timeline-segment-index-free-all branch.
![shaka-webos6-retest](https://github.com/shaka-project/shaka-player/assets/30461882/db9fb1e5-4380-49e7-afa9-fa5c9a459760)
Heap snapshots for the same demo app (shaka live playback with a hardcoded fullhd channel) on web:
![image](https://github.com/shaka-project/shaka-player/assets/30461882/efc732c6-30ff-486f-b33c-659d60754534)
The said heap snapshots with debug build:
[debug-smtv-web-shaka.zip](https://github.com/shaka-project/shaka-player/files/14095985/debug-smtv-web-shaka.zip)
Some thoughts on the heap leak:
references arrays of two TimelineSegmentIndex (playing audio and video) grow over time due to growing amount of SegmentRefernce elements. Each of them retains ~9 KB of heap memory through InitSegmentReference after its assigning:
![shaka-web-retest](https://github.com/shaka-project/shaka-player/assets/30461882/8620823a-024a-40fa-94d8-5ea1bb1d4a42)
As of high memory allocation rate:  tizen/webos tests reveal that it fluctuates by magnitude of up to 50-70 MB and it happens not within the heap itself. It is up to native memory underlying data structures, which in turn may be related to dash manifest in-memory manipulation changes.

**Comment by nrcrast** [comment] 2024-01-30 14:32
Interesting. From what I can tell, the eviction logic in the TimelineSegmentIndex seems to work pretty much the same way as the eviction logic in the base SegmentIndex, plus it only creates SegmentReference objects when it's asked to. 

So I'm surprised at the number still remaining. That's definitely concerning.

**Comment by nrcrast** [comment] 2024-01-30 15:09
Some more interesting info! 

Here is a comparison of my fork of v3.3.10 on the left and current shaka main on the right. Both contain the Timeline Segment Index, but my fork does not contain #5762 or any other changes that happened since my initial contribution. 

![image](https://github.com/shaka-project/shaka-player/assets/5086301/09607c67-1d82-404d-a751-27161dcadb2d)

Going to play the "binary search" game and see if I can reproduce similar results using official shaka releases and not my own fork.

**Comment by nrcrast** [comment] 2024-01-30 16:25
![image](https://github.com/shaka-project/shaka-player/assets/5086301/c8bd3659-50aa-4948-9432-65926f509f6f)

Comparison of current main Shaka (on right) and commit 8d2b6574de6d0510ae752637c3507df93fbf3591 (https://github.com/shaka-project/shaka-player/pull/5842). This is after a bug fix for a race condition in the Timeline Segment Index. So seems like something went sideways sometime after this. 

Continuing the hunt!

**Comment by Illmatikx** [comment] 2024-01-30 21:12
> Have we checked if #5762 had any impact? I have no reason to suspect that it did, but it would be an interesting test.
I just tagged and checked 2 versions from timeline-segment-index-free-all branch on web: a commit right before #5762 (#5848 ) and #5762 itself. Looks like the heap size is quite stable, no known memory leak being detected:
![image](https://github.com/shaka-project/shaka-player/assets/30461882/09e05e82-e703-4a3a-bf33-d93835370732)

**Comment by Illmatikx** [comment] 2024-01-31 12:22
Seems that I found the root cause (checked on web and webos 6 for memory leaking atm) - #5899 
calling appendTemplateInfo() of TimelineSegmentIndex on manifest arrival assigns init segment references by this.initSegmentReference_ = initSegmentReference and thereby "binds" the referenced data to the long-living object.
Compared tagged build of PR #5899 vs its preceding #5729  (4.6 release).
web:
![image](https://github.com/shaka-project/shaka-player/assets/30461882/eb4b637c-2441-4c98-bcaa-6bf09dc5ad8e)
webos 6:
![webos6-PR-5899-memory-comparison](https://github.com/shaka-project/shaka-player/assets/30461882/51d02d1d-dc3f-40c3-8a02-2f590adbb3a1)

Memory allocation magnitude is still high on webos 6 for dash live playback: 
1. 25-30 MB for 4.3 release.
2. 45-55 MB for #5729 build (release 4.6).
3. 70-80 MB for timeline-segment-index-free-all branch. 
One need to perform some additional investigation of that on TV devices.

**Comment by nrcrast** [comment] 2024-01-31 14:09
Interesting. 

I don't fully understand though what the real difference is or how that PR could cause this. Even before that PR, the TSI was holding a reference to an initSegmentReference -- that PR just makes it so that reference changes periodically. 

It's also unclear to me why my `timeline-segment-index-free-all` wouldn't have fixed this issue. 

Something isn't quite adding up for me 🤔

**Comment by OrenMe** [comment] 2024-01-31 14:18
We are testing it commit by commit so hard to tell. One thing that can be a gotcha is that the code we see and code we ship is not the same in JS land. Maybe the code change seems safe but maybe compiled code optimizes and creates some closure.

**Comment by Illmatikx** [comment] 2024-01-31 14:52
According to heapdumps, we assign init segment references to initSegmentReference property of SegmentReference objects on fresh manifest arrival and appendTemplateInfo() calls. TimelineSegmentIndex and its references array have a lot of SegmentReference elements: with 1h DVR it is about 1800+ for video and audio indexes respectively. 
![image](https://github.com/shaka-project/shaka-player/assets/30461882/ce89c69b-a790-4daf-ad81-8b8b983d3c06)

**Comment by nrcrast** [comment] 2024-02-01 15:42
> According to heapdumps, we assign init segment references to initSegmentReference property of SegmentReference objects on fresh manifest arrival and appendTemplateInfo() calls. TimelineSegmentIndex and its references array have a lot of SegmentReference elements: with 1h DVR it is about 1800+ for video and audio indexes respectively. ![image](https://private-user-images.githubusercontent.com/30461882/301202772-ce89c69b-a790-4daf-ad81-8b8b983d3c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDIxMzAsIm5iZiI6MTcwNjgwMTgzMCwicGF0aCI6Ii8zMDQ2MTg4Mi8zMDEyMDI3NzItY2U4OWM2OWItYTc5MC00ZGFmLWFkODEtOGI4Yjk4M2QzYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMjc1MGY1ZDEwMzI4MDdkNmY2ZTg4N2EwODU1NGU0ZjM0NzBmNDUyN2VhODM2OGM0MTJjMjk3ZTZhZGUwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eGFh4zh67AcFtUX-B9HJiXtn8b5i2WHqDqRdfMf2n2k)

@Illmatikx I think this has always been the case, though. 

Before the Timeline Segment Index was introduced, all of these SegmentReferences were created during manifest parse time, and each Segment Reference had a ref to the InitSegmentReference. 

With the introduction of the Timeline Segment Index, these Segment References are only created upon retrieval (`SegmentIndex.get`). 

@OrenMe The only difference between your two tests was that single commit for https://github.com/shaka-project/shaka-player/pull/5899? It just seems like such an innocuous change! @avelad any idea? 

Maybe this is some weird compilation issue, but on a linear stream Segment References will be periodically evicted. They should then be garbage collected. As long as there is no other reference to the InitSegmentReference (which I tried to fix in my branch), the InitSegmentReference should be collected as well eventually. 

In practice, I must be missing something, because it's not happening that way 😆 .

**Comment by Illmatikx** [comment] 2024-02-01 17:53
@nrcrast  hello! Yes, the only difference during the last test was #5899 
I think the problem is that TimelineSegmentIndex is a long-living object and it keeps the references itself (references-> SegmentReference -> InitSegmentReference). For the duration of availability window - 1+ hour with 1h DVR - the references are not evicted, hence memory leaks for an hour for our streams. Before the said commit appendTemplateInfo() didn't assign initSegmentReference, which in turn retains 9-20 KB of memory per each SegmentReference object.

**Comment by nrcrast** [comment] 2024-02-08 15:07
Before the said commit, though, initSegmentReference was still in TimelineSegmentIndex. 

Ah maybe it's that appendTemplateInfo re-assigns `initSegmentReference` so it's keeping a bunch of different `initSegmentReference` objects in memory instead of just having all of the references in the TSI _share_ the same `initSegmentReference`. 

I'm not really sure of a solution, to be honest, as I don't have much context around #5899 . 🤔

**Comment by Illmatikx** [comment] 2024-03-13 08:29
@nrcrast Greetings! Any updates on the subject maybe?

**Comment by Illmatikx** [comment] 2024-03-13 08:36
Greetings! @nrcrast @avelad maybe any updates or thoughts on the subject?

**Comment by Illmatikx** [comment] 2024-03-19 13:02
I have conducted some memory tests on webos 6 2021 device with beanviser. The purpose was to compare distinct shaka versions and seek for any difference in terms of memory allocation during live dash playback. The results are the following:
![image](https://github.com/shaka-project/shaka-player/assets/30461882/1d8dbb44-dbd8-4f13-ab2a-417ba262d737)
I am thinking of #5061 added in 4.4 being a culprit for the memory usage growth: it may be improving manifest parsing time at the cost of excessive memory pressure, which in turn is the most costly resource on low-end smart tv devices (on par with main thread availability). The memory pressure presumably became even worse with shaka 4.6.1 #5899 - the PR introduced the ticket subject memory leak through addition of initSegmentReference parameter to appendTemplateInfo().

**Comment by avelad** [comment] 2024-04-26 11:01
Does anyone want to submit a PR that improves what was implemented in https://github.com/shaka-project/shaka-player/pull/5899 to reduce the pressure? Thanks!

**Comment by cristian-atehortua** [comment] 2024-04-26 19:00
I created a branch with the suggested change in the last comment: https://github.com/cristian-atehortua/shaka-player/tree/bugfix/6070--high-memory-pressure

Can you please help me to test behavior and memory usage?

@pszemus Since this is related to a bug fix of an issue you reported, can you please help me test how your streams work on that branch?

**Comment by avelad** [comment] 2024-04-29 10:57
I share some reduced MPDs of the problem that occurred:

1º
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:scte35="urn:scte:scte35:2013:xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="dynamic"
     minimumUpdatePeriod="PT5.18S" 
     publishTime="2024-04-29T10:53:08.094Z" 
     availabilityStartTime="2022-01-01T00:00:00.000Z" 
     timeShiftBufferDepth="PT25.0S"
     suggestedPresentationDelay="PT20.0S" 
     minBufferTime="PT6.0S">
<Period id="0" start="PT0.0S">
    <EventStream timescale="90000" schemeIdUri="urn:scte:scte35:2013:xml"></EventStream>
    <AdaptationSet id="0" group="1" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" par="16:9" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate timescale="90000" media="segment_6740c147d_ctvideo_cfm4s_rid$RepresentationID$_cs$Time$_mpd.m4s" initialization="segment_6740c147d_ctvideo_cfm4s_rid$RepresentationID$_cinit_mpd.m4s">
            <SegmentTimeline>
                <S t="6605347805640" d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0va0br150000" codecs="avc1.42c00c" width="256" height="144" sar="1:1" bandwidth="150000" />
    </AdaptationSet>
</Period>
</MPD>
```

After some time:
```

<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:scte35="urn:scte:scte35:2013:xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="dynamic"
     minimumUpdatePeriod="PT5.127S" 
     publishTime="2024-04-29T10:53:43.097Z" 
     availabilityStartTime="2022-01-01T00:00:00.000Z" 
     timeShiftBufferDepth="PT25.0S"
     suggestedPresentationDelay="PT20.0S" 
     minBufferTime="PT6.0S">
<Period id="0" start="PT0.0S">
    <EventStream timescale="90000" schemeIdUri="urn:scte:scte35:2013:xml"></EventStream>
    <AdaptationSet id="0" group="1" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" par="16:9" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate timescale="90000" media="segment_b2415eee8_ctvideo_cfm4s_rid$RepresentationID$_cs$Time$_mpd.m4s" initialization="segment_b2415eee8_ctvideo_cfm4s_rid$RepresentationID$_cinit_mpd.m4s">
            <SegmentTimeline>
                <S t="6605350955640" d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
                <S d="450000"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0va0br150000" codecs="avc1.42c00c" width="256" height="144" sar="1:1" bandwidth="150000" />
    </AdaptationSet>
</Period>
</MPD>
```

@cristian-atehortua It is valid to update the old segments and it is what should be done.

I'll be happy to review your PR

**Comment by avelad** [comment] 2024-04-29 12:14
I have tested it and it works fine with the stream I had to fix, can anyone confirm that it reduces memory pressure?

**Comment by OrenMe** [comment] 2024-04-29 12:17
Hi @avelad l'll be back from holiday tomorrow and check if we can do a quick test

**Comment by cristian-atehortua** [comment] 2024-04-29 12:45
Apart from that, do you think it is appropriate to create a new `initSegmentReference` on each call to `SegmentTemplate.createStreamInfo`?

Shouldn't we check if the properties used to create the `initSegementReference` have changed and only in that case create a new one?

**Comment by avelad** [comment] 2024-04-29 13:41
> Shouldn't we check if the properties used to create the `initSegementReference` have changed and only in that case create a new one?

Yes, please do it

**Comment by avelad** [comment] 2024-05-06 15:22
@Illmatikx Can you share the same comparison against 4.8.1? Thanks!

**Comment by Illmatikx** [comment] 2024-05-06 17:23
@avelad that is the plan from my side, but I am blocked atm by https://github.com/shaka-project/shaka-player/issues/6533 
I managed to run some heap memory comparison tests on web though and 4.8.1 looks fine in terms of the notorious memory leak:
![shaka481-memory-test](https://github.com/shaka-project/shaka-player/assets/30461882/635a54be-432d-4169-a2c9-6a2a54fc0f15)
I intend to run the test on a webOS device and monitor memory allocation rate with the changes. It is a must for us since UI scrolling freezes were caused not by the leak but by high memory allocation.

**Comment by avelad** [comment] 2024-05-09 15:17
@Illmatikx Yesterday we released 4.8.3, can you test on WebOS if this issue is fixed now?

**Comment by Illmatikx** [comment] 2024-05-20 10:55
Hello @avelad sorry for the late response, but I managed to take a glance at 4.,8.4 version with our demo app. The test targeted a start-over video with 15h35m timeShiftBufferDepth. so It was a kind of an edge use case.
Memory allocation magnitude has reduced from 40-65 (shaka 4.6.1) to 5-8 MB on account of manifest processing changes for TImelineSegmentIndex.
![memory-allocation-shaka-comparison](https://github.com/shaka-project/shaka-player/assets/30461882/eabbacff-49cd-4cc7-b68d-1aba75ea2a3c)
At the same time, there was still a "benign" leak observed on webos 6 device, which is about TimeSegmentIndex in-memory structure itself:
![memory-trend-shaka484](https://github.com/shaka-project/shaka-player/assets/30461882/4afd93a9-4752-440d-b497-9382e5d1fe3b)
It was about leaking a couple of dozens of MB during 1h20m test.

**Comment by Illmatikx** [comment] 2024-05-24 09:33
@avelad is it doable to enable/disable usage of TimelineSegmentIndex from https://github.com/shaka-project/shaka-player/pull/5061 by a flag/configuration option? This way one can opt for each specific use case: either go for manifest parsing time improvement or memory saving,

**Comment by avelad** [comment] 2024-05-28 13:54
@Illmatikx can you test if https://github.com/shaka-project/shaka-player/issues/6610#issuecomment-2110138873 reduce the pressure? (It seems like a bit of an ugly hack, but... I would be willing to add it if it works for everyone). Thanks!

**Comment by avelad** [comment] 2024-07-15 15:34
In version 4.10.6 we have introduced some improvements, can you validate if it is enough or do we need more improvements? Thanks!

**Closed** 2024-07-23 07:37 UTC
Labels: type: bug, type: performance, priority: P1, component: DASH
