### ISSUE TITLE
HLS/TS multi-audio A/V sync

### ISSUE THREAD

**Issue by rauldelperal** [shaka-project/shaka-player#4599] opened 2022-10-19 15:05 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;panel=CUSTOM%20CONTENT;build=uncompiled
https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://directes-test.ccma.cat/live-origin/tv3-hls/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.2.2-uncompiled

**What browser and OS are you using?**
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"

**What did you do?**
We don´t have added any changes on our side. We use the same Encoder version.
Since you have added to your v4 releases the commit "https://github.com/shaka-project/shaka-player/commit/36d0b5484fad68dc1d640fbddf2fae3e1eb7169b" there is an A/V sync error playing an HLS/TS Multi-audio Livestream through Shaka-Player v4.X.X. If you try with older versions, this error does not appears.

**What did you expect to happen?**
Shaka-player should be able to A/V sync these type of HLS/TS Live Streams like others players do.

**What actually happened?**
An a clear A/V sync error.

**Comment by joeyparrish** [comment] 2022-10-19 22:37
Thank you for the report.  We'll look into it!

**Comment by joeyparrish** [comment] 2022-10-19 22:39
Possible duplicate of #4589

**Comment by JBurgosCires21** [comment] 2022-11-11 12:10
Hi! Is there any update on this issue?

Regarding your last comment @joeyparrish, we do not think this is exactly a duplicate of that issue, because in our case there is no need of any ad break, the issue is always there. You can see we are emitting an HLS stream correctly formed in [this URL](https://directes-test.ccma.cat/live-origin/tv3-hls/master.m3u8), and the desynchronization can be seen in any version of shaka player that includes the commit 36d0b54. 
You can check it directy [here](https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://directes-test.ccma.cat/live-origin/tv3-hls/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled).

**Comment by theodab** [comment] 2022-12-06 07:37
For whatever reason, it looks like some of the changes from https://github.com/shaka-project/shaka-player/commit/89409cee3eaeb6764dbc191b7408bf45eecdced3 (the PR that should be responsible for A/V sync after https://github.com/shaka-project/shaka-player/commit/36d0b5484fad68dc1d640fbddf2fae3e1eb7169b) were undone. I believe there must have been a problem when merging with https://github.com/shaka-project/shaka-player/commit/47fa3093e1462d0bcca87238dc4886b9e2c1f8f4, which also changes the logic behind appending buffers.
Because of that, we read `EXT-X-PROGRAM-DATE-TIME` from the manifest and store it internally, but never actually use it for anything besides logs.

**Comment by theodab** [comment] 2022-12-10 08:59
Okay, I think I was wrong in my previous statement. I had forgotten about https://github.com/shaka-project/shaka-player/commit/314a987ecf85b47cc8a6cef08f390ef817e11c49, which changed how `EXT-X-PROGRAM-DATE-TIME` was handled, so I had been looking in the wrong part of the code.

I did a git bisect, and I think the actual problem is https://github.com/shaka-project/shaka-player/pull/4338.
I did a few manual test runs, where I downgraded mux.js to v6.1.0 and looked for A/V sync issues. I don't... think I am seeing the issues anymore with mux.js downgraded, though I will admit that I am not that great at telling if someone's mouth matches up to the sound of their voice when they're speaking a language I don't.

That's where I'll have to sign off on this for now. I'll be going on break after today.

**Comment by joeyparrish** [comment] 2022-12-12 21:01
It's time-consuming to bisect this issue, because ad breaks tend not to have visible speech, and use voiceovers or on-screen titles instead.  (Presumably because these are easier to localize and run across regions.)

**Comment by joeyparrish** [comment] 2022-12-12 21:16
And some programs are dubbed foreign TV shows. :cry: 

I'm frequently unable to accurately judge lip sync on this content.  But what I've seen so far is that I can't tell any difference between any combination of `main`, `v4.0.0`, mux.js v5.14, and mux.js v6.2.  All appear off, but only very slightly (sub-second, can't judge how far).

So I'm analyzing the segments for now instead.  I'm checking to see if the contents of the TS segments agree with the metadata in the HLS playlists.

Playlists all state that segments are exactly 6 seconds long, and `PROGRAM-DATE-TIME` is specified to the millisecond, but always ends with `.000`.

**Comment by joeyparrish** [comment] 2022-12-12 21:25
Presentation timestamps in the media do not agree with PROGRAM-DATE-TIME metadata.

For example:

`bitrate_3.m3u8`:

```
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:278479923
#EXT-X-PROGRAM-DATE-TIME:2022-12-12T19:12:17.000+0000
#EXTINF:6,
0/br3/221117115102/92827/geo2-br3_278479923.ts
```

Actual PTS: 7803148816


`bitrate_7.m3u8`:

```
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:278479924
#EXT-X-PROGRAM-DATE-TIME:2022-12-12T19:12:22.000+0000
#EXTINF:6,
0/br7/221117115102/92827/geo2-br7_278479924.ts
```

Actual PTS: 7803561136

The `PROGRAM-DATE-TIME` metadata says these should be played at 5s apart.  However, the timestamps are 4.58133 seconds apart.  This would suggest desync of about 419 ms, which is roughly consistent with what I observed in the native-Catalan programs I was able to observe this morning.

7803561136 - 7803148816 = 412320
412320 / 90k = 4.58133

As far as I can tell, inaccuracy in the playlist's `PROGRAM-DATE-TIME` is to blame for this content being out of sync.

The reason v3 played this content is because we used a much higher-latency startup process to extract timestamps from media instead of MSE sequence mode, and we used that extracted timestamp information instead of `PROGRAM-DATE-TIME` to sync the content.

@rauldelperal, can you confirm my findings?

Lowering priority, tentatively marking this as bad content.  I will prioritize #4589 now (previously suspected of being a duplicate), in case there is a separate AV sync issue there.

**Closed** 2023-01-20 16:10 UTC
Labels: type: bug, status: waiting on response, status: bad content, component: HLS, priority: P2
