### ISSUE TITLE
IMA SDK preroll survey not working properly

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-player#2597] opened 2020-05-28 18:23 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest master

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
your nighttly demo

**What browser and OS are you using?**
Mac OS + Chrome

**What are the manifest and license server URIs?**
Big bunny video from your demo + IMA SDK sample tag from page https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags called *SIMID Survey Pre-roll*  I believe those links expire after some time so Im not sharing link directly to the VMAP)

**What did you do?**
I entered the dash url and ad survey url into shaka nighly demo

**What did you expect to happen?**
I expected that the survey would work

**What actually happened?**
The survey options are not clickable when not in full screen. In fullscreen, it appears to be working fine

**Comment by ismena** [comment] 2020-05-28 18:33
@jakubvojacek 
Thanks for the report! I'll take a look later this week or early next one.
The note about the survey working in fullscreen males me think that it might be overlapping with some of our UI elements in the non-fullscreen mode. I will investigate.

**Comment by ismena** [comment] 2020-06-05 22:59
Hi @jakubvojacek 
Finally had a chance to look at this - sorry for the delay!

So, this is pretty weird - I was able to get into this state with the survey ad, but very inconsistently. About 1 time in 5-7 tries, and I'm having trouble figuring out what was different about the times it reproes.

Could I ask you a few things about your repro: do you get it every time? What asset are you adding the ad to? Is there some sort of a pre-requisite behavior to make the survey unclickable? (Like, did you interact with the UI first or something like that).

Thank you!

**Comment by jakubvojacek** [comment] 2020-06-09 08:51
Hello @ismena 

I too am having troubles reproducing it every time, I think it happens when I click on some of the ui elements, if I just refresh the page then without any interaction, it seems to be OK

Thank you
Jakub

**Comment by joeyparrish** [comment] 2020-08-17 23:26
I managed to reproduce the issue, and it's still an issue in our latest v3.0.3 release.  The trick to 100% repro is to load the page, load the video, close it, then load the video again.  After the third playback, I found that there were 3 different ad divs in our UI, each containing an iframe.  The ones on top prevent clicks from getting to the survey.  Instead, they seem to simply pause the video.

![no click - 3 iframes](https://user-images.githubusercontent.com/6843156/90453459-85f6ef80-e0a5-11ea-93f2-884b13b8cd8d.png)

It looks like something in the ad UI isn't being cleaned up properly.

To get this set up in the demo app, I used the following setup in the custom content tab:
  1. Manifest URL: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
  2. Name: 2597 - ads survey not clickable
  3. Ad Tag URL: https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/simid&description_url=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

**Comment by Leena-Sharma-rsys** [comment] 2022-05-04 05:29
hi @jakubvojacek 
i am using the same ima sample tag  from page https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags
and the javascript is not getting loaded in iframe from the html derived from pre roll survey. 
Is there anything we need to add third party support or something else ?
thank You!

**Comment by avelad** [comment] 2023-09-27 10:15
I tested the issue on 4.4.2 and the issue does not occur. I consider the issue resolved. Thanks!

**Closed by avelad** 2023-09-27 10:15 UTC
Labels: type: bug, component: UI, component: ads, priority: P2
