### ISSUE TITLE
Playback Speed resets to 1x

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#3709] opened 2021-10-20 22:52 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Brave, Linux

**What are the manifest and license server URIs?**
N/A, affects demo

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
The demo's configuration, I haven't changed anything.

**What did you do?**
Open the demo at https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=HOME;build=compiled

Wait for it to start auto-playing.

Pause the player.

Run `document.querySelector("video").playbackRate = 2` in the console.

Click on play again.

**What did you expect to happen?**
Video to play on 2x.

**What actually happened?**
Video played at 1x.

The issue also happens when you disable autoplay, set `playbackRate` and then click on the play button initially. (in the custom app)

**Comment by TheModMaker** [comment] 2021-10-21 20:05
This is caused by us canceling trick play when you click the UI button ([source](https://github.com/google/shaka-player/blob/221637a66c04d4fdc4767fea027c48a5601ac972/ui/controls.js#L615)).  As a workaround, you can set the `video.defaultPlaybackRate` to the value you want to use, or use `player.trickPlay(value)` to set the playback rate.

**Comment by avelad** [comment] 2023-11-28 10:47
The solution given by https://github.com/shaka-project/shaka-player/issues/3709#issuecomment-948962984 is the correct one, so I am going to close the issue.

**Closed by avelad** 2023-11-28 10:47 UTC
Labels: type: bug, component: UI, priority: P2
