### ISSUE TITLE
Startover, player stops when manifest chnages from 'dynamic' to 'static'

### ISSUE THREAD

**Issue by nikhilxperi** [shaka-project/shaka-player#6642] opened 2024-05-20 13:48 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

No related to FairPlay

**What version of Shaka Player are you using?**

3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome/Mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
shared over the email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
start the playback with end time as future time start the playback and then seek the playback in past 

**What did you expect to happen?**
when clock time reach to end time, manifest change from 'dynamic' to 'static'. that time playback should continue from seek position. 

**What actually happened?**
playback stop working.

**Comment by avelad** [comment] 2024-05-20 13:49
Duplicate of https://github.com/shaka-project/shaka-player/issues/2581

**Closed by avelad** 2024-05-20 13:49 UTC
Labels: type: bug
