### ISSUE TITLE
Safari rapid seek hangs stream

### ISSUE THREAD

**Issue by CHaNGeTe** [shaka-project/shaka-player#3367] opened 2021-04-23 13:52 UTC
**What version of Shaka Player are you using?**
3.0.10 and 2.5.21

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iPad mini 2 12.5.1
Chrome 87.0.4280.163 / Safari 12.5.2

**What are the manifest and license server URIs?**
https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multiple-subtitles.ism/.m3u8
Tears of Steel (HLS, Subtitles) from **All Content** tab

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multiple-subtitles.ism/.m3u8;panel=ALL_CONTENT;build=uncompiled;nativecontrols

Default configuration but with **native controls**

**What did you do?**
Load the stream, on the native controls click fullscreen, seek a big chunk by dragging timeline (not by short incremental seek buttons)

**What did you expect to happen?**
Player resumes after seeking a big chunk in fullscreen

**What actually happened?**
After seeking on fullscreen player "freezes", not resumes, there is no other way than cancelling fullscreen and seek again and click play to recover the player

**More info**
As Safari / Chrome on iPad allows to play m3u8 directly, I tried to load this same stream and do the same behaviour (fullscreen + seek) and it works correctly there.

**Comment by CHaNGeTe** [comment] 2021-04-23 14:42
btw, seems listening onSeeked event and setting 

document.querySelector('video').playbackRate = 1

is a hacky solution for this

**Comment by surajkumar-sk** [comment] 2021-04-23 17:10
@CHaNGeTe I am using chrome version 89.0.4389.114 windows 8.1. As far as I know, there won't be any significant difference in chrome's native player between IOS and windows. I tried reproducing the error using this link 
>> What configuration are you using? What is the output of player.getConfiguration()?
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multiple-subtitles.ism/.m3u8;panel=ALL_CONTENT;build=uncompiled;nativecontrols

I clicked on the fullscreen button, then dragged the seek bar using the mouse from time `0:13` to `11:57`. and waited for the video to load and the video started playing again within few seconds. 

and as per this line
>>btw, seems listening onSeeked event and setting
document.querySelector('video').playbackRate = 1
is a hacky solution for this

this actually cancels the shaka-player feature of maintaining the playback speed after seek.

could you tell me any other ways of reproducing this issue.

**Comment by joeyparrish** [comment] 2021-04-23 17:30
@surajkumar-sk wrote:
> I am using chrome version 89.0.4389.114 windows 8.1. As far as I know, there won't be any significant difference in chrome's native player between IOS and windows.

Suraj, this may surprise you, but iOS is completely different from everything else.  All browsers on iOS, including Chrome, are essentially Apple's Safari under the hood.  All playback on iOS is done with Apple's native HLS implementation.  On other platforms, playback is handled by Shaka Player through the MSE API, not with any "native player" at all.  This is (unfortunately) just how the browser/media ecosystem works at the moment.

@CHaNGeTe, thank you for the report.  Someone with an iOS device will need to reproduce and debug this issue, but unfortunately, that's not me.  @CHaNGeTe, do you have a Mac?  Does this issue occur on desktop Safari as well?  If so, that will make it easier to debug.  More of us have Mac laptops than iPhones.  (Still not me, though.)

**Comment by CHaNGeTe** [comment] 2021-04-23 18:05
@surajkumar-sk, totally agree with @joeyparrish, indeed the integration is even more tricky when speaking about fullscreen on iOS.

Safari on mobile/ipad didn't allow to go fullscreen the same way other browsers do, they have a kinda special integration where only the tag video can request fullscreen, this for example makes impossible to use custom controls on fullscreen.
Seems iPads got an update on this purpose, and now other elements can be fullscreen on Safari, but not in Chrome. While iOS AFAIK still only allows fullscreen for video (with native controls)

@joeyparrish a pleasure.
I do have a Mac. I didn't tested there before, but it seems it works on Chrome (the native UI is different).
But on Desktop Safari it fails as well. Indeed on desktop I reproduced the issue even without fullscreen. (Safari Version 14.0.2 (15610.3.7.1.10, 15610))

**Comment by surajkumar-sk** [comment] 2021-04-23 18:13
>> Suraj, this may surprise you, but iOS is completely different from everything else. All browsers on iOS, including Chrome, are essentially Apple's Safari under the hood. All playback on iOS is done with Apple's native HLS implementation. On other platforms, playback is handled by Shaka Player through the MSE API, not with any "native player" at all. This is (unfortunately) just how the browser/media ecosystem works at the moment.

Wow, that's new. I genuinely taught they were the same. I never doubted that it might be different, but I did google it few times and couldn't find a direct answer saying they were different. I'll remember this.
Thank you @joeyparrish.

**Comment by TheModMaker** [comment] 2021-04-27 20:49
Also reproduced on desktop even without fullscreen.  This probably has to do with repeated seeks since our UI delays all seeks until you release; whereas Safari seeks a bunch while dragging the seek bar.  We probably get stuck somewhere while seeking.  On a different note, for some reason, I can't see our verbose logs in the console on Safari.  Even with V2 logging, I can't see the StreamingEngine logs.

**Comment by joeyparrish** [comment] 2021-04-28 21:37
If we're using native HLS, StreamingEngine isn't involved, so you won't see those logs.

**Comment by zth** [comment] 2021-06-21 15:20
Can confirm this is also happening, and is pretty easy to reproduce (in the iOS simulator as well). It's a bit unfortunate because it's a blocker for us moving to Shaka on iOS, which we'd really like to do. Can we (outside of the Shaka team) do anything to help with this one?

Also, the workaround @CHaNGeTe mentioned about setting the playbackRate on seekend seems to work. Does that have any other implications, or is that a "safe" workaround?

**Comment by joeyparrish** [comment] 2021-06-21 22:33
I believe it's safe enough as a workaround, but I think this hints at a root cause, too.

We do a thing we probably shouldn't do, which is that we set playbackRate=0 when we detect that we're buffering.  This is a very old decision, and I'm nervous to reverse it without extensive testing on all supported platforms.

But you could try it for us on iOS and confirm if it helps.  If it does, this is good motivation to prioritize reversing our buffering-state-madness.

Please try changing the buffering rate from 1 to 0 in `lib/media/play_rate_controller.js`:

```js
  calculateCurrentRate_() {
    return this.isBuffering_ ? 1 : this.rate_;
  }
```

If this works well for iOS without any major side-effects, we can recommend an official workaround and start planning a permanent fix.

**Comment by zth** [comment] 2021-06-22 06:44
@joeyparrish thank you for your reply! I'll do a fairly comprehensive testing with that change and get back to you with the results.

Coming to think of it, I'm fairly sure we used to have this bug in all platforms before moving our custom controls to the same approach as the Shaka UI (that is, committing the seek only after the user seek input has settled, making it one seek instead of many rapid seeks). Back then, what happened was that Shaka seemed to get stuck in the buffering state after a number of quick, successive seeks. This seems in line with the events happening on iOS as well - whenever the bug appears, it's preceded by a single "buffering started" event, and no "buffering ended" event is dispatched regardless of what you then do.
Anyway, just some additional information.

**Comment by zth** [comment] 2021-07-02 16:57
@joeyparrish i haven't been able to run an own build of Shaka with the change, but we've been running the workaround setting playback rate via an event listener successfully in prod for a while now and it seems to work well.

**Comment by michellezhuogg** [comment] 2021-10-19 20:15
Update: got 404 error with the test manifest. Will try again later.

**Comment by Benny739** [comment] 2023-01-05 17:49
I just did some testing and the
```
document.querySelector('video').playbackRate = 1
```
hack seems to work for us as well. 
I have to set the playbackRate after the seeked event and also after the play event.

**Comment by Cell5** [comment] 2023-01-06 00:42
> I just did some testing and the
> 
> ```
> document.querySelector('video').playbackRate = 1
> ```
> 
> hack seems to work for us as well. I have to set the playbackRate after the seeked event and also after the play event.

Yep, it works for me too.
Using this workaround for several months so far

**Comment by avelad** [comment] 2023-11-07 11:33
Can you check if it's still happening on the main branch? thanks!

**Closed** 2023-11-14 11:36 UTC
Labels: type: bug, status: waiting on response, priority: P1, platform: iOS
