### ISSUE TITLE
TrickMode disengages in the middle of trick mode playback

### ISSUE THREAD

**Issue by TheJohnBowers** [shaka-project/shaka-player#2893] opened 2020-10-03 06:01 UTC
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4 as deployed on the app spot demo

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo Application

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Chrome macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
https://content.downlynk.com/34c2e8dc7078462a80fcf9c461ba0073.mpd?prettydash=1&ifo=1&vcodec=avc
https://content.downlynk.com/wv

**What did you do?**

Start playback -- Engage TrickMode to 8X and wait 

**What did you expect to happen?**
I expect it to playback to the end of the stream in trick mode since trick mode has the lowest bandwidth of any video representation.

**What actually happened?**
While trick mode engages initially, at some point it usually disengages and starts playing a normal track at high speed, sometimes buffering because the normal video tracks all have a higher bitrate than the trick mode track.

HINT -- This only happens when my content has 2 video adaptation sets - One with id=1 and one with id=2 (with adaptation set switching enabled).  My trick mode adaptation set is linked to the adaptation set with id=1 via the trick mode essential property:

<EssentialProperty schemeIdUri="http://dashif.org/guidelines/trickmode" value="1"/>

I cannot link it to both 1 and 2 I don't think because to playback this trick mode set you will need the license from adaptation set one to decrypt.  The license from adaptation set 2 will not contain the key to decrypt the trick mode track.   Something about this setup convinces Shaka to disengage trick mode....  When I have a single video adaptation set trick mode never disengages on me.  I have tried to imagine how I might change things in the dash manifest to avoid this, and I think this is a valid configuration.  I can stick all the keys into a single video license, but separating representations this way is not disallowed when adaptation set switching is signaled (as it is here).

Here is the same content configured with all the representations in the same adaptation set:

https://content.downlynk.com/34c2e8dc7078462a80fcf9c461ba0073.mpd?prettydash=1&ifo=1&vcodec=avc&singlevideolicense=1

(use the same license url as the first sample) -- 

These are the same segments everything else is the same, and trick mode will engage and never disengage.  It is clearly related to splitting the vid representations between 2 different adaptation sets.

**Comment by TheJohnBowers** [comment] 2020-10-03 06:03
Debug logs:

`all): seeked: buffered seek: presentationTime=0.066666
streaming_engine.js:280 setTrickPlay true
streaming_engine.js:292 Engaging trick mode stream {id: 5, originalId: "1", segmentIndex: null, mimeType: "video/mp4", createSegmentIndex: ƒ, …}
streaming_engine.js:431 switch: switching to Stream (video:5)
streaming_engine.js:516 Aborting current segment request.
2streaming_engine.js:280 setTrickPlay true
simple_abr_manager.js:278 Calling switch_(), bandwidth=4078 kbps
player.js:4515 switch_
streaming_engine.js:396 switch during trick play mode {id: 4, originalId: "B", segmentIndex: null, mimeType: "video/mp4", createSegmentIndex: ƒ, …}
streaming_engine.js:408 switch found no special trick play stream
streaming_engine.js:431 switch: switching to Stream (video:4)
streaming_engine.js:414 switch: Stream (audio:1) already active`

**Comment by TheModMaker** [comment] 2020-10-26 19:57
This has nothing to do with encryption; if we see a stream that we don't have the keys for, we'll filter them out.  We have all the keys we need in your case.  Also, you can set a `<cenc:pssh>` element in the trick play track that will cause us to fetch the license for it so we can have the keys for it whether we start with the high-res or low-res track.  Also note that if the track is encrypted, you must add a `<ContentProtection>` element.  If we think the track is clear, we may fail playback.

What is happening is there are two (conceptual) tracks, high-res and low-res.  Low-res has an associated trick play track and high-res doesn't.  We start playing the low-res since we have a conservative bandwidth estimate.  Then we enable trick play and switch to the trick-play track.  Once we play for a while, we know we have enough bandwidth, so we switch to high-res.  Since the high-res track doesn't have a trick play track, we just play the high-res track.

To a certain extent, this is working as intended.  When we are playing the high-res track, we can't switch to the trick-play track since you didn't specify we can in the manifest.  But we could make this a bit better for ABR track selection.  First, we could avoid switching to a track without a trick-play track if we have trick-play enabled.  Secondly, we should account for playback rate in calculating ABR.  I remember a bug for this, but I can't seem to find it now.

**Comment by joeyparrish** [comment] 2020-10-26 20:44
> Secondly, we should account for playback rate in calculating ABR. I remember a bug for this, but I can't seem to find it now.

I believe this was finally solved.  I'll see if I can find a reference.

**Comment by joeyparrish** [comment] 2020-10-26 20:45
Fixed by PR #2329, released in v3.0.0.

**Comment by jhnbwrs** [comment] 2020-10-26 20:51
I did try to implement associating both adaptation sets to the trick mode track by specify 

<EssentialProperty schemeIdUri="http://dashif.org/guidelines/trickmode" value="1 2"/>

That didn't seem to work -- I will have to revisit what issues that caused me.  

I gave up on that a bit because it wasn't working, and I couldn't see how you could determine the proper license to use if it was associated with 2 adaptation sets that require different licenses.  I guess I could put the content protection block into the trick mode adaptation set and then associate the trick mode track with both adaptation set 1 and 2.

If a trick mode track is associated with one adaptation set and adaptation set switching is allowed between the adaptation sets... Seems like you should be allowed to use the trick mode track for both adaptation sets.

Accounting for playback rate for ABR calculation seems like it should help, but if it is already merged it must not be helping.

**Comment by TheModMaker** [comment] 2020-10-26 20:58
The ABR manager sees the correct playback-rate, but the video is buffering a lot.  It could be that our code is wrong, our estimate is off, or your manifest doesn't have the correct `bandwidth` values.

**Comment by jhnbwrs** [comment] 2020-10-27 18:41
Dash conformance test states the following about this manifest:

Rep id v0 (audio) has a bandwidth of 129345 in the manifest and calculates to 128138 by conformance test
Rep id b (video) has a bandwidth of  599955 in the manifest and calculates to 599644 by conformance test
Rep id c (video) has a bandwidth of 1000130 in the manifest and calculates to 999505 by conformance test
Rep id 1 (trick mode) has a bandwidth of 139084 in the manifest and calculates to 203979 by conformance test

So the bandwidths are pretty accurate - Other than the bandwidth of the trickmode track, which we appear to be signaling to be of a lower bandwidth than it actually is by a significant margin.  The trick mode track still has by far the lowest bandwidth of any video track.  

If you engage trick mode for video, you are still downloading audio, at 8x it contributes far more to your bandwidth consumption that the trick mode video track.  Could the audio be causing the buffering?

**Comment by avelad** [comment] 2023-11-02 17:07
I have reviewed and with the main branch the problem does not occur, so I consider the issue resolved.

**Closed by avelad** 2023-11-02 17:07 UTC
Labels: type: enhancement, priority: P3
